### PR TITLE
Alternative fix for #4292 (problems with JMSDiExtraBundle interaction)

### LINKED ISSUE #4292: Conflict with DI extra bundle
Hi !

I have an issue with the last release of SonataAdminBundle (3.11.*). 

### Environment

* Environment dev
* Debug enabled
* PHP version 5.6.29-0+deb8u1

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.10.3             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.2.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master 9c6f293 Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.0              Symfony Sonata / Integrate Doctrine...
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
sonata-project/intl-bundle               dev-master d2eab1c Symfony SonataIntlBundle
sonata-project/media-bundle              dev-master master  

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP v...
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower...
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower...
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower...
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower...
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework

```

#### PHP version

PHP version 5.6.29-0+deb8u1

## Subject

With the last release of SonataAdmin, I have some issues with DI Extra Bundle see this issue https://github.com/schmittjoh/JMSDiExtraBundle/issues/266

All services are not found with basic service annotation:

```
/**
 * @DI\Service("app.indexer.category")
 */
class CategoryIndexer
```

Also, it could be a conflict with my JMS configuration:

```
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle, ApiBundle]
        directories: ["%kernel.root_dir%/../src"]
```

I tried to use `"jms/di-extra-bundle": "^1.7"` but the problem still persists...

My workaround so far: rollback to SonataAdminBundle 3.10.* :confused: 

## Steps to reproduce

1. Update to SonataAdminBundle 3.11.*
2. Declare services with JMSDiExtraBundle @DI\service()
3. Try to get the service (dep injection or get from container)

## Expected results

All services in AppBundle which uses DI annotation must be found as service.

## Actual results

Services declared with DI annotation are not found.

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                           
  The service "fos_elastica.listener.app.category" has a dependency on a non-existent service "app.indexer.category". 
```

Any idea ?

Thanks for your amazing work and your help !

If you need anything ask for it ! ;)

### PR DESCRIPTION
**Pull request by andreasferber**
I am targetting this branch, because issue #4292 concerns this branch.

Closes #4292 

## Changelog

```markdown
### Added
- Config option to disable autoregistration of annotations with `JMSDiExtraBundle`

### Fixed
- Fix #4292: don't overwrite `JMSDiExtraBundle` default configuration

### Deprecated
- auto registration of `JMSDiExtraBundle` annotations is now discouraged in favor of doing it manually
```

## Subject

As discussed in the comments for #4292, there are issues with the first proposed fix (#4312). This pull request provides a fix for the original issue using a different approach. In addition, it also makes the behaviour in question configurable so that users have a choice.

### CODE REVIEW

**Comment by andreasferber** [comment]
- coverage/coveralls fail: automatically testing this would be very hard, since i think it would basically require a full symfony setup, configuration and all
- codacy/pr fail: complains about two variable names that it deems too long, I don't want to add another commit just for that

File: DependencyInjection/SonataAdminExtension.php [hunk 1]
```diff
@@ -214,13 +214,47 @@ public function prepend(ContainerBuilder $container)
...
         $bundles = $container->getParameter('kernel.bundles');
 
-        if (isset($bundles['JMSDiExtraBundle'])) {
+        if (!isset($bundles['JMSDiExtraBundle'])) {
+            return;
+        }
+
+        $configs = $container->getExtensionConfig($this->getAlias());
+        $config = $this->processConfiguration(new Configuration(), $configs);
+        if (!$config['options']['enable_jms_di_extra_autoregistration']) {
```
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: A depreciation should be triggered inside this if, now or in another PR

File: DependencyInjection/SonataAdminExtension.php [hunk 2]
```diff
@@ -214,13 +214,47 @@ public function prepend(ContainerBuilder $container)
...
+        }
+
+        if ($annotationPatternsConfigured) {
+            $container->prependExtensionConfig(
+                'jms_di_extra',
+                array(
+                    'annotation_patterns' => array($sonataAdminPattern),
+                )
+            );
+        } else {
```
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: An early return can be used to avoid this else

File: DependencyInjection/SonataAdminExtension.php [hunk 3]
```diff
@@ -214,13 +214,47 @@ public function prepend(ContainerBuilder $container)
...
+            // get annotation_patterns default from DiExtraBundle configuration
+            $diExtraConfigDefinition = new \JMS\DiExtraBundle\DependencyInjection\Configuration();
```
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: Nice!

File: DependencyInjection/SonataAdminExtension.php (hunk 1 above)
Comment (andreasferber) [inline DependencyInjection/SonataAdminExtension.php]: I've added it a little bit further down the code so that it doesn't get triggered when the user has already added the necessary pattern manually in the jms_di_extra configuration.

File: DependencyInjection/SonataAdminExtension.php (hunk 2 above)
Comment (andreasferber) [inline DependencyInjection/SonataAdminExtension.php]: I have moved the prependExtensionConfig outside the if instead, I think it's more clear this way that in both cases a prepend gets done, but with different values.

File: DependencyInjection/SonataAdminExtension.php (hunk 1 above)
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: Yes sorry, I came back here to say just that, I was very tired yesterday evening.

File: DependencyInjection/SonataAdminExtension.php (hunk 2 above)
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: Good thinking!

**Comment by greg0ire** [comment]
So now there's a deprecation, there's a bit more work left to do : 

- add a note to the UPGRADE guide, explaining people what they need to do
- add `NEXT_MAJOR` comments in the code, explaining what to get rid of when preparing the next major release

File: Resources/doc/reference/annotations.rst [hunk 4]
```diff
@@ -10,6 +10,30 @@ All annotations require jms/di-extra-bundle, it can easily be installed by compo
...
+
+    .. code-block:: yaml
+
+        sonata_admin:
+            options:
+                enable_jms_di_extra_autoregistration: false
+
+.. note::
+
+    Starting with version 4.0, SonataAdminBundle will no longer register
```
Comment (greg0ire) [inline Resources/doc/reference/annotations.rst]: You can copy this to the UPGRADE guide

File: DependencyInjection/Configuration.php [hunk 5]
```diff
@@ -104,6 +104,10 @@ public function getConfigTreeBuilder()
                             ->defaultFalse()
                             ->info('Enable locking when editing an object, if the corresponding object manager supports it.')
                         ->end()
+                        ->booleanNode('enable_jms_di_extra_autoregistration')
+                            ->defaultTrue()
```
Comment (greg0ire) [inline DependencyInjection/Configuration.php]: `NEXT_MAJOR: default to false, and change the docs`

File: DependencyInjection/SonataAdminExtension.php [hunk 6]
```diff
@@ -208,22 +208,62 @@ public function load(array $configs, ContainerBuilder $container)
     /**
      * Allow an extension to prepend the extension configurations.
      *
+     * NEXT_MAJOR: remove all code that deals with JMSDiExtraBundle
```
Comment (greg0ire) [inline DependencyInjection/SonataAdminExtension.php]: Oh you already added some `NEXT_MAJOR` instructions, good.

File: DependencyInjection/Configuration.php [hunk 7]
```diff
@@ -104,6 +104,10 @@ public function getConfigTreeBuilder()
                             ->defaultFalse()
                             ->info('Enable locking when editing an object, if the corresponding object manager supports it.')
                         ->end()
+                        ->booleanNode('enable_jms_di_extra_autoregistration')
```
Comment (greg0ire) [inline DependencyInjection/Configuration.php]: `// NEXT_MAJOR: remove this`

File: UPGRADE-3.x.md [hunk 8]
```diff
@@ -1,6 +1,23 @@
 UPGRADE 3.x
 ===========
 
+UPGRADE FROM 3.13 to 3.14
+=========================
```
Comment (OskarStark) [inline UPGRADE-3.x.md]: no need for this 2 lines

**Comment by greg0ire** [comment]
Please associate your chaos-agency.de address with your github account if you want your contributions to show up in your profile. It will also help us find you back in case of problem.

File: UPGRADE-3.x.md [hunk 9]
```diff
@@ -1,6 +1,23 @@
...
+
+## Deprecated automatic annotation registration with JMSDiExtraBundle
+
+Starting with version 4.0, SonataAdminBundle will no longer register
+annotations with JMSDiExtraBundle automatically. Please add the following to
+your config.yml to register the annotations yourself:
+
+.. code-block:: yaml
```
Comment (greg0ire) [inline UPGRADE-3.x.md]: This is markdown, you need to use fenced code blocks here.

**Comment by greg0ire** [comment]
Thanks @andreasferber , I'll ask for a release right now!
