### PR TITLE
Hotfix of "Child _delete does not exist." error

### LINKED ISSUE #5483: appendformfield error child _delete does not exist
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.45.2 3.45.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.14.0 3.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.1 3.16.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.2  3.8.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.2.3  v4.2.3  Symfony Asset Component
symfony/browser-kit          v4.2.3  v4.2.3  Symfony BrowserKit Component
symfony/cache                v4.2.3  v4.2.3  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.3  v4.2.3  Symfony Config Component
symfony/console              v4.2.3  v4.2.3  Symfony Console Component
symfony/contracts            v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector         v4.2.3  v4.2.3  Symfony CssSelector Component
symfony/debug                v4.2.3  v4.2.3  Symfony Debug Component
symfony/debug-bundle         v4.2.3  v4.2.3  Symfony DebugBundle
symfony/debug-pack           v1.0.7  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection v4.2.3  v4.2.3  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.3  v4.2.3  Symfony Doctrine Bridge
symfony/dom-crawler          v4.2.3  v4.2.3  Symfony DomCrawler Component
symfony/dotenv               v4.2.3  v4.2.3  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.3  v4.2.3  Symfony EventDispatcher Component
symfony/expression-language  v4.2.3  v4.2.3  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.3  v4.2.3  Symfony Filesystem Component
symfony/finder               v4.2.3  v4.2.3  Symfony Finder Component
symfony/flex                 v1.2.0  v1.2.0  Composer plugin for Symfony
symfony/form                 v4.2.3  v4.2.3  Symfony Form Component
symfony/framework-bundle     v4.2.3  v4.2.3  Symfony FrameworkBundle
symfony/http-foundation      v4.2.3  v4.2.3  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.3  v4.2.3  Symfony HttpKernel Component
symfony/inflector            v4.2.3  v4.2.3  Symfony Inflector Component
symfony/intl                 v4.2.3  v4.2.3  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle         v1.11.3 v1.11.3 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget ab...
symfony/monolog-bridge       v4.2.3  v4.2.3  Symfony Monolog Bridge
symfony/monolog-bundle       v3.3.1  v3.3.1  Symfony MonologBundle
symfony/options-resolver     v4.2.3  v4.2.3  Symfony OptionsResolver Component
symfony/orm-pack             v1.0.6  v1.0.6  A pack for the Doctrine ORM
symfony/phpunit-bridge       v4.2.3  v4.2.3  Symfony PHPUnit Bridge
symfony/polyfill-ctype       v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu    v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.2.3  v4.2.3  Symfony Process Component
symfony/profiler-pack        v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access      v4.2.3  v4.2.3  Symfony PropertyAccess Component
symfony/property-info        v4.2.3  v4.2.3  Symfony Property Info Component
symfony/routing              v4.2.3  v4.2.3  Symfony Routing Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.3  v4.2.3  Symfony SecurityBundle
symfony/security-core        v4.2.3  v4.2.3  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.3  v4.2.3  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.3  v4.2.3  Symfony Security Component - Guard
symfony/security-http        v4.2.3  v4.2.3  Symfony Security Component - HTTP Integration
symfony/serializer           v4.2.3  v4.2.3  Symfony Serializer Component
symfony/serializer-pack      v1.0.2  v1.0.2  A pack for the Symfony serializer
symfony/stopwatch            v4.2.3  v4.2.3  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.5  v3.2.5  Symfony SwiftmailerBundle
symfony/templating           v4.2.3  v4.2.3  Symfony Templating Component
symfony/translation          v4.2.3  v4.2.3  Symfony Translation Component
symfony/twig-bridge          v4.2.3  v4.2.3  Symfony Twig Bridge
symfony/twig-bundle          v4.2.3  v4.2.3  Symfony TwigBundle
symfony/validator            v4.2.3  v4.2.3  Symfony Validator Component
symfony/var-dumper           v4.2.3  v4.2.3  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.2.3  v4.2.3  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link             v4.2.3  v4.2.3  Symfony WebLink Component
symfony/web-profiler-bundle  v4.2.3  v4.2.3  Symfony WebProfilerBundle
symfony/webpack-encore-pack  v1.0.3  v1.0.3  A pack for Symfony Encore
symfony/workflow             v4.2.3  v4.2.3  Symfony Workflow Component
symfony/yaml                 v4.2.3  v4.2.3  Symfony Yaml Component

```

#### PHP version

```
 $ php -v
PHP 7.2.15 (cli) (built: Feb  9 2019 03:10:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

commit c7ca519dddf51d676b70801e0a7ed7d1a8d5beb1 introduced a bug in my project.
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AdminHelper.php#L203

for a collection form field  with 

```
'type_options' => [
    'delete' => false,
],
```
when you click add  on the collection  you get ´Child "_delete" does not exist.´

```
Symfony\Component\Form\Exception\OutOfBoundsException:
Child "_delete" does not exist.

  at vendor/symfony/form/Form.php:946
  at Symfony\Component\Form\Form->get('_delete')
     (vendor/sonata-project/admin-bundle/src/Admin/AdminHelper.php:203)
  at Sonata\AdminBundle\Admin\AdminHelper->appendFormFieldElement(object(ProjectContactAdmin), object(ProjectContact), 'selion_project_contact_contactAttempts')
     (vendor/sonata-project/admin-bundle/src/Action/AppendFormFieldElementAction.php:84)
  at Sonata\AdminBundle\Action\AppendFormFieldElementAction->__invoke(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:150)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:67)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:37)
```
## fix

```
    if ($childField->has('_delete')) {
        $childField->get('_delete')->setData(isset($toDelete[$i]) && $toDelete[$i]);
        ++$i;
    }
´´´

### PR DESCRIPTION
**Pull request by SerafimArts**
Closes #5483 Hotfix

```markdown
### Fixed
-  Crash when clicking "add" on a collection
```

### CODE REVIEW

**Comment by kunicmarko20** [comment]
@sad270 could you review this?

File: src/Admin/AdminHelper.php [hunk 1]
```diff
@@ -200,7 +200,9 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
         if (\count($toDelete) > 0) {
             $i = 0;
             foreach ($finalForm->get($childFormBuilder->getName()) as $childField) {
-                $childField->get('_delete')->setData(isset($toDelete[$i]) && $toDelete[$i]);
+                if ($childField->has('_delete')) {
```
Comment (core23) [inline src/Admin/AdminHelper.php]: Can you create a constant for this?

Comment (SerafimArts) [reply src/Admin/AdminHelper.php]: This, of course, is possible, but are you sure that this is the smallest problem in this code? It seems to me that such improvements will not greatly affect the quality, because this code needs to be completely rewritten.

Comment (SerafimArts) [reply src/Admin/AdminHelper.php]: UPD: Fixed

File: src/Admin/AdminHelper.php [hunk 2]
```diff
@@ -115,7 +120,7 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
                 $i = 0;
                 foreach ($formData[$childFormBuilder->getName()] as $name => &$field) {
                     $toDelete[$i] = false;
-                    if (\array_key_exists('_delete', $field)) {
+                    if (\array_key_exists(self::FORM_FIELD_DELETE, $field)) {
                         $toDelete[$i] = true;
                         unset($field['_delete']);
```
Comment (phansys) [inline src/Admin/AdminHelper.php]: This should be updated to use the new constant too.

**Comment by sad270** [comment]
Ok for me, this PR fix the issue and doesn't broke my fix.

File: src/Admin/AdminHelper.php [hunk 3]
```diff
@@ -29,6 +29,11 @@
  */
 class AdminHelper
 {
+    /**
+     * @var string
+     */
+    private const FORM_FIELD_DELETE = '_delete';
+
```
Comment (VincentLanglet) [inline src/Admin/AdminHelper.php]: There is extra spaces to remove on this line

**Comment by VincentLanglet** [comment]
@SerafimArts Hi ! Can you fix your PR ? :)
I'll be happy having the fix merged

**Comment by SerafimArts** [comment]
@VincentLanglet I watch this PR like a comedy. 

Understand me correctly, it's not difficult for me to fix...

But on the other hand, for 3 months the project simply does not work. Аnd the core developers are discussing about spacers, instead of merging and fixing. I would understand more when the code is normally written. But in this form, it is suitable to immediately send it to the trash.

This is some kind of surrealism...

**Comment by VincentLanglet** [comment]
@SerafimArts The core developers are taking time for the project. They don't have to, they have a real life and a family. There are plenty of bug to fix and feature to add, they can't be everywhere. It's not simple to be maintainers of such a big project.
 
It's nice from you to make this PR to fix this bug. They just asked for a little change and the linters are actually failing because of this https://github.com/SerafimArts/SonataAdminBundle/pull/1/files
It's not because a PR fix a bug that we have to merge it at any price and breaking the CI.

By the way, they will certainly ask you to squash your commit.
But if you don't want to fix your PR, I'll create a new one that's not a problem for me. I'll be happy to help the community.

**Comment by OskarStark** [comment]
Thank you @SerafimArts 👍🏻

File: src/Admin/AdminHelper.php [hunk 4]
```diff
@@ -200,7 +205,9 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
         if (\count($toDelete) > 0) {
             $i = 0;
             foreach ($finalForm->get($childFormBuilder->getName()) as $childField) {
-                $childField->get('_delete')->setData(isset($toDelete[$i]) && $toDelete[$i]);
+                if ($childField->has(self::FORM_FIELD_DELETE)) {
+                    $childField->get(self::FORM_FIELD_DELETE)->setData(isset($toDelete[$i]) && $toDelete[$i]);
```
Comment (greg0ire) [inline src/Admin/AdminHelper.php]: Isn't that the same as

```suggestion
                    $childField->get(self::FORM_FIELD_DELETE)->setData($toDelete[$i] ?? false);
```

?

**Comment by greg0ire** [comment]
Writing tests will not be easy: only half of the method is covered by tests: https://coveralls.io/builds/24174994/source?filename=src%2FAdmin%2FAdminHelper.php#L153 Anyone up to the task?

**Comment by phansys** [comment]
I'm working on the test.

**Comment by phansys** [comment]
I'm currently blocked with the last (and more important) part of the test. Basically, I'm testing blindly because I didn't check yet where is this class used in a real life application.
This is what I have so far: https://github.com/SerafimArts/SonataAdminBundle/compare/patch-1...phansys:pr_5532.
If someone know how to resolve the failure, please let me know. I'll try to continue this WIP later.

**Comment by VincentLanglet** [comment]
If nobody knows, I think we should merge this PR like this. 
The best is the enemy of the good. This is still a bugfix and this will be useful.

But good luck with the test, i hope you'll find a solution :)

**Comment by phansys** [comment]
Could someone experiencing this issue share the steps required to reproduce it?
I have tested by clicking on the "Add new" button of a collection, and there is nothing broken on my side:

image

I'm now are able to -at least- know how `AdminHelper::appendFormFieldElement()` works, since I saw  the "Add new" request calling it.

**Comment by greg0ire** [comment]
> Could someone experiencing this issue share the steps required to reproduce it?

cc @selion05 @kcoissard @thomasBourdin @msphn @adevyatov @VadimSushin @terox

**Comment by greg0ire** [comment]
> If nobody knows, I think we should merge this PR like this.

Maybe merge now and add the test later :sweat_smile: At least we know it has been manually tested

**Comment by phansys** [comment]
It's fine for me to merge it AS IS, but IMO we should know how to reproduce the issue. Otherwise we can't be sure of what it fixes or if the proposed change is the right fix.

**Comment by SerafimArts** [comment]
> Could someone experiencing this issue share the steps required to reproduce it?

@phansys https://github.com/sonata-project/SonataAdminBundle/issues/5483

**Comment by VincentLanglet** [comment]
@phansys I add the bug with a user who had the `CREATE` role and not the `DELETE` role. I'll maybe have time to look tomorrow, but according to https://github.com/sonata-project/SonataAdminBundle/issues/5483, this PR fix the bug.

**Comment by phansys** [comment]
Great! Thanks for the feedback!
I have updated the tests, there are no errors now :smile:
I need to get the form children in order to check the presence of the "_delete" form input.
I'll try to destinate more time for this today, but I'd be happy if it is solved before :wink:

**Comment by phansys** [comment]
I've pushed the [latest changes to the tests](https://github.com/SerafimArts/SonataAdminBundle/compare/patch-1...phansys:pr_5532). I think they can be improved a lot, but they work well as start point. Please, try to add more if you can. Even check if the input options can be respected.
Thank you in advance.

File: tests/Admin/AdminHelperTest.php [hunk 5]
```diff
@@ -155,6 +161,107 @@ public function testItThrowsExceptionWhenDoesNotFindTheFullPath(): void
         $this->helper->getElementAccessPath($path, $object);
     }
 
+    public function testAppendFormFieldElement(): void
+    {
+        $container = $this->createMock(ContainerInterface::class);
```
Comment (core23) [inline tests/Admin/AdminHelperTest.php]: Not a blocker, but this method is very long. It would help if you could extract some methods (e.g. prepareAdmin, assertForm, ...), so the test is more readable.

Comment (OskarStark) [reply tests/Admin/AdminHelperTest.php]: Let’s do it in another PR and go forward here, it’s blocking a real project 👍🏻

**Comment by Selion05** [comment]
> > Could someone experiencing this issue share the steps required to reproduce it?

on a oneToMany relation add this to your form 
        $form->add('values', CollectionType::class, [
            'type_options' => [
                'delete' => false,
            ],
        ]);

**Comment by kcoissard** [comment]
> > > Could someone experiencing this issue share the steps required to reproduce it?
> 
> on a oneToMany relation add this to your form
> 
> ```
>         $form->add('values', CollectionType::class, [
>             'type_options' => [
>                 'delete' => false,
>             ],
>         ]);
> ```

Indeed, it's ok now.

Thank you and good job everyone.

**Comment by greg0ire** [comment]
Just released this bugfix. Thank you almost everyone.

> @VincentLanglet I watch this PR like a comedy.
> Understand me correctly, it's not difficult for me to fix...
> But on the other hand, for 3 months the project simply does not work. Аnd the core developers are discussing about spacers, instead of merging and fixing. I would understand more when the code is normally written. But in this form, it is suitable to immediately send it to the trash.
> This is some kind of surrealism...

@SerafimArts please don't do that again, it's really not OK.

1. It would not have been easy for you to fix this, because the main difficulty of this PR was not getting the cs right, or even coming up with the fix. It was to write the tests, and you didn't do it.
2. You did not bother respecting the PR template that we wrote to make our maintainers life a bit easier, which should be understandable given the sheer amount of pull requests we have to deal with on a daily basis.
3. You argued that the code is bad as a reason to make it worse by adding more untested code to it, that's really fallacious. We are trying to slowly get to better quality so that you do not have to suffer from that many bugs and you chose to make these efforts worthless.
4. You say we argue about spaces when in fact our CI does it for us, and we tried to point that out to you so that you could fix the build of your PR, which we cannot merge otherwise.

Anyway, thanks for starting this I guess, but bear in mind that we're not really happy for being criticized about code we did not write, and in my case, do not even use. Getting us to quit maintaining this project is not what you want to do.

**Comment by SerafimArts** [comment]
@greg0ire The term "hotfix" just says that PR was written in haste.

**Comment by core23** [comment]
We can only gurante a better code stability by writing tests and improving docs, so we don't introduce new bugs with a hotfix

**Comment by SerafimArts** [comment]
Well, I don't want to argue anymore.

In any case, I want to apologize to those who might be offended by my words.

And to you @core23, as a community member, I suggest connecting the style-ci (https://styleci.io/) to avoid a lot of problems with whitespaces in the future.

**Comment by greg0ire** [comment]
@SerafimArts thanks for apologizing, I can't speak for others by I was indeed offended. Stay kind 👍

**Comment by greg0ire** [comment]
> I would completely agree with you if it were PR with improving the code or adding new functionality. But this is just a correction of the sonata, which has not worked for two months...

That does not make it an emergency. The latest version might not work, but you can still use previous versions. We have had the case in the past of untested "fixes" actually breaking things even more, that's very real I assure you. We don't need more of this.
