### PR TITLE
Replace $container `has` check with `hasParameter`

### LINKED ISSUE #7768: Using `$container->has('security.acl.provider')` fails even if `symfony/acl-bundle` is present
#### Sonata packages

<details><summary>show</summary>
<p>

```
sonata-project/admin-bundle              4.9.0   The missing Symfony Admin Generator
sonata-project/block-bundle              4.10.0  Symfony SonataBlockBundle
sonata-project/cache                     2.2.0   Cache library
sonata-project/doctrine-extensions       1.16.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.2.6   Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.11.0  Lightweight Exporter library
sonata-project/form-extensions           1.13.1  Symfony form extensions

```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
symfony/acl-bundle                       v2.3.0  Symfony AclBundle
symfony/amqp-messenger                   v5.4.5  Symfony AMQP extension Messenger Bridge
symfony/asset                            v5.4.3  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                      v5.4.3  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                            v5.4.5  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts                  v2.5.0  Generic abstractions related to caching
symfony/config                           v5.4.3  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                          v5.4.5  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector                     v5.4.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle                     v5.4.3  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dependency-injection             v5.4.5  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts            v3.0.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge                  v5.4.5  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger               v5.4.3  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                      v5.4.5  Eases DOM navigation for HTML and XML documents
symfony/dotenv                           v5.4.5  Registers environment variables from a .env file
symfony/error-handler                    v5.4.3  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher                 v5.4.3  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts       v3.0.0  Generic abstractions related to dispatching event
symfony/expression-language              v5.4.3  Provides an engine that can compile and evaluate expressions
symfony/filesystem                       v5.4.5  Provides basic utilities for the filesystem
symfony/finder                           v5.4.3  Finds files and directories via an intuitive fluent interface
symfony/flex                             v2.1.6  Composer plugin for Symfony
symfony/form                             v5.4.5  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle                 v5.4.5  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                      v5.4.5  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts            v2.5.0  Generic abstractions related to HTTP clients
symfony/http-foundation                  v5.4.5  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                      v5.4.5  Provides a structured process for converting a Request into a Response
symfony/intl                             v5.4.5  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/mailer                           v5.4.5  Helps sending emails
symfony/maker-bundle                     v1.38.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                        v5.4.3  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                             v5.4.3  Allows manipulating MIME messages
symfony/monolog-bridge                   v5.4.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle                   v3.7.1  Symfony MonologBundle
symfony/notifier                         v5.4.3  Sends notifications via one or more channels (email, SMS, ...)
symfony/options-resolver                 v5.4.3  Provides an improved replacement for the array_replace PHP function
symfony/panther                          v2.0.1  A browser testing and web scraping library for PHP and Symfony.
symfony/password-hasher                  v5.4.3  Provides password hashing utilities
symfony/phpunit-bridge                   v6.0.3  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme           v1.24.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu                v1.24.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn                v1.24.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer         v1.24.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring                v1.24.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.20.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php73                   v1.24.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80                   v1.24.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81                   v1.24.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/process                          v5.4.5  Executes commands in sub-processes
symfony/property-access                  v5.4.5  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info                    v5.4.3  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge             v5.4.3  Provides integration for ProxyManager with various Symfony components
symfony/redis-messenger                  v5.4.5  Symfony Redis extension Messenger Bridge
symfony/routing                          v5.4.3  Maps an HTTP request to a set of configuration variables
symfony/runtime                          v5.4.5  Enables decoupling PHP applications from global state
symfony/security-acl                     v3.3.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle                  v5.4.5  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core                    v5.4.5  Symfony Security Component - Core Library
symfony/security-csrf                    v5.4.3  Symfony Security Component - CSRF Library
symfony/security-guard                   v5.4.3  Symfony Security Component - Guard
symfony/security-http                    v5.4.5  Symfony Security Component - HTTP Integration
symfony/serializer                       v5.4.5  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts                v2.4.1  Generic abstractions related to writing services
symfony/stopwatch                        v5.4.5  Provides a way to profile code
symfony/string                           v5.4.3  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                      v5.4.5  Provides tools to internationalize your application
symfony/translation-contracts            v2.5.0  Generic abstractions related to translation
symfony/twig-bridge                      v5.4.5  Provides integration for Twig with various Symfony components
symfony/twig-bundle                      v5.4.3  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                        v5.4.5  Provides tools to validate values
symfony/var-dumper                       v5.4.5  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter                     v5.4.3  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                         v5.4.3  Manages links between resources
symfony/web-profiler-bundle              v5.4.5  Provides a development tool that gives detailed information about the execution of any request
symfony/webapp-meta                      v1.0.0  A meta package for the web app pack
symfony/webpack-encore-bundle            v1.14.0 Integration with your Symfony app & Webpack Encore!
symfony/yaml                             v5.4.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
PHP 8.1.3 (cli) (built: Feb 16 2022 01:00:24) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.3, Copyright (c), by Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans

```

## Subject

Trying to configure Sonata admin bundle with Symfony acl bundle gives me a headache because of fail fast check.
`vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php`
processes extension configuration one by one. It processes acl bundle, sets up all the required configuration, wires services.
When `symfony/acl-bundle` container extension is being loaded into `$tmpContainer` it has the service after it processes the configuration. So at that point it would pass `if (!$container->has('security.acl.provider')) ...` check.

Now after that more bundles are loaded, and eventually `sonata_admin` extension wants to load. When `$tmpContainer` is created it does not get services from previous extensions, but it gets parameter bag through `$resolvingBag` which at least keeps parameters when different extension loads.

The problem I encountered happens when I use Sonata admin and acl bundle. I was following these steps:
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/security/

When I tried configuring acl, I ran into this issue, which was a fix for https://github.com/sonata-project/SonataAdminBundle/issues/7613

After a lot of debugging and wondering why things are the way they are, I can't find a better solution than to:
- change `$container->has('security.acl.provider')` to `$container->hasParameter('security.acl.provider')`
- explicitly configure parameter `security.acl.provider: 'Symfony\Component\Security\Acl\Dbal\MutableAclProvider'` when working with these 2 bundles

## Steps to reproduce
For SF5 fresh project:
- Add `sonata-project/admin-bundle` and `sonata-project/doctrine-orm-admin-bundle`
- Add `symfony/acl-bundle`

Try to configure sonata admin security so that it works with acl bundle

## Expected results
Both bundles working together

## Actual results
with `has` check:
```
 bin/console c:c

In SonataAdminExtension.php line 159:
                                                                                                                                              
  The "security.acl.provider" service is needed to use ACL as security handler. You MUST install and enable the "symfony/acl-bundle" bundle.  
                                                                                                                                              
```
with `hasParameter` check and explicitly configuring parameter:
```
# services.yaml
parameters:
    security.acl.provider: 'Symfony\Component\Security\Acl\Dbal\MutableAclProvider'
```
```

 bin/console c:c

 // Clearing the cache for the dev environment with debug true                                                          
                                                                                                                        
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.                                            
                                                                                                                        
```

### PR DESCRIPTION
**Pull request by Buratinas**
When extensions are being loaded one by one into tmpContainer inside
`vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php`
`sonata_admin` configuration is loaded alone, and other extension services are not present.
By replacing `has` check with `hasParameter` check we can make sure parameter exists instead of service.
Since we can easily configure extra parameter,
but to get service we would need to load most of the acl bundle extension services.

## Subject

I am targeting this branch, because I'm working with this and it's the latest branch.

Closes #7768.

## Changelog

```markdown
### Fixed
- Improve detection of Symfony ACL bundle installation
```

### CODE REVIEW

File: src/DependencyInjection/SonataAdminExtension.php [hunk 1]
```diff
@@ -144,7 +144,7 @@ public function load(array $configs, ContainerBuilder $container): void
 
                 break;
             case 'sonata.admin.security.handler.acl':
-                if (!$container->has('security.acl.provider')) {
+                if (!$container->hasParameter('security.acl.provider')) {
```
Comment (jordisala1991) [inline src/DependencyInjection/SonataAdminExtension.php]: why don't we instead check for the presence of the bundle enabled?, something like:

```suggestion
                if (!isset($bundles['AclBundle'])) {
```

Comment (Buratinas) [reply src/DependencyInjection/SonataAdminExtension.php]: that actually might work better. I was checking bundles in compiler passes and extensions and it never came to my mind to simply replace this check with bundle check, although I wonder if that's the only bundle which can do ACL. I'll add it in front and I guess I can leave this as fallback since it should work with simple or statement.

Comment (jordisala1991) [reply src/DependencyInjection/SonataAdminExtension.php]: Keep in mind that the only integration we support is that bundle, We use some interfaces from there and dependencies also declared there. I wouldn't compplicate it any further, to me we should remove other checks and leave only the bundle one, wdyt @VincentLanglet ?

Comment (Buratinas) [reply src/DependencyInjection/SonataAdminExtension.php]: I thought this might be the case. If support is only with `symfony/acl-bundle`, then bundle check and error message change should be enough - if it only checks if bundle exists, then the message should probably not mention `security.acl.provider` at all, just the part with required bundle.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thank you @Buratinas
