### PR TITLE
Fix for #4267

### LINKED ISSUE #4267: Admin-Generator ignore question answer
#### Sonata packages

```bash
$ composer show | grep sonata-project

sonata-project/admin-bundle              3.10.3             The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.1.2              Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.2              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show | grep symfony
symfony/assetic-bundle                   v2.8.1             Integrates Assetic into Symfony2
symfony/monolog-bundle                   2.12.0             Symfony MonologBundle
symfony/polyfill-intl-icu                v1.3.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0             Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.4.2             Symfony SwiftmailerBundle
symfony/symfony                          v3.2.1             The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.0 (cli) (built: Dec  2 2016 09:19:56) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

Admin Generator updates `services.yml` even if I answer the question with no.

## Steps to reproduce

Run `./bin/console sonata:admin:generate`
Answer the question `Do you want to update the services YAML configuration file [yes]?` with no.

## Expected results

If I answer with no then my services.yml should not be updated.

## Actual results

A new services.yml (I use in my project services.xml) was created with the admin-class service defintion

### PR DESCRIPTION
**Pull request by floriansemm**
I am targetting this branch, because of a bug-fix.

Closes #4267 

## Changelog

Set `services` option default-value to null in command `Sonata\AdminBundle\Command\GenerateAdminCommand`

## To do

- [x] Update the tests

## Subject

Fix for #4267 

If I answer the question `Do you want to update the services YAML configuration file [yes]?` with no, then `interact` sets no value for `services` which is ok. 

Then the command checks in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Command/GenerateAdminCommand.php#L135 if a service-file is set, which is always true because of the default value `->addOption('services', 'y', InputOption::VALUE_OPTIONAL, 'The services YAML file', 'services.yml')`.

### CODE REVIEW

File: Tests/Command/GenerateAdminCommandTest.php [hunk 1]
```diff
@@ -48,6 +49,8 @@ class GenerateAdminCommandTest extends \PHPUnit_Framework_TestCase
 
     protected function setUp()
     {
+        error_reporting(E_ALL & ~E_STRICT & ~E_DEPRECATED);
```
Comment (OskarStark) [inline Tests/Command/GenerateAdminCommandTest.php]: this should be removed

File: Command/GenerateAdminCommand.php [hunk 2]
```diff
@@ -53,7 +53,7 @@ public function configure()
             ->addOption('admin', 'a', InputOption::VALUE_OPTIONAL, 'The admin class basename')
             ->addOption('controller', 'c', InputOption::VALUE_OPTIONAL, 'The controller class basename')
             ->addOption('manager', 'm', InputOption::VALUE_OPTIONAL, 'The model manager type')
-            ->addOption('services', 'y', InputOption::VALUE_OPTIONAL, 'The services YAML file', 'services.yml')
+            ->addOption('services', 'y', InputOption::VALUE_OPTIONAL, 'The services YAML file', null)
```
Comment (OskarStark) [inline Command/GenerateAdminCommand.php]: not sure this is the correct fix @greg0ire

Comment (greg0ire) [inline Command/GenerateAdminCommand.php]: It does look weird. IMO the changed code should be in `interact()`, this for when you use the command in non-interactive mode, by passing options.

Comment (floriansemm) [inline Command/GenerateAdminCommand.php]: I did not know that there is a no-interaction mode

File: Command/GenerateAdminCommand.php [hunk 3]
```diff
@@ -228,6 +228,8 @@ protected function interact(InputInterface $input, OutputInterface $output)
             );
             $input->setOption('services', $servicesFile);
             $input->setOption('id', $id);
+        } else {
+            $input->setOption('services', false);
```
Comment (greg0ire) [inline Command/GenerateAdminCommand.php]: This looks like a better fix! 👍

**Comment by greg0ire** [comment]
Tell us if you need any help fixing this issue.

**Comment by floriansemm** [comment]
all tests are green now

File: Tests/Command/GenerateAdminCommandTest.php [hunk 4]
```diff
@@ -384,4 +384,108 @@ public function testValidateManagerTypeWithException3()
...
+     */
+    public function testAnswerUpdateServicesWithNo()
+    {
+        $this->container->set('sonata.admin.manager.foo', $this->getMock('Sonata\AdminBundle\Model\ModelManagerInterface'));
+
+        $modelEntity = 'Sonata\AdminBundle\Tests\Fixtures\Bundle\Entity\Foo';
+
+        $command = $this->application->find('sonata:admin:generate');
+
+        if (class_exists('Sensio\Bundle\GeneratorBundle\Command\Helper\DialogHelper')) {
```
Comment (greg0ire) [inline Tests/Command/GenerateAdminCommandTest.php]: Please add a `NEXT_MAJOR` explaining when we can get rid of the condition. See CONTRIBUTING.md

File: Tests/Command/GenerateAdminCommandTest.php [hunk 5]
```diff
@@ -384,4 +384,108 @@ public function testValidateManagerTypeWithException3()
         $this->setExpectedException('InvalidArgumentException', 'Invalid manager type "baz". Available manager types are "".');
         $this->command->validateManagerType('baz');
     }
+
+    /**
+     * @group admin-gen
```
Comment (greg0ire) [inline Tests/Command/GenerateAdminCommandTest.php]: What is the purpose of this?

**Comment by greg0ire** [comment]
@OskarStark , review and merge?

**Comment by OskarStark** [comment]
Thank you @floriansemm 👍
