### PR TITLE
Fix batch action proxy query parameter name requirement

### LINKED ISSUE #7869: Cannot autowire argument exception in batch action when using 4.13.0
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.13.1 4.13.1 The missing Symfony Admin Generator
sonata-project/block-bundle              4.14.0 4.14.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
Package sonata-project/cache is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       1.17.0 1.17.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.3.0  4.3.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.13.0 2.13.0 Lightweight Exporter library
sonata-project/form-extensions           1.17.1 1.17.1 Symfony form extensions
sonata-project/twig-extensions           1.10.0 1.10.0 Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v6.1.0  v6.1.0  Symfony AMQP extension Messenger Bridge
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v6.1.0  v6.1.0  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v6.1.2  v6.1.2  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v3.1.1  v3.1.1  Generic abstractions related to caching
symfony/config                     v6.1.0  v6.1.0  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v6.1.2  v6.1.2  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v6.1.0  v6.1.0  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v6.1.0  v6.1.0  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge ...
symfony/dependency-injection       v6.1.2  v6.1.2  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.1.1  v3.1.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v6.1.2  v6.1.2  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v6.1.1  v6.1.1  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v6.1.0  v6.1.0  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v6.1.0  v6.1.0  Registers environment variables from a .env file
symfony/error-handler              v6.1.0  v6.1.0  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v6.1.0  v6.1.0  Provides tools that allow your application components to communicate with each other by dispatching events a...
symfony/event-dispatcher-contracts v3.1.1  v3.1.1  Generic abstractions related to dispatching event
symfony/expression-language        v6.1.2  v6.1.2  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v6.1.0  v6.1.0  Provides basic utilities for the filesystem
symfony/finder                     v6.1.0  v6.1.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.2.2  v2.2.2  Composer plugin for Symfony
symfony/form                       v6.1.2  v6.1.2  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v6.1.2  v6.1.2  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v6.1.2  v6.1.2  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v3.1.1  v3.1.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v6.1.2  v6.1.2  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v6.1.2  v6.1.2  Provides a structured process for converting a Request into a Response
symfony/intl                       v6.1.0  v6.1.0  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/lock                       v6.1.1  v6.1.1  Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mailer                     v6.1.2  v6.1.2  Helps sending emails
symfony/maker-bundle               v1.43.0 v1.43.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget a...
symfony/messenger                  v6.1.2  v6.1.2  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v6.1.1  v6.1.1  Allows manipulating MIME messages
symfony/monolog-bridge             v6.1.2  v6.1.2  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.8.0  v3.8.0  Symfony MonologBundle
symfony/options-resolver           v6.1.0  v6.1.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v6.1.0  v6.1.0  Provides password hashing utilities
symfony/phpunit-bridge             v6.1.2  v6.1.2  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype             v1.26.0 v1.26.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.26.0 v1.26.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.26.0 v1.26.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.26.0 v1.26.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.26.0 v1.26.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.26.0 v1.26.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php80             v1.26.0 v1.26.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v6.1.0  v6.1.0  Executes commands in sub-processes
symfony/property-access            v6.1.0  v6.1.0  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v6.1.2  v6.1.2  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v6.1.0  v6.1.0  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.1.2  v2.1.2  PSR HTTP message bridge
symfony/rate-limiter               v6.1.0  v6.1.0  Provides a Token Bucket implementation to rate limit input and output in your application
symfony/routing                    v6.1.1  v6.1.1  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v6.1.1  v6.1.1  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.1  v3.3.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v6.1.0  v6.1.0  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v6.1.2  v6.1.2  Symfony Security Component - Core Library
symfony/security-csrf              v6.1.0  v6.1.0  Symfony Security Component - CSRF Library
symfony/security-http              v6.1.2  v6.1.2  Symfony Security Component - HTTP Integration
symfony/serializer                 v6.1.2  v6.1.2  Handles serializing and deserializing data structures, including object graphs, into array structures or oth...
symfony/service-contracts          v3.1.1  v3.1.1  Generic abstractions related to writing services
symfony/stopwatch                  v6.1.0  v6.1.0  Provides a way to profile code
symfony/string                     v6.1.2  v6.1.2  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in ...
symfony/templating                 v6.1.0  v6.1.0  Provides all the tools needed to build any kind of template system
symfony/translation                v6.1.0  v6.1.0  Provides tools to internationalize your application
symfony/translation-contracts      v3.1.1  v3.1.1  Generic abstractions related to translation
symfony/twig-bridge                v6.1.2  v6.1.2  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v6.1.1  v6.1.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v6.1.1  v6.1.1  Provides tools to validate values
symfony/var-dumper                 v6.1.0  v6.1.0  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v6.1.1  v6.1.1  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v6.1.0  v6.1.0  Manages links between resources
symfony/web-profiler-bundle        v6.1.2  v6.1.2  Provides a development tool that gives detailed information about the execution of any request
symfony/yaml                       v6.1.2  v6.1.2  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.1.4 (cli) (built: Apr  4 2022 13:30:17) (NTS)
```

## Subject

When upgrading to [4.13.0](https://github.com/sonata-project/SonataAdminBundle/releases/tag/4.13.0), my batch actions didn't work anymore. I get this exception:
```
Cannot autowire argument $proxyQuery of "App\Controller\Admin\CostController::batchReviewedAction()": it references interface "Sonata\AdminBundle\Datagrid\ProxyQueryInterface" but no such service exists. Did you create a class that implements this interface?
```

I think the issue started in #7819, because it depend on the parameter $query (see https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Controller/CRUDController.php#L1512), but my parameter was called $proxyQuery. Maybe more user will get this problem.

If I rename my parameter to $query it works, but I think this is a BC break and not sure if you want to depend on the name of the parameter. Isn't it possible to depend on the interface ProxyQueryInterface instead of the parameter $query, someway?

### PR DESCRIPTION
**Pull request by mpoiriert**
## Subject

I am targeting this branch, because the BC break was introduce in this branch.

Closes #7869 .

## Changelog

```markdown
### Fixed
 - Batch action ProxyQueryInterface parameter don't have to be named $query anymore.
```

### CODE REVIEW

**Comment by mpoiriert** [comment]
I will ad integration testing.

**Comment by mpoiriert** [comment]
@VincentLanglet I have two issue with that PR:

The php linter (cs fixer) don't succeed on files that I didn't change.

I have added integration test and with "highest" it fail because session doesn't seem to exists. It's working from composer install. I need a session to generate a csrf token in sonata.batch context from the integration test of calling a batch action from another controller with query parameter not named $query.

**Comment by VincentLanglet** [comment]
For the linter seems like it's related to
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6470
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6471

Just ignore it. I'll see what I can do

For the session ; maybe you can set one ?

**Comment by mpoiriert** [comment]
@VincentLanglet I manage to use the crawler to get the generate csrf token so everything is fine now. I have sqashed my commit. Ready to review.

**Comment by VincentLanglet** [comment]
For the linter seems like it will be fixed soon https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6473

File: tests/Fixtures/Controller/BatchOtherController.php [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+ */
+
+namespace Sonata\AdminBundle\Tests\Fixtures\Controller;
+
+use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
+use Symfony\Component\HttpFoundation\Response;
+
+class BatchOtherController
+{
+    public function batchAction(ProxyQueryInterface $proxyQuery): Response
```
Comment (VincentLanglet) [inline tests/Fixtures/Controller/BatchOtherController.php]:
```suggestion
    public function batchAction(ProxyQueryInterface $aCustomNameForTheProxyQuery): Response
```
Maybe ?

**Comment by VincentLanglet** [comment]
With your approval @jordisala1991, I consider to force the merge and release a bugfix tomorrow even if the linter is not fixed.

**Comment by jordisala1991** [comment]
Now the errors on linters look better.

**Comment by VincentLanglet** [comment]
Indeed, do you mind fix the linter errors (even if it's not coming from your changes) @mpoiriert ?

**Review by VincentLanglet — DISMISSED** [review]

File: tests/ArgumentResolver/ProxyQueryResolverTest.php [hunk 2]
```diff
@@ -0,0 +1,107 @@
...
+namespace Sonata\AdminBundle\Tests\ArgumentResolver;
+
+use PHPUnit\Framework\TestCase;
+use Sonata\AdminBundle\ArgumentResolver\ProxyQueryResolver;
+use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface;
+use Symfony\Component\HttpKernel\ControllerMetadata\ArgumentMetadata;
+
+class ProxyQueryResolverTest extends TestCase
```
Comment (jordisala1991) [inline tests/ArgumentResolver/ProxyQueryResolverTest.php]:
```suggestion
final class ProxyQueryResolverTest extends TestCase
```

File: tests/Fixtures/Controller/BatchOtherController.php [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\AdminBundle\Tests\Fixtures\Controller;
+
+use Sonata\AdminBundle\Datagrid\ProxyQueryInterface;
+use Symfony\Component\HttpFoundation\Response;
+
+class BatchOtherController
```
Comment (jordisala1991) [inline tests/Fixtures/Controller/BatchOtherController.php]:
```suggestion
final class BatchOtherController
```

File: src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php [hunk 4]
```diff
@@ -358,7 +358,7 @@ private function getDefaultMethodCalls(ContainerBuilder $container, string $serv
             );
 
         // NEXT_MAJOR: Uncomment the exception instead of the deprecation.
-            // throw new InvalidArgumentException(sprintf('Missing tag information "model_class" on service "%s".', $serviceId));
+        // throw new InvalidArgumentException(sprintf('Missing tag information "model_class" on service "%s".', $serviceId));
```
Comment (jordisala1991) [inline src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php:361]: I would say both lines should be indented 4 more spaces.

**Comment by mpoiriert** [comment]
Done, rebases, kept php-cs-fix commit separately, since it's affecting unrelated code.

**Review by VincentLanglet — APPROVED** [review]
