### PR TITLE
Use class for ancestors and remove set parent as current

### LINKED ISSUE #4805: Composer update fails
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.26.0 3.27.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.7.0  3.7.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.6.0  3.7.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.0  2.3.0  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.7  3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.3  3.2.3  Symfony SonataFormatterBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.6.1  v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.3.0  v3.1.2  Symfony MonologBundle
symfony/polyfill-apcu      v1.6.0  v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0  v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.6.0  v1.6.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.12 v3.1.6  Symfony SwiftmailerBundle
symfony/symfony            v2.8.13 v3.3.13 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

## Steps to reproduce
Run composer install
## Expected results
Normal install process
## Actual results
Circular reference detected for service "knp_menu.matcher", path: "knp_menu.matcher -> sonata.admin.menu.matcher.voter.children -> knp_menu.matcher".

##Quick workarroud
Intsall "knplabs/knp-menu-bundle": "2.1.3" even when I not use that bundle. So it seems it could be a knp-menu-bundle issue

### PR DESCRIPTION
**Pull request by greg0ire**
I am targeting this branch, because this is BC.

Closes #4639 
Fixes #4805

## Changelog
```markdown
### Fixed
- interference with other bundles

### Deprecated
- using the `ChildrenVoter` class
- using the `sonata.admin.menu.matcher.voter.children` service
```

## Subject

This is a carry of #4639

### CODE REVIEW

File: src/Menu/Matcher/Voter/ChildrenVoter.php [hunk 1]
```diff
@@ -19,6 +19,7 @@
  * Children menu voter based on children items.
  *
  * @author Samusev Andrey <andrey.simfi@ya.ru>
+ * @deprecated this class is deprecated since 3.x and will be removed in 4.0
```
Comment (stof) [inline src/Menu/Matcher/Voter/ChildrenVoter.php]: you should also add a deprecation warning in the file.

And it is not deprecated since `3.x` (which is not a version number but a version range). It is deprecated since `3.28` (which will be the next 3.x release)

Comment (greg0ire) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: @stof the 3.x is how we do things (we can't guarantee the PR will get merged in time for `3.28`, we deliberately choose to do it like this. As per the deprecation warning, @Soullivaneuh told me it wasn't required anymore.

Comment (greg0ire) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: See https://github.com/sonata-project/dev-kit/pull/312

Comment (Soullivaneuh) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: @stof Does not the latest versions of Symfony handle single `@deprecated` tag on the profiler? I am sure it was working like that at a moment. :-|

Comment (stof) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: see my comment in the discussion linked above

Comment (greg0ire) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: So this PR is good right? The point of it is to warn if someone extends the voter and tags it.

File: src/Resources/config/menu.xml [hunk 2]
```diff
@@ -20,10 +20,6 @@
         <service id="sonata.admin.menu.matcher.voter.admin" class="Sonata\AdminBundle\Menu\Matcher\Voter\AdminVoter" public="true">
             <tag name="knp_menu.voter" request="true"/>
         </service>
-        <service id="sonata.admin.menu.matcher.voter.children" class="Sonata\AdminBundle\Menu\Matcher\Voter\ChildrenVoter" public="true">
```
Comment (core23) [inline src/Resources/config/menu.xml]: This is a public service, so a BC break

Comment (greg0ire) [reply src/Resources/config/menu.xml]: Technically yes

Comment (stof) [reply src/Resources/config/menu.xml]: getting it from the container before getting the menu matcher was triggering an exception due to a circular reference previously AFAICT.

Anyway, for full BC, you could keep the service and mark it as deprecated, if you just remove the tag (so that it does not get registered itself in the matcher, which is causing the bugs being resolved by the PR)

Comment (greg0ire) [reply src/Resources/config/menu.xml]: In that case it sounds like the workflow xkcd though

image

File: src/Menu/Matcher/Voter/ChildrenVoter.php (hunk 1 above)
Comment (greg0ire) [reply src/Menu/Matcher/Voter/ChildrenVoter.php]: Now that I think of it I can see how it could possibly work. Will add a deprecation.

**Comment by greg0ire** [comment]
I added a deprecation.

File: src/Resources/config/menu.xml (hunk 2 above)
Comment (greg0ire) [reply src/Resources/config/menu.xml]: `@deprecated` is supported now since we bumped to 2.8 though, so I'm going to do that.

File: UPGRADE-3.x.md [hunk 3]
```diff
@@ -1,6 +1,11 @@
 UPGRADE 3.x
 ===========
 
+## Deprecated Sonata\AdminBundle\Menu\Matcher\Voter\ChildrenVoter
+
+It was replaced with something much more simple, and you should not rely on it
+anymore.
```
Comment (Soullivaneuh) [inline UPGRADE-3.x.md]: One line please.

File: src/Menu/Matcher/Voter/ChildrenVoter.php [hunk 4]
```diff
@@ -15,10 +15,17 @@
...
+    '"%s" is deprecated since 3.x, and will be removed in 4.0.',
+    ChildrenVoter::class
+));
+
 /**
  * Children menu voter based on children items.
  *
  * @author Samusev Andrey <andrey.simfi@ya.ru>
+ *
+ * @deprecated this class is deprecated since 3.x and will be removed in 4.0
```
Comment (Soullivaneuh) [inline src/Menu/Matcher/Voter/ChildrenVoter.php]: `@deprecated since 3.x, will be removed in 4.0.`

**Comment by Soullivaneuh** [comment]
Would you mind added a line on the `Deprecated` section of the changelog? Thanks.

File: src/Resources/config/menu.xml (hunk 2 above)
Comment (core23) [reply src/Resources/config/menu.xml]: > In that case it sounds like the workflow xkcd though

I knew that you would post this xkcd :trollface:

Comment (greg0ire) [reply src/Resources/config/menu.xml]: Sorry couldn't resist :P

**Comment by core23** [comment]
Thanks @greg0ire
