### PR TITLE
bug #7646 - rebased fix from #3082

### LINKED ISSUE #7646: For nested admins the DefaultRouteGenerator sometimes generates incorrect routes
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              4.5.0         4.5.0         The missing Symfony Admin Generator
sonata-project/block-bundle              4.9.0         4.9.0         Symfony SonataBlockBundle
sonata-project/cache                     2.2.0         2.2.0         Cache library
sonata-project/doctrine-extensions       1.16.0        1.16.0        Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.2.1         4.2.1         Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.9.1         2.9.1         Lightweight Exporter library
sonata-project/form-extensions           1.12.4        1.12.4        Symfony form extensions
sonata-project/intl-bundle               2.11.2        2.11.2        Symfony SonataIntlBundle
sonata-project/translation-bundle        3.0.0-alpha.1 3.0.0-alpha.1 SonataTranslationBundle
sonata-project/twig-extensions           1.9.1         1.9.1         Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/amqp-messenger             v5.4.0  v5.4.0  Symfony AMQP extension Messenger Bridge
symfony/asset                      v5.4.0  v6.0.1  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/browser-kit                v5.4.0  v6.0.1  Simulates the behavior of a web browser, allowing you to make requests, click on links and submit forms programmatically
symfony/cache                      v5.4.0  v6.0.1  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.0  v3.0.0  Generic abstractions related to caching
symfony/config                     v5.4.0  v6.0.0  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.4.0  v6.0.1  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.0  v6.0.1  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.4.0  v6.0.0  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v5.4.0  v6.0.1  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v3.0.0  v3.0.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.0  v6.0.1  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.4.0  v6.0.1  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.4.0  v6.0.1  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.4.0  v6.0.1  Registers environment variables from a .env file
symfony/error-handler              v5.4.0  v6.0.1  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.0  v6.0.1  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v3.0.0  v3.0.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.0  v6.0.1  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.0  v6.0.0  Provides basic utilities for the filesystem
symfony/finder                     v5.4.0  v6.0.0  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.17.6 v2.0.1  Composer plugin for Symfony
symfony/form                       v5.4.0  v6.0.1  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.0  v6.0.1  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.4.0  v6.0.1  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.0  v3.0.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.0  v6.0.1  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.0  v6.0.1  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.0  v6.0.1  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/lock                       v5.4.0  v6.0.1  Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mailer                     v5.4.0  v6.0.1  Helps sending emails
symfony/maker-bundle               v1.36.4 v1.36.4 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/messenger                  v5.4.0  v6.0.1  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       v5.4.0  v6.0.1  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.0  v6.0.1  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.1  v3.7.1  Symfony MonologBundle
symfony/options-resolver           v5.4.0  v6.0.0  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.0  v6.0.1  Provides password hashing utilities
symfony/phpunit-bridge             v5.4.0  v6.0.0  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-intl-grapheme     v1.23.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.23.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.23.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-uuid              v1.23.0 v1.23.0 Symfony polyfill for uuid functions
symfony/process                    v5.4.0  v6.0.0  Executes commands in sub-processes
symfony/property-access            v5.4.0  v6.0.0  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.4.0  v6.0.0  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.4.0  v6.0.1  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.1.2  v2.1.2  PSR HTTP message bridge
symfony/redis-messenger            v5.4.0  v5.4.0  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.4.0  v6.0.1  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.4.0  v6.0.0  Enables decoupling PHP applications from global state
symfony/security-acl               v3.2.0  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.0  v6.0.1  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.4.0  v6.0.1  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.0  v6.0.1  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.0  v5.4.0  Symfony Security Component - Guard
symfony/security-http              v5.4.0  v6.0.1  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.4.0  v6.0.1  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.4.1  v3.0.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.0  v6.0.0  Provides a way to profile code
symfony/string                     v5.4.0  v6.0.1  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/templating                 v5.4.0  v6.0.1  Provides all the tools needed to build any kind of template system
symfony/translation                v5.4.0  v6.0.1  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.0  v3.0.0  Generic abstractions related to translation
symfony/twig-bridge                v5.4.0  v6.0.1  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.0  v6.0.1  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.4.0  v6.0.1  Provides tools to validate values
symfony/var-dumper                 v5.4.0  v6.0.1  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.0  v6.0.0  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.4.0  v6.0.1  Manages links between resources
symfony/web-profiler-bundle        v5.4.0  v6.0.1  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.13.2 v1.13.2 Integration with your Symfony app & Webpack Encore!
symfony/workflow                   v5.4.0  v6.0.1  Provides tools for managing a workflow or finite state machine
symfony/yaml                       v5.4.0  v6.0.1  Loads and dumps YAML files

```

</p>
</details>

#### PHP version

```
$ php -v
# PHP 8.0.12 (cli) (built: Oct 21 2021 16:00:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.12, Copyright (c), by Zend Technologies
```

## Subject
During the last few years we have on 'random' occurrences issues with child route generation:

```twig
<a class="btn btn-sm btn-default view_link" href="{{ admin.generateObjectUrl('admin.chapter.list', object) }}">
    <i class="fas fa-level-up-alt"></i> Chapters
</a>
```
Most of the time this works well and generates routes like `/admin/books/book-1/chapters/list`. However on rare occassions it decides to break and generate URLs like `/admin/chapters/list?ID=book-1`. 

There are several previous issues created before for similar issues:

 * https://github.com/sonata-project/SonataAdminBundle/issues/2505
 * https://github.com/sonata-project/SonataAdminBundle/issues/4093

The unpredictable behaviour might be triggered by the caching of routes, perhaps the cache is not always built correctly?

Changing 

https://github.com/sonata-project/SonataAdminBundle/blob/97c4eb4559b0634cd4e5a53a01b89f9ffcc079d7/src/Route/DefaultRouteGenerator.php#L134-L154

To:

```php
/**
     * @param AdminInterface<object> $admin
     */
    private function getCode(AdminInterface $admin, string $name): string
    {
        $this->loadCache($admin);

        $codePrefix = $admin->getBaseCodeRoute();

        // someone provide a code, so it is a child
        if (strpos($name, '.') > 0) {
            return sprintf('%s|%s', $codePrefix, $name);
        }

        // someone provide the fullname
        if (!$admin->isChild() && \array_key_exists($name, $this->caches)) {
            return $name;
        }

        return sprintf('%s.%s', $codePrefix, $name);
    }
```

Seems to fix the issue. This the same 'fix' as suggested in https://github.com/sonata-project/SonataAdminBundle/pull/3082/files . Also the test added there fails without the change in `DefaultRouteGenerator`. I don't know the correctness / performance implications of this though.

An alternative workaround to force the correct URL always:

```twig
<a class="btn btn-sm btn-default view_link" href="{{ admin.generateObjectUrl(admin.getBaseCodeRoute() ~ '|admin.chapter.list', object) }}">
    <i class="fas fa-level-up-alt"></i> Chapters
</a>
```

Or to not use `generateUrl / generateObjectUrl` at all and fall back on `path` with its many disadvantages.

## Steps to reproduce

I have not been able to reproduce it in a small repository. It seems to be related in the order the routing cache is build. Multiple nested Child admins definitely increase the chance for this bug to occur.

### PR DESCRIPTION
**Pull request by Devristo**
## Subject
Probably this needs to be applied to 3.x as well?

Closes #7646 

See #3082
## Changelog

```markdown
### Fixed
- DefaultRouteGenerator Routes generation for nested admins
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
We will need to suppress that psalm until it is solved on their side @VincentLanglet

**Comment by VincentLanglet** [comment]
Done in https://github.com/sonata-project/SonataAdminBundle/pull/7649 @jordisala1991

File: tests/Route/DefaultRouteGeneratorTest.php [hunk 1]
```diff
@@ -164,6 +164,10 @@ public function testGenerateUrlChild(string $type, string $expected, string $nam
         $collection->add('foo');
         $collection->addCollection($childCollection);
 
+        $nochildCollection = new RouteCollection('base.Code.Child', 'admin_child', '/foo/', 'BundleName:ControllerName');
+        $nochildCollection->add('bar');
+        $collection->addCollection($nochildCollection);
```
Comment (VincentLanglet) [inline tests/Route/DefaultRouteGeneratorTest.php:169]: This variable is used nowhere so this code is useless and not testing the changes you made

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: tests/Route/DefaultRouteGeneratorTest.php (hunk 1 above)
Comment (Devristo) [reply tests/Route/DefaultRouteGeneratorTest.php:169]: `$collection` is used in line 184. And without the changes in `DefaultRouteGenerator` the test fails after adding these 3 lines. If you want I can split the PR in 2 commits: first adding the test (which will fail) and the commit which will fix the test?

To be honest I dont understand the test either way, I just copied it from the previous PR.

Comment (VincentLanglet) [reply tests/Route/DefaultRouteGeneratorTest.php:169]: Indeed the test failing, but in a kinda wrong way IMHO.

Can you update the switch in the test to add 
```
case 'admin_child_bar':
    return sprintf('/bar%s', $params);
```
This way you get a Failure instead of an error without your change.

Comment (Devristo) [reply tests/Route/DefaultRouteGeneratorTest.php:169]: I have added this to the test. Also I rebased so the Psalm fix is in there.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thank you @Devristo

**Comment by core23** [comment]
I'm not completely sure why, but some of my integration tests are failing with this change :/

**Comment by VincentLanglet** [comment]
> I'm not completely sure why, but some of my integration tests are failing with this change :/

Can you give more explanation about which scenario is failing ?
Maybe with a PR to reproduce the test failure on this project ?

The 
```
if (strpos($name, '.') > 0) {
     return sprintf('%s|%s', $codePrefix, $name);
}
```
check is done before the cache check now.

Do you use route_name with `.` ?

**Comment by core23** [comment]
Just ignore my comment. It was just a strange caching bug on my CI server.

**Comment by ZZromanZZ** [comment]
Hi, coult it be backported to 3.x ?

**Comment by VincentLanglet** [comment]
> Hi, coult it be backported to 3.x ?

Feel free to do the PR

**Comment by ZZromanZZ** [comment]
Done, https://github.com/sonata-project/SonataAdminBundle/pull/7665
