### PR TITLE
Set persistFilters option to true while setting the filter persister

### LINKED ISSUE #5069: Filters from list are reset after a "Save and close" action
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.34.1 3.34.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  3.5.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/intl-bundle               2.4.0  2.4.0  Symfony SonataIntlBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.0.8  v4.0.8  Symfony Asset Component
symfony/browser-kit          v4.0.8  v4.0.8  Symfony BrowserKit Component
symfony/cache                v4.0.8  v4.0.8  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.8  v3.4.8  Symfony ClassLoader Component
symfony/config               v3.4.8  v4.0.8  Symfony Config Component
symfony/console              v3.4.8  v4.0.8  Symfony Console Component
symfony/css-selector         v4.0.8  v4.0.8  Symfony CssSelector Component
symfony/debug                v4.0.8  v4.0.8  Symfony Debug Component
symfony/debug-bundle         v4.0.8  v4.0.8  Symfony DebugBundle
symfony/dependency-injection v3.4.8  v4.0.8  Symfony DependencyInjection Component
symfony/doctrine-bridge      v3.4.8  v4.0.8  Symfony Doctrine Bridge
symfony/dom-crawler          v4.0.8  v4.0.8  Symfony DomCrawler Component
symfony/dotenv               v4.0.8  v4.0.8  Registers environment variables from a .env file
symfony/event-dispatcher     v3.4.8  v4.0.8  Symfony EventDispatcher Component
symfony/expression-language  v3.4.8  v4.0.8  Symfony ExpressionLanguage Component
symfony/filesystem           v3.4.8  v4.0.8  Symfony Filesystem Component
symfony/finder               v3.4.8  v4.0.8  Symfony Finder Component
symfony/flex                 v1.0.78 v1.0.78
symfony/form                 v3.4.8  v4.0.8  Symfony Form Component
symfony/framework-bundle     v3.4.8  v4.0.8  Symfony FrameworkBundle
symfony/http-foundation      v3.4.8  v4.0.8  Symfony HttpFoundation Component
symfony/http-kernel          v3.4.8  v4.0.8  Symfony HttpKernel Component
symfony/inflector            v4.0.8  v4.0.8  Symfony Inflector Component
symfony/intl                 v4.0.8  v4.0.8  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge       v4.0.8  v4.0.8  Symfony Monolog Bridge
symfony/monolog-bundle       v3.2.0  v3.2.0  Symfony MonologBundle
symfony/options-resolver     v3.4.8  v4.0.8  Symfony OptionsResolver Component
symfony/phpunit-bridge       v3.4.8  v4.0.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu    v1.7.0  v1.7.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.7.0  v1.7.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72       v1.7.0  v1.7.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util        v1.7.0  v1.7.0  Symfony utilities for portability of PHP codes
symfony/process              v3.4.8  v4.0.8  Symfony Process Component
symfony/property-access      v3.4.8  v4.0.8  Symfony PropertyAccess Component
symfony/property-info        v3.4.8  v4.0.8  Symfony Property Info Component
symfony/routing              v3.4.8  v4.0.8  Symfony Routing Component
symfony/security             v3.4.8  v4.0.8  Symfony Security Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v3.4.8  v4.0.8  Symfony SecurityBundle
symfony/serializer           v3.4.8  v4.0.8  Symfony Serializer Component
symfony/stopwatch            v4.0.8  v4.0.8  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.2  v3.2.2  Symfony SwiftmailerBundle
symfony/templating           v4.0.8  v4.0.8  Symfony Templating Component
symfony/translation          v3.4.8  v4.0.8  Symfony Translation Component
symfony/twig-bridge          v3.4.8  v4.0.8  Symfony Twig Bridge
symfony/twig-bundle          v3.4.8  v4.0.8  Symfony TwigBundle
symfony/validator            v3.4.8  v4.0.8  Symfony Validator Component
symfony/var-dumper           v4.0.8  v4.0.8  Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle  v4.0.8  v4.0.8  Symfony WebProfilerBundle
symfony/yaml                 v3.4.8  v4.0.8  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.2.3 (cli) (built: Mar 22 2018 21:24:10) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.0alpha1, Copyright (c) 2002-2018, by Derick Rethans
```

## Subject

The filter are reset when you save and close to go back to the list.

## Steps to reproduce

- Go to a list
- Set some filters
- Edit an entity
- Click on "Save and close"

## Expected results

Going back to the list with the current filters.

## Actual results

The filters are gone.

Note: They are still present on the URL but does not seem to have the same format.

No issue on 3.33.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
I am targeting this branch, because it's a regression fix.

Closes #5069 

## Changelog

```markdown
### Fixed
- Not working persist_filter option for legacy admin property.
```

## Subject

Even if the property is deprecated, it's still used to check if the filters have to be persisted or not.

As the `setFilterPersister` method is called only if the `persist_filter` configuration key is set to `true`, I set the `persistFilters` deprecated attribute here to avoid resolvable deprecation error with the setter.

### CODE REVIEW

File: src/Admin/AbstractAdmin.php [hunk 1]
```diff
@@ -1430,6 +1430,8 @@ public function setPersistFilters($persist)
     public function setFilterPersister(FilterPersisterInterface $filterPersister = null)
     {
         $this->filterPersister = $filterPersister;
+        // NEXT_MAJOR remove the deprecated property will be removed. Needed for persisted filter condition.
+        $this->persistFilters = true;
```
Comment (jordisala1991) [inline src/Admin/AbstractAdmin.php]: Are you sure this property is deprecated?

**Comment by Soullivaneuh** [comment]
Approved by two contributors, let's merge.
