### PR TITLE
fix nested admin (one-to-one-to-many relation) that opens inline (fixes #6777)

### LINKED ISSUE #6777: Relative admin form is broken after 3.84.0
#### PHP version

```
PHP 7.4.9 (cli) (built: Aug  7 2020 14:29:10) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.9, Copyright (c), by Zend Technologies
```

## Subject

I'm sure that it was in `3.84.0` and specifically https://github.com/sonata-project/SonataAdminBundle/commit/cf1ec4d501e13645fc1cb12e97b1d8409d052948

## Minimal repository with the bug
I'll provide one if the code that I'll give, will not be understandable

## Steps to reproduce
0. You want to edit admin from related admin
1. Create one, general `UserAdmin`
2. Then create related `UserInfoAdmin` (the relations between tables is `one-to-one`)
2.1. in `configureFormFields` of `UserAdmin` write `$form->add('userInfo',AdminType::class,)`
2.2 The the `user_info` table has relation to `one-to-many` table called `user_info_color` (one info has many colors)
3. In `UserInfoAdmin` in `configureFormFields` set
```php
            ->add(
                'colors',
                CollectionType::class,
                [],
                [
                    'edit' => 'inline',
                    'inline' => 'table',
                ]
            )
```
4. Open `UserAdmin` in web and try to set colors with
image
5. See
```
Error:
Call to a member function getValue() on null

  at vendor/sonata-project/admin-bundle/src/Admin/AdminHelper.php:228
  at Sonata\AdminBundle\Admin\AdminHelper->appendFormFieldElement(object(UserAdmin), object(User), 's6002dde957cdd_fakePublicInfo_tradeVolumes')
     (vendor/sonata-project/admin-bundle/src/Action/AppendFormFieldElementAction.php:77)
  at Sonata\AdminBundle\Action\AppendFormFieldElementAction->__invoke(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (Web/index.php:27)  
```
where the error happens
```php
            // retrieve the posted data
            $data = $admin->getRequest()->get($formBuilder->getName());
```

## Expected results
I get new line in my admin panel  

## Actual results
```
Error:
Call to a member function getValue() on null

  at vendor/sonata-project/admin-bundle/src/Admin/AdminHelper.php:228
  at Sonata\AdminBundle\Admin\AdminHelper->appendFormFieldElement(object(UserAdmin), object(User), 's6002dde957cdd_fakePublicInfo_tradeVolumes')
     (vendor/sonata-project/admin-bundle/src/Action/AppendFormFieldElementAction.php:77)
  at Sonata\AdminBundle\Action\AppendFormFieldElementAction->__invoke(object(Request))
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (Web/index.php:27)  
```
where the error happens
```php
            // retrieve the posted data
            $data = $admin->getRequest()->get($formBuilder->getName());
```

-------------------

the why it happens is because of this commit https://github.com/sonata-project/SonataAdminBundle/commit/cf1ec4d501e13645fc1cb12e97b1d8409d052948 in file `src/Admin/AdminHelper.php` method `getChildFormBuilder`. If I revert changes of this method, it works perfectly.

Should I make revert commit?

### PR DESCRIPTION
**Pull request by vladyslavstartsev**
## Subject
Fix form rendering of nested Admin properties.

I am targeting this branch, because everything is backwards compatible.

Closes #6777.

## Changelog

```markdown
### Fixed
How `AdminHelper::appendFormFieldElement` renders nested forms.
```

### CODE REVIEW

**Comment by vladyslavstartsev** [comment]
tests will fail, because I have no idea how do you mock methods that does not exist on interface (talking about `hasFormFieldDescription`). yes, I've google it

**Comment by VincentLanglet** [comment]
> tests will fail, because I have no idea how do you mock methods that does not exist on interface (talking about `hasFormFieldDescription`). yes, I've google it

```
$this->getMockBuilder(Interface::class)
            ->addMethods(['method'])
            ->getMockForAbstractClass();
```
?

File: src/Admin/AdminHelper.php [hunk 1]
```diff
@@ -211,7 +211,7 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
                 //since doctrine 2.4
                 $modelClassName = $collection->getTypeClass()->getName();
             } elseif ($collection instanceof Collection) {
-                $modelClassName = $this->getEntityClassName($admin, explode('.', preg_replace('#\[\d*?\]#', '', $path)));
+                $modelClassName = $this->getModelClassName($admin, explode('.', preg_replace('#\[\d*?\]#', '', $path)));
```
Comment (VincentLanglet) [inline src/Admin/AdminHelper.php:214]: Isn't this a BC-break if someone override `getEntityClassName` ?

File: src/Admin/AdminHelper.php [hunk 2]
```diff
@@ -202,7 +202,7 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
 
         //Child form not found (probably nested one)
         //if childFormBuilder was not found resulted in fatal error getName() method call on non object
-        if (!$childFormBuilder) {
+        if (!$childFormBuilder || !$admin->hasFormFieldDescription($childFormBuilder->getName())) {
```
Comment (VincentLanglet) [inline src/Admin/AdminHelper.php:205]: Can you update the comment before to add better explanation ?

File: src/Admin/AdminHelper.php (hunk 1 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php:214]: I've reverted this one, since it's not relevant to this PR

File: src/Admin/AdminHelper.php (hunk 2 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php:205]: :ok_hand: 

BTW PhpStorm suggested to me to flip `if-else`.
And if will look prettier to me

```php
if ($childFormBuilder && $admin->hasFormFieldDescription($childFormBuilder->getName())) {
``` 

But I think PR should atomic, maybe in next PR

Comment (VincentLanglet) [reply src/Admin/AdminHelper.php:207]: It's not a bad idea to flip indead !

Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php]: ok, I've flipped it

**Review by VincentLanglet — COMMENTED** [review]
Can you add a test where hasFormFieldDescription return false ?

**Comment by vladyslavstartsev** [comment]
There isnone case that I dont know how to handle.
There are nested if
```php
            if ($collection instanceof DoctrinePersistentCollection || $collection instanceof PersistentCollection) {
                //since doctrine 2.4
                $modelClassName = $collection->getTypeClass()->getName();
            } elseif ($collection instanceof Collection) {
                $modelClassName = $this->getEntityClassName($admin, explode('.', preg_replace('#\[\d*?\]#', '', $path)));
            } else {
                throw new \Exception('unknown collection class');
            }
```

I can check for exception. But how should I handle case with `PersistentCollection`?
The short answer is - no, just don't check

**Comment by VincentLanglet** [comment]
I find the code 
```
if ($collection instanceof DoctrinePersistentCollection || $collection instanceof PersistentCollection) {
                //since doctrine 2.4
                $modelClassName = $collection->getTypeClass()->getName();
            } elseif ($collection instanceof Collection) {
                $modelClassName = $this->getEntityClassName($admin, explode('.', preg_replace('#\[\d*?\]#', '', $path)));
            } else {
                throw new \Exception('unknown collection class');
            }
```
weird, since a PersistentCollection is  a Collection, we should be able to remove the if part.

the collection is 
```
$collection = $this->propertyAccessor->getValue($subject, $path);
```
So you could mock the propertyAccessor.

**Comment by VincentLanglet** [comment]
Rebasing 3.x should fix the build

**Review by VincentLanglet — APPROVED** [review]

File: src/Admin/AdminHelper.php [hunk 3]
```diff
@@ -252,6 +230,26 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
             $newInstance = ObjectManipulator::addInstance($form->getData(), $associationAdmin->getNewInstance(), $fieldDescription);
 
             $associationAdmin->setSubject($newInstance);
+        } else {
+            //Else branch is executed when child form not found (probably nested one)
+            //if childFormBuilder was not found resulted in fatal error getName() method call on non object
+            //OR if childFormBuilder was found, but admin object does not have formFieldDescription with
+            //same name as childFormBuilder
```
Comment (phansys) [inline src/Admin/AdminHelper.php:237]:
```suggestion
            // The `else` branch is executed when child form was not found (probably nested one).
            // If `$childFormBuilder` was not found resulted in fatal error `getName()` method call on non object
            // or if `$childFormBuilder` was found, but the admin object does not have a formFieldDescription with
            // same name as `$childFormBuilder`.
```

File: src/Admin/AdminHelper.php [hunk 4]
```diff
@@ -252,6 +230,26 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
...
+
+            $path = $this->getElementAccessPath($elementId, $subject);
+
+            $collection = $this->propertyAccessor->getValue($subject, $path);
+
+            if ($collection instanceof Collection) {
+                $modelClassName = $this->getEntityClassName($admin, explode('.', preg_replace('#\[\d*?\]#', '', $path)));
+            } else {
+                throw new \Exception('unknown collection class');
```
Comment (phansys) [inline src/Admin/AdminHelper.php:246]: IMO, we could flip this condition in order to avoid the `else` block.
Regarding the exception, I think we must use a narrower type (like `\TypeError` or similar) and provide a better message explaining what is the expected and the found type.
```suggestion
                throw new \Exception('Unknown collection class.');
```

**Review by phansys — CHANGES_REQUESTED** [review]

File: src/Admin/AdminHelper.php (hunk 3 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php]: done

File: src/Admin/AdminHelper.php (hunk 4 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php]: Did something that you asked for

**Review by VincentLanglet — DISMISSED** [review]

**Comment by vladyslavstartsev** [comment]
some why on my local machine `php-cs-fixer` was trying to fix `E_USER_DEPRECATED` in opposite way

```diff
-        ), \E_USER_DEPRECATED);
+        ), E_USER_DEPRECATED);
```

I don't really understand why

**Comment by VincentLanglet** [comment]
Can you try `composer update` ? or a rebase ?

**Comment by vladyslavstartsev** [comment]
> Can you try `composer update` ? or a rebase ?

1. deleted cache
2. rebased to latest commit on 3.x
3. composer update
still the same.

Any way, I hope that it's been final fixes of this branch, other way I'll fix it some how

File: src/Admin/AdminHelper.php [hunk 5]
```diff
@@ -252,6 +230,33 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
...
+
+            $path = $this->getElementAccessPath($elementId, $subject);
+
+            $collection = $this->propertyAccessor->getValue($subject, $path);
+
+            if (!($collection instanceof Collection)) {
+                throw new \TypeError(sprintf(
+                    'Unknown collection class. Expected instance of %s, got %s',
+                    Collection::class,
+                    \is_object($collection) ? \get_class($collection) : \gettype($collection)
```
Comment (phansys) [inline src/Admin/AdminHelper.php:247]:
```suggestion
            if (!$collection instanceof Collection) {
                throw new \TypeError(sprintf(
                    'Collection must be an instance of %s, %s given.',
                    Collection::class,
                    \is_object($collection) ? 'instance of "'.\get_class($collection).'"' : '"'.\gettype($collection).'"'
```

File: src/Admin/AdminHelper.php (hunk 4 above)
Comment (phansys) [reply src/Admin/AdminHelper.php]: Thank you!

**Comment by phansys** [comment]
Could you please use the PR template in order to expose the motivation for these changes in the "Changelog" section?
Thank you.

File: src/Admin/AdminHelper.php (hunk 5 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php]: done

**Review by VincentLanglet — APPROVED** [review]

**Review by OskarStark — APPROVED** [review]

File: src/Admin/AdminHelper.php [hunk 6]
```diff
@@ -252,6 +230,33 @@ public function appendFormFieldElement(AdminInterface $admin, $subject, $element
...
+            // The `else` branch is executed when child form was not found (probably nested one).
+            // If `$childFormBuilder` was not found resulted in fatal error `getName()` method call on non object
+            // or if `$childFormBuilder` was found, but the admin object does not have a formFieldDescription with
+            // same name as `$childFormBuilder`.
+
+            $path = $this->getElementAccessPath($elementId, $subject);
+
+            $collection = $this->propertyAccessor->getValue($subject, $path);
+
+            if (!($collection instanceof Collection)) {
```
Comment (phansys) [inline src/Admin/AdminHelper.php:243]: IMO, we should avoid superfluous parentheses.

**Review by phansys — APPROVED** [review]
If this PR is fixing something, the "Changelog" section should include the "Fixed" item.

File: src/Admin/AdminHelper.php (hunk 6 above)
Comment (vladyslavstartsev) [reply src/Admin/AdminHelper.php:243]: Can we discuss this in dev-kit? 
So it's applied globally

**Comment by OskarStark** [comment]
Thank you
