### PR TITLE
Fix return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`

### LINKED ISSUE #6046: deleteAction does not do it
### prod

```
$ composer show --latest 'sonata-project/*'
onata-project/admin-bundle              3.53.0 3.64.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.17.0 3.18.4 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.18.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.2.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.0  1.6.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.10.0 3.17.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  2.0.1  2.2.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.5.0  4.1.3  Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.2.0  2.2.0  Library to integrate Google Authenticator into a PHP project
sonata-project/translation-bundle        2.4.2  2.5.0  SonataTranslationBundle
sonata-project/user-bundle               4.4.0  4.5.2  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/acl-bundle                 v1.0.0             v2.0.0             Symfony AclBundle
symfony/asset                      v4.3.4             v5.0.7             Symfony Asset Component
symfony/browser-kit                v4.3.4             v5.0.7             Symfony BrowserKit Component
symfony/cache                      v4.3.4             v5.0.7             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.5             v2.0.1             Generic abstractions related to caching
symfony/config                     v4.3.4             v5.0.7             Symfony Config Component
symfony/console                    v4.3.4             v5.0.7             Symfony Console Component
symfony/css-selector               v4.3.4             v5.0.7             Symfony CssSelector Component
symfony/debug                      v4.3.4             v4.4.7             Symfony Debug Component
symfony/dependency-injection       v4.3.4             v5.0.7             Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.3.4             v5.0.7             Symfony Doctrine Bridge
symfony/dom-crawler                v4.3.4             v5.0.7             Symfony DomCrawler Component
symfony/dotenv                     v4.3.4             v5.0.7             Registers environment variables from a .env file
symfony/event-dispatcher           v4.3.4             v5.0.7             Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.5             v2.0.1             Generic abstractions related to dispatching event
symfony/expression-language        v4.3.4             v5.0.7             Symfony ExpressionLanguage Component
symfony/filesystem                 v4.3.4             v5.0.7             Symfony Filesystem Component
symfony/finder                     v4.3.4             v5.0.7             Symfony Finder Component
symfony/flex                       v1.4.5             v1.6.2             Composer plugin for Symfony
symfony/form                       v4.3.4             v5.0.7             Symfony Form Component
symfony/framework-bundle           v4.3.4             v5.0.7             Symfony FrameworkBundle
symfony/http-client                v4.3.4             v5.0.7             Symfony HttpClient component
symfony/http-client-contracts      v1.1.6             v2.0.1             Generic abstractions related to HTTP clients
symfony/http-foundation            v4.3.4             v5.0.7             Symfony HttpFoundation Component
symfony/http-kernel                v4.3.4             v5.0.7             Symfony HttpKernel Component
symfony/inflector                  v4.3.4             v5.0.7             Symfony Inflector Component
symfony/intl                       v4.3.4             v5.0.7             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lock                       v4.3.4             v5.0.7             Symfony Lock Component
symfony/lts                        dev-master c1affae dev-master c1affae Enforces Long Term Supported versions of Symfony components
Package symfony/lts is abandoned, you should avoid using it. Use symfony/flex instead.
symfony/maker-bundle               v1.13.0            v1.15.0            Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can...
symfony/messenger                  v4.3.4             v5.0.7             Symfony Messenger Component
symfony/mime                       v4.3.4             v5.0.7             A library to manipulate MIME messages
symfony/monolog-bridge             v4.3.4             v5.0.7             Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0             v3.5.0             Symfony MonologBundle
symfony/options-resolver           v4.3.4             v5.0.7             Symfony OptionsResolver Component
symfony/orm-pack                   v1.0.6             v1.0.8             A pack for the Doctrine ORM
symfony/phpunit-bridge             v4.3.4             v5.0.7             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu          v1.12.0            v1.15.0            Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.12.0            v1.15.0            Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.12.0            v1.15.0            Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.12.0            v1.15.0            Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.12.0            v1.15.0            Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.3.4             v5.0.7             Symfony Process Component
symfony/profiler-pack              v1.0.4             v1.0.4             A pack for the Symfony web profiler
symfony/property-access            v4.3.4             v5.0.7             Symfony PropertyAccess Component
symfony/property-info              v4.3.4             v5.0.7             Symfony Property Info Component
symfony/proxy-manager-bridge       v4.4.1             v5.0.7             Symfony ProxyManager Bridge
symfony/routing                    v4.3.4             v5.0.7             Symfony Routing Component
symfony/security-acl               v3.0.2             v3.0.4             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.3.4             v5.0.7             Symfony SecurityBundle
symfony/security-core              v4.3.4             v5.0.7             Symfony Security Component - Core Library
symfony/security-csrf              v4.3.4             v5.0.7             Symfony Security Component - CSRF Library
symfony/security-guard             v4.3.4             v5.0.7             Symfony Security Component - Guard
symfony/security-http              v4.3.4             v5.0.7             Symfony Security Component - HTTP Integration
symfony/serializer                 v4.3.4             v5.0.7             Symfony Serializer Component
symfony/serializer-pack            v1.0.2             v1.0.3             A pack for the Symfony serializer
symfony/service-contracts          v1.1.6             v2.0.1             Generic abstractions related to writing services
symfony/stopwatch                  v4.3.4             v5.0.7             Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.2.8             v3.4.0             Symfony SwiftmailerBundle
symfony/templating                 v4.3.4             v5.0.7             Symfony Templating Component
symfony/test-pack                  v1.0.6             v1.0.6             A pack for functional and end-to-end testing within a Symfony app
symfony/translation                v4.3.4             v5.0.7             Symfony Translation Component
symfony/translation-contracts      v1.1.6             v2.0.1             Generic abstractions related to translation
symfony/twig-bridge                v4.3.4             v5.0.7             Symfony Twig Bridge
symfony/twig-bundle                v4.3.4             v5.0.7             Symfony TwigBundle
symfony/validator                  v4.3.4             v5.0.7             Symfony Validator Component
symfony/var-dumper                 v4.3.4             v5.0.7             Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.3.4             v5.0.7             A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.3.4             v5.0.7             Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.4             v5.0.7             Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.4             v4.4.7             Symfony WebServerBundle
symfony/webpack-encore-bundle      v1.6.2             v1.7.3             Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.3.4             v5.0.7             Symfony Yaml Component

```

#### PHP version

```
$ php -v
PHP 7.3.16 (cli) (built: Mar 17 2020 10:18:38) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.9, Copyright (c) 2002-2019, by ionCube Ltd.

```

## Subject

clicking on delete action in list action show confirmation page. i click Yes, delete - and again confirmation page. I look inside and noticed that:
in ./vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php method:
always return $request->getMethod() 
```
protected function getRestMethod()
    {
        $request = $this->getRequest();
        if (Request::getHttpMethodParameterOverride() || !$request->request->has('_method')) {
            return $request->getMethod();
        }

        return $request->request->get('_method');
    }

```
I think you need to make 
```
...
if ( !Request::getHttpMethodParameterOverride()  ...
```

### PR DESCRIPTION
**Pull request by phansys**
## Subject
Fix return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`.

I am targeting this branch, because this change respects BC.

Closes #6046.
Closes #6098.

## Changelog

```markdown
### Fixed
- Fixed return value from `CRUDController::getRestMethod()` respecting `Request::getHttpMethodParameterOverride()`.

### Deprecated
- Deprecated `Sonata\AdminBundle\Controller\CRUDController::getRestMethod()` method in favor of `Symfony\Component\HttpFoundation\Request::getMethod()`.
```

### CODE REVIEW

**Comment by phansys** [comment]
@sonata-project/contributors, do you know why we need this method instead of trusting [`Request::getMethod()`](https://github.com/symfony/http-foundation/blob/1f0d6627e680591c61e9176f04a0dc887b4e6702/Request.php#L1236-L1269) directly?
```php
if (!$method && self::$httpMethodParameterOverride) {
    $method = $this->request->get('_method', $this->query->get('_method', 'POST'));
}
```
AFAIK, this is only avoiding to use the logic defined there, like falling back to `$this->query->get('_method', 'POST')` or using `X-HTTP-METHOD-OVERRIDE` header.
Since it's not clear to me, is not easy to create valid test cases.
Any clue is welcome.

**Comment by phansys** [comment]
Reading the [history](https://github.com/sonata-project/SonataAdminBundle/pull/1184#discussion-diff-3263904), maybe this method is not required anymore.

**Review by wbloszyk — APPROVED** [review]

File: tests/Controller/CRUDControllerTest.php [hunk 1]
```diff
@@ -1095,11 +1113,14 @@ public function testDeleteActionAjaxSuccess2(): void
 
         $this->request->headers->set('X-Requested-With', 'XMLHttpRequest');
 
+        Request::enableHttpMethodParameterOverride();
+
```
Comment (wbloszyk) [inline tests/Controller/CRUDControllerTest.php:1117]:
```suggestion
```
This should not be enabled in tests.

**Review by wbloszyk — CHANGES_REQUESTED** [review]
Request::getMethod() will return $_SERVER['REQUEST_METHOD'] with some hack for `POST` where are additional checking and return if exist in some order:
1. $this->headers->get('X-HTTP-METHOD-OVERRIDE');
1. $httpMethodParameterOverride === true
    - $_POST['_method']
    - $_GET['_method']
    - 'POST'

Technicly exist two solution:
1. 
```php
Request::enableHttpMethodParameterOverride()
if (Request::METHOD_DELETE === $request->getMethod()) {
```
or
```php
if (
    Request::METHOD_POST === $request->getMethod() &&
    'DELETE' === $request->request->get('_method')
) {
```
For better understand it look at `Symfony\Component\HttpFoundation\Request::getMethod()`

File: tests/Controller/CRUDControllerTest.php (hunk 1 above)
Comment (phansys) [reply tests/Controller/CRUDControllerTest.php:1117]: What do you propose to cover the expected behavior then?
Additionally, please note that the original value for `Request::$httpMethodParameterOverride` is being restored after each individual test:
https://github.com/sonata-project/SonataAdminBundle/blob/39c4e2483b956e537b23d42b5491bd036f94c7dc/tests/Controller/CRUDControllerTest.php#L376-L386

Comment (wbloszyk) [reply tests/Controller/CRUDControllerTest.php:1117]: This should be done in Action, otherwise test will work and action do not:
https://github.com/sonata-project/SonataAdminBundle/blob/39c4e2483b956e537b23d42b5491bd036f94c7dc/src/Controller/CRUDController.php#L220

Comment (phansys) [reply tests/Controller/CRUDControllerTest.php:1117]: I'm sorry @wbloszyk, I don't understand your suggestion or why you say it won't work.
AFAIK, the choice about enabling or disabling the http method overriding is a global responsibility in the context of the whole application execution. By instance, the configuration node [`framework.http_method_override`](
https://symfony.com/doc/current/reference/configuration/framework.html#http-method-override) establishes this setting globally.

Comment (wbloszyk) [reply tests/Controller/CRUDControllerTest.php:1117]: https://symfony.com/doc/2.6/book/forms.html#book-forms-changing-action-and-method

> NOTE
If the form’s method is not GET or POST, but PUT, PATCH or DELETE, Symfony will insert a hidden field with the name _method that stores this method. The form will be submitted in a normal POST request, but Symfony’s router is capable of detecting the _method parameter and will interpret it as a PUT, PATCH or DELETE request. Read the cookbook chapter “How to Use HTTP Methods beyond GET and POST in Routes” for more information.

When $disableHttpMethodParameterOverride === false then 
```php
if (Request::METHOD_DELETE === $request->getMethod()) { } // always false
if (Request::METHOD_DELETE === $request->getRestMethod()) { } // always false, before this change - true
```

Comment (wbloszyk) [reply tests/Controller/CRUDControllerTest.php:1117]: Otherwise `Request::enableHttpMethodParameterOverride()` will be not nesessery in tests.

Comment (phansys) [reply tests/Controller/CRUDControllerTest.php:1117]: >https://symfony.com/doc/2.6/book/forms.html#book-forms-changing-action-and-method

I'm not sure I understand what are you trying to expose, but I think we should start from the fact that `Request::$httpMethodParameterOverride` is a property that enables the `Request::getMethod()` to return other values than the real HTTP method (`$_SERVER['REQUEST_METHOD']`), based on the "_method" param provided in the `$_POST` or `$_GET` superglobals or in the "X-HTTP-METHOD-OVERRIDE" header.
Regarding this doc entry, be aware that `FormConfigBuilder::setMethod()` is setting this "_method" parameter.

>Otherwise Request::enableHttpMethodParameterOverride() will be not nesessery in tests.

If you run these tests, you'll see that calling `Request::enableHttpMethodParameterOverride()` is necessary to achieve the expected result.

Maybe I'm not understanding the scenario you are talking about.
If that is the case or there is something else I'm omitting or misunderstanding about your concern, please try to share a test case or a alternative PR with what you think should be done. That way I think we could get a clearer perspective.

Comment (wbloszyk) [reply tests/Controller/CRUDControllerTest.php:1117]: > If you run these tests, you'll see that calling `Request::enableHttpMethodParameterOverride()` is necessary to achieve the expected result.

So code is working when `Request::$httpMethodParameterOverride` is enabled and don't when it is disabled. It is what I mean. I think current code is working correct and we should consider #6046 one more time.

**Comment by VincentLanglet** [comment]
@phansys @wbloszyk What's the status of this ?

**Comment by phansys** [comment]
> @phansys @wbloszyk What's the status of this ?

IIUC the issue, this PR is RTM.
@wbloszyk, if you think other approach must be followed, please try to provide a new PR in order to check what you mean, since I'm not understanding the point in your comments.

**Review by VincentLanglet — APPROVED** [review]

File: src/Controller/CRUDController.php [hunk 2]
```diff
@@ -217,7 +217,7 @@ public function deleteAction($id) // NEXT_MAJOR: Remove the unused $id parameter
             return $preResponse;
         }
 
-        if (Request::METHOD_DELETE === $this->getRestMethod()) {
+        if (Request::METHOD_DELETE === $request->getMethod()) {
```
Comment (wbloszyk) [inline src/Controller/CRUDController.php:220]: **Case 1:**
```yaml
framework:
    http_method_override: false
```
All forms will be generated as `GET|POST` (`Request::getMethod()`). If you want use `DELETE` then you should take it from `_method` parameter.

**Case 2:**
```yaml
framework:
    http_method_override: true
```
Form attribute `method` will be override. If you want use `DELETE` then you can take it from `Request::getMethod()`.

In this case, when people will have this parameter disabled then this if will be treated as allways false.

**Review by wbloszyk — CHANGES_REQUESTED** [review]

File: src/Controller/CRUDController.php (hunk 2 above)
Comment (phansys) [reply src/Controller/CRUDController.php:220]: AFAIK, the "_method" request parameter must only receive a special treatment when `Request::$httpMethodParameterOverride` is set to `true`, otherwise it is a common parameter like any other:
* https://symfony.com/doc/current/routing.html#matching-http-methods
>HTML forms only support GET and POST methods. If you’re calling a route with a different method from an HTML form, add a hidden field called _method with the method to use (e.g. <input type="hidden" name="_method" value="PUT"/>). If you create your forms with Symfony Forms this is done automatically for you.
* https://symfony.com/doc/current/forms.html#changing-the-action-and-http-method
>If the form’s method is not GET or POST, but PUT, PATCH or DELETE, Symfony will insert a hidden field with the name _method that stores this method. The form will be submitted in a normal POST request, but Symfony’s routing is capable of detecting the _method parameter and will interpret it as a PUT, PATCH or DELETE request. See the http_method_override option.
* https://symfony.com/doc/current/reference/configuration/framework.html#configuration-framework-http-method-override
>http_method_override¶
>type: boolean default: true
>
>This determines whether the _method request parameter is used as the intended HTTP method on POST requests. If enabled, the Request::enableHttpMethodParameterOverride method gets called automatically. It becomes the service container parameter named kernel.http_method_override.

Comment (wbloszyk) [reply src/Controller/CRUDController.php:220]: Correct, my bad here.

**Review by wbloszyk — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks @phansys
