### PR TITLE
Get data from the form in create/update actions.

### LINKED ISSUE #4494: Get data from the form in create/update actions of CrudController
## Subject

On the project I'm working on immutable entities are used. DataMapper solves the problem with creating new Entity instance based on Form data. But $object is never got from the form in CRUDController::createAction() and CRUDController::editAction(). If new object is not created then nothing will change as the same instance will be returned. But this patch can be easily adopted and provide others working with DDD entities with a solution.

I provided sample DataMapper that creates new entity from Form data.

## DataMapper

```php
class SampleEntityDataMapper implements DataMapperInterface
{
    /**
     * @param SampleEntity $data
     * @param FormInterface[]|\Traversable $forms
     */
    public function mapDataToForms($data, $forms)
    {
        if (null !== $data) {
            $forms = iterator_to_array($forms);
            $forms['name']->setData($data->getName());
            $forms['description']->setData($data->getDescription());
        }
    }

    /**
     * @param FormInterface[]|\Traversable $forms
     * @param SampleEntity $data
     */
    public function mapFormsToData($forms, &$data)
    {
        $forms = iterator_to_array($forms);

        if (null === $data->getId()) {
            $name = $forms['name']->getData();
            $description = $forms['description']->getData();

            // New entity is created
            $data = new SampleEntity(
                $name,
                $description
            );
        } else {
            $data->update(
                $forms['description']->getData()
            );
        }
    }
```

## CRUDController:createAction()

See comments here. Some code was removed to make my example more readable.

```php
    /**
     * Create action.
     *
     * @return Response
     *
     * @throws AccessDeniedException If access is not granted
     */
    public function createAction()
    {
        // some code is removed

        $object = $this->admin->getNewInstance();

        $this->admin->setSubject($object);

        /** @var $form \Symfony\Component\Form\Form */
        $form = $this->admin->getForm();
        $form->setData($object);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            //TODO: remove this check for 4.0
            if (method_exists($this->admin, 'preValidate')) {
                $this->admin->preValidate($object);
            }
            $isFormValid = $form->isValid();

            // persist if the form was valid and if in preview mode the preview was approved
            if ($isFormValid && (!$this->isInPreviewMode() || $this->isPreviewApproved())) {
                $this->admin->checkAccess('create', $object);

                try {
                    // Old object is passed to be created. One that is newly created in the form is never got back
                    // For example:
                    $object = $form->getData();
                    $object = $this->admin->create($object);

                    // some code removed
                } catch (ModelManagerException $e) {
                   // some code removed
                }
            }
         // some code removed
    }
```

### PR DESCRIPTION
**Pull request by ozanichkovsky**
I am targeting this branch, because 3.x branch is used on a project I'm working on. On the other hand it should be applicable to master according to CRUDController code.

Closes #4494

## Changelog

```markdown

### Changed
- compatibility with immutable entities was improved
```

## Subject

On the project I'm working on immutable entities are used. DataMapper solves the problem with creating new Entity instance based on Form data. But $object is never got from the form in CRUDController::createAction() and CRUDController::editAction(). If new object is not created then nothing will change as the same instance will be returned. But this patch can be easily adopted and provides others working with DDD entities with a solution.

### CODE REVIEW

File: Controller/CRUDController.php [hunk 1]
```diff
@@ -265,6 +265,9 @@ public function editAction($id = null)
 
             // persist if the form was valid and if in preview mode the preview was approved
             if ($isFormValid && (!$this->isInPreviewMode() || $this->isPreviewApproved())) {
+                $object = $form->getData();
+                $this->admin->setSubject($object);
```
Comment (greg0ire) [inline Controller/CRUDController.php]: Please directly `$this->admin->setSubject($form->getData())`, no need for an additional variable IMO, especially given it's named just like the one line 272, which is confusing.

File: Controller/CRUDController.php [hunk 2]
```diff
@@ -509,6 +512,8 @@ public function createAction()
...
```
Comment (greg0ire) [inline Controller/CRUDController.php]: Same here

**Comment by greg0ire** [comment]
I changed the changelog so that users understand the benefit they have when upgrading.

File: Controller/CRUDController.php (hunk 1 above)
Comment (ozanichkovsky) [inline Controller/CRUDController.php]: The reason is a newly updated `$object` should be passed into `$object = $this->admin->update($object);` It was done for purpose. If form somehow changes object and it is no longer the same instance then admin won't get that changed object in `$this->admin->update($object)`.

File: Controller/CRUDController.php (hunk 2 above)
Comment (ozanichkovsky) [inline Controller/CRUDController.php]: My answer is the same as for the previous comment.

File: Controller/CRUDController.php (hunk 1 above)
Comment (greg0ire) [inline Controller/CRUDController.php]: Hmm... this makes no sense, unless `$form` does not return the same object. Maybe it clones it? Can you find out whether the object line 268 and the object line 256 have the same `spl_object_hash` or not?

I means [as you can see, there should be no need to get the object again if you want the modifications done by the form](https://3v4l.org/Gj6SB)

Comment (greg0ire) [inline Controller/CRUDController.php]: Oh wait, [there is a clone](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Form.php#L328), so it makes sense!

Comment (ozanichkovsky) [inline Controller/CRUDController.php]: If new object is not created in a form as I provided in sample DataMapper in corresponding issue then there is no need to get data from form because instance remains the same. But otherwise `$object` in the method and data in the form are different. That's why there is a need to get data.

Comment (greg0ire) [inline Controller/CRUDController.php]: Can you rename variables though? There will be less confusion. Maybe `$existingObject` and `$modifiedObject` for `editAction`, and `$defaultObject` / `$createdObject` for `createAction`, what do you think?

Comment (ozanichkovsky) [inline Controller/CRUDController.php]: Agree

**Comment by greg0ire** [comment]
@sonata-project/contributors please review
@ozanichkovsky , thanks for this contribution! If you successfully use immutable objects throughout your application, consider contributing a cookbook article about this, we often get questions about support for it and I never know what to answer.

**Comment by ozanichkovsky** [comment]
@greg0ire I've been looking for an answer until I found I can get full control of the entity by using `DataMapper`. What is the right way to create cookbook article?

**Comment by greg0ire** [comment]
You would need to create a new `rst` file in `Resources/doc/cookbook` and then reference it in `Resources/doc/index.rst`. I wrote more details [here](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#the-documentation), please tell me if it's unclear.

**Comment by greg0ire** [comment]
Thanks @ozanichkovsky !

**Comment by greg0ire** [comment]
ping @ozanichkovsky

**Comment by ozanichkovsky** [comment]
Hi @greg0ire. Writing cookbook article is planned. I'll do it as soon as it fits my schedule.

**Comment by greg0ire** [comment]
Great news, really looking forward to it!

**Comment by ozanichkovsky** [comment]
@greg0ire I've created PR with documentation on how to use DataMapper within `configureFormFields` method.

**Comment by ozanichkovsky** [comment]
See #4566
