### PR TITLE
Use form event listener to fix preValidation

### LINKED ISSUE #4859: preValidate method does not work as expected
The method `AbstractAdmin::preValidate($object)` is not call before validation. The validation is done by Symfony at `FormEvents::POST_SUBMIT`.

Looking at the controller on `createAction`

```php
        /** @var $form \Symfony\Component\Form\Form */
        $form = $this->admin->getForm();
        $form->setData($newObject);
        $form->handleRequest($request); // <-- validation is done here by symfony

        if ($form->isSubmitted()) {
            //TODO: remove this check for 4.0
            if (method_exists($this->admin, 'preValidate')) {
                $this->admin->preValidate($newObject);   // <-- it's to late if you want to do something before validation
            }
            $isFormValid = $form->isValid();
```

I think that there is two options to fix this : 
 * Remove the method saying that this functionality is not supported anymore
 * Call the preValidate method from an event listener before Symfony validation

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.28.0 3.29.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.8.0  3.9.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.7.1  3.8.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.0  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.7  3.3.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/intl-bundle               2.4.0  2.4.0  Symfony SonataIntlBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.2 v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.1 v4.0.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0 v1.6.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0 v1.6.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0 v1.6.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0 v1.6.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.6.0 v1.6.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.1.6 Symfony SwiftmailerBundle
symfony/symfony            v3.4.1 v3.4.2 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.18.0~linux-x64-non_zts70, https://blackfire.io, by SensioLabs
```

### PR DESCRIPTION
**Pull request by nykopol**
I am targeting this branch, because is BC.

Closes #4859 

## Changelog

```markdown
### Fixed
- fix behaviour of `AbstractAdmin::preValidate` by relying on form event listener
```

## Subject

The `AbstractAdmin::preValidate` method was not called before the effective symfony validation. This PR fix that by relying on form event listener.

The real Symfony validation is done by the [ValidatorListener](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/Validator/EventListener/ValidationListener.php) on `FormEvents::POST_SUBMIT` event with the priority 0. 

With this patch, the `preValidation` is called on `FormEvents::POST_SUBMIT` event with the priority 100 (the highest the priority, the earlier a listener is executed).

### CODE REVIEW

File: src/Controller/CRUDController.php [hunk 1]
```diff
@@ -314,10 +314,6 @@ public function editAction($id = null)
         $form->handleRequest($request);
 
         if ($form->isSubmitted()) {
-            //TODO: remove this check for 4.0
-            if (method_exists($this->admin, 'preValidate')) {
```
Comment (kunicmarko20) [inline src/Controller/CRUDController.php]: Isn't it a BC if you remove this?

File: src/Admin/AbstractAdmin.php [hunk 2]
```diff
@@ -692,6 +694,11 @@ public function delete($object)
         }
     }
 
+    public function onPostSubmit(FormEvent $event)
```
Comment (jlamur) [inline src/Admin/AbstractAdmin.php]: Please do not add new methods to the `AbstractAdmin` class, we already have enough SRP violations on this class.

You could use a closure like this instead:
```php
->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
    $this->preValidate($event->getData());
}, 100)

File: src/Controller/CRUDController.php (hunk 1 above)
Comment (core23) [reply src/Controller/CRUDController.php]: Technically yes, but it didn't work as expected. So this is a bugfix.

Comment (nykopol) [reply src/Controller/CRUDController.php]: `preValidate` method is still call but at the right moment now. So i think that we can say it's BC compatible.

File: src/Admin/AbstractAdmin.php (hunk 2 above)
Comment (nykopol) [reply src/Admin/AbstractAdmin.php]: ok i did it

File: src/Admin/AbstractAdmin.php [hunk 3]
```diff
@@ -2837,7 +2839,12 @@ protected function buildForm()
             }
         }
 
-        $this->form = $this->getFormBuilder()->getForm();
+        $self = $this;
```
Comment (jordisala1991) [inline src/Admin/AbstractAdmin.php]: why this?

File: src/Controller/CRUDController.php (hunk 1 above)
Comment (jordisala1991) [reply src/Controller/CRUDController.php]: You need to keep the if, wherever you call the method because it could not be there.

**Comment by jordisala1991** [comment]
@Koc can you give your opinion on this since you first implemented this feature on  #3493

**Comment by core23** [comment]
Can you try to add a test @nykopol ?

**Comment by nykopol** [comment]
@core23 i added some tests to check that an event listener is added on `FormEvents::POST_SUBMIT` before Symfony validation and that the callback call the `preValidate` method. Is it ok like that or i must test something else?

**Comment by nykopol** [comment]
@jlamur I did the requested changes can you confirm that it's ok for you now? 

Unless i missed something, i think that this PR is ready to be merged.

File: src/Admin/AbstractAdmin.php [hunk 4]
```diff
@@ -2837,7 +2839,14 @@ protected function buildForm()
             }
         }
 
-        $this->form = $this->getFormBuilder()->getForm();
+        $formBuilder = $this->getFormBuilder();
+        $formBuilder->addEventListener(FormEvents::POST_SUBMIT, function (FormEvent $event) {
+            if (method_exists($this, 'preValidate')) {
```
Comment (core23) [inline src/Admin/AbstractAdmin.php]: Do you need this check? The method will always exist in an `AbstractAdmin`

Comment (jordisala1991) [reply src/Admin/AbstractAdmin.php]: Not if it is not on the interface

Comment (jordisala1991) [reply src/Admin/AbstractAdmin.php]: oh, I didnt saw that this method is directly on the abstractAdmin, so this is indeed not needed. Sorry for the mistake, the if is not needed. Can you remove it?

**Comment by jordisala1991** [comment]
Thanks @nykopol
