### PR TITLE
Fix sonata_help not showing for subfields and add the has-error class

### LINKED ISSUE #4656: Help message sonata_help not showing for subfields
#### Sonata packages

```
sonata-project/admin-bundle              3.23.0 = 3.23.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  = 3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  = 1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  = 2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.3.1  = 3.3.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0  = 3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  = 2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  = 1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7  = 3.1.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  = 2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  = 1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.2  = 3.2.2  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  ! 1.1.0  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.2  = 2.3.2  Symfony SonataIntlBundle
sonata-project/media-bundle              3.6.0  = 3.6.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.2.0  = 3.2.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.5.2  = 3.5.2  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.2.0  = 2.2.0  Symfony SonataSeoBundle
sonata-project/user-bundle               3.2.4  = 3.2.4  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/assetic-bundle     v2.8.2  = v2.8.2  Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0  = v3.1.0  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.27 ~ v3.3.9  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.5.0  = v1.5.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.5.0  = v1.5.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.5.0  = v1.5.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.5.0  = v1.5.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.5.0  = v1.5.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  = v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  ~ v3.0.3  Symfony SwiftmailerBundle
symfony/symfony            v2.8.27 = v2.8.27 The Symfony PHP framework
```

#### PHP version

```
PHP 5.5.38 (cli) (built: Jul 20 2016 11:16:05)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

## Subject

Sonata help for subfields isn't shown, but it should be as explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field). When aan error occurs in a subfield, error message is not in red color as other form fields with errors.

## Steps to reproduce

Add a new form of type `sonata_type_immutable_array` like explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field) and add the help message.

## Expected results

Help is shown right under the field.

## Actual results

Help is not shown.

### PR DESCRIPTION
**Pull request by gremo**
I am targeting this branch, because this is a bugfix.

Closes #4656

## Changelog

```markdown
### Fixed
- Print of `sonata_help` for form subfields
- Error class for `sonata_type_immutable_array` form group
```

## Subject

Sonata help for subfields isn't shown, but it should be as explained [here](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field). When aan error occurs in a subfield, error message is not in red color as other form fields with errors.

### CODE REVIEW

**Comment by jlamur** [comment]
I just edited your changelog @gremo. `Added` and `Changed` sections moved to `Fixed`.

File: Form/Extension/Field/Type/FormTypeFieldExtension.php [hunk 1]
```diff
@@ -87,13 +87,13 @@ public function buildForm(FormBuilderInterface $builder, array $options)
...
     {
         $sonataAdmin = $form->getConfig()->getAttribute('sonata_admin');
+        $sonataAdminHelp = isset($options['sonata_help']) ? $options['sonata_help'] : null;
 
         /*
          * We have a child, so we need to upgrade block prefix
          */
         if ($view->parent && $view->parent->vars['sonata_admin_enabled'] && !$sonataAdmin['admin']) {
             $blockPrefixes = $view->vars['block_prefixes'];
-
```
[the remark this answers is not in the document]
Comment (gremo) [reply Form/Extension/Field/Type/FormTypeFieldExtension.php]: @jlamur your' right 😁 no reason at all, my bad... will fix it before merging..

File: Form/Extension/Field/Type/FormTypeFieldExtension.php [hunk 2]
```diff
@@ -115,13 +115,12 @@ public function buildView(FormView $view, FormInterface $form, array $options)
                 'class' => false,
                 'options' => $this->options,
             );
+            $view->vars['sonata_help'] = $sonataAdminHelp;
```
Comment (greg0ire) [inline Form/Extension/Field/Type/FormTypeFieldExtension.php]: Why not just write `$sonataAdminHelp = isset($options['sonata_help']) ? $options['sonata_help'] : null;`?

Comment (gremo) [reply Form/Extension/Field/Type/FormTypeFieldExtension.php]: The assignment you are talking about is at the very top of the method definition and $sonataAdminHelp is used two times in the method, so I moved in to the top.

Comment (greg0ire) [reply Form/Extension/Field/Type/FormTypeFieldExtension.php]: Oh ok didn't see the second occurence.

**Comment by greg0ire** [comment]
Please fix the unit tests.

**Comment by gremo** [comment]
@greg0ire Yep, sorry about that, forgot to test berfore commit....

**Comment by greg0ire** [comment]
Thanks @gremo !

**Comment by gremo** [comment]
Thanks to you @greg0ire 😄 about that, how can I join the contributors team?

**Comment by Soullivaneuh** [comment]
@gremo By contributing. :trollface:

**Comment by greg0ire** [comment]
Hey! We have no fixed rules about that, but last time it was a matter of having done quite a few PRs and also many reviews. If you want to join the team, please read the `CONTRIBUTING.md` entirely and start reviewing incoming PRs (enforce our rules, spot BC-breaks... get noticed with your wise comments). Also, come help on the #sonata slack channel on the Symfony slack if you can.
