### PR TITLE
Fix deprecations

### LINKED ISSUE #4229: How do I remove translations from admin class?
Hi,

Since v3.9, translations no longer have to be managed by the class admin but is it possible to have examples of how to do it via the controller or via the template?

It is understandable that you want to decrease the dependency of the admin class but it does not complicate things to quickly have a functional bundle for a dev?

Before it was possible to add only one admin class and everything worked while now it will be necessary to add templates or controllers each time?

Thank you!

### PR DESCRIPTION
**Pull request by wouterj**
I am targetting this branch, because no BC break, bug fix.

Closes #4229

## Changelog

```markdown
### Removed
- a Twig deprecation added in Twig 1.28.0
- a Sonata deprecation called by Sonata itself by adding a way to disable it when called internally
```

### CODE REVIEW

File: Admin/AbstractAdmin.php [hunk 1]
```diff
@@ -2172,12 +2172,14 @@ public function getTranslationDomain()
      *
      * @deprecated since 3.9, to be removed with 4.0
      */
-    public function setTranslator(TranslatorInterface $translator)
+    public function setTranslator(TranslatorInterface $translator, $deprecation = true)
```
Comment (greg0ire) [inline Admin/AbstractAdmin.php]: This trick is nice, but…neither the method nor the class are final, so [this is a BC-break](https://3v4l.org/dVLLZ). I just thought of another solution 💡  Why not use `func_get_args()` ?

File: Resources/views/standard_layout.html.twig [hunk 2]
```diff
@@ -8,18 +8,18 @@ For the full copyright and license information, please view the LICENSE
...
-{% set _list_table           = block('list_table') %}
-{% set _list_filters         = block('list_filters') %}
-{% set _tab_menu             = block('tab_menu') %}
-{% set _content              = block('content') %}
-{% set _title                = block('title') %}
-{% set _breadcrumb           = block('breadcrumb') %}
-{% set _actions              = block('actions') %}
-{% set _navbar_title         = block('navbar_title') %}
-{% set _list_filters_actions = block('list_filters_actions') %}
+{% set _preview              = block('preview') is defined ? block('preview') : null %}
```
Comment (greg0ire) [inline Resources/views/standard_layout.html.twig]: I don't get it… how can a method return something that is not defined? Even `null` is defined… it's… `null`. Not saying this is wrong [the documentation suggests this is valid](http://twig.sensiolabs.org/doc/tests/defined.html), it's just… I don't get what this does. Also, why not use the `default` filter here, like this : `block('preview')|default(null)` ?

**Comment by greg0ire** [comment]
I took the liberty to create a changelog from the subject of your PR, this is needed for releases.

File: Resources/views/standard_layout.html.twig (hunk 2 above)
Comment (wouterj) [inline Resources/views/standard_layout.html.twig]: `is defined` is a strange construct that does a lot more than checking if it's `null`. In Twig 1.28, they also added `is defined` support for `block()` calls: https://github.com/twigphp/Twig/pull/2239

So instead of looking at it from a `block('preview') === null` point of view, you should read it as `block preview is defined`.

About `|default()`, it uses `twig_test_empty()`, which doesn't use the `is defined` construct but just compares blank values against the object. So it wouldn't work.

File: Admin/AbstractAdmin.php (hunk 1 above)
Comment (wouterj) [inline Admin/AbstractAdmin.php]: Alright, I'll change it (although I think nobody ever would rewrite this method).

**Comment by wouterj** [comment]
> I took the liberty to create a changelog from the subject of your PR, this is needed for releases.

No problem.

File: Resources/views/standard_layout.html.twig (hunk 2 above)
Comment (greg0ire) [inline Resources/views/standard_layout.html.twig]: Thanks, I get it now! `defined` is indeed a bit strange 😅

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

File: Admin/AbstractAdmin.php [hunk 3]
```diff
@@ -2174,10 +2174,13 @@ public function getTranslationDomain()
      */
     public function setTranslator(TranslatorInterface $translator)
     {
-        @trigger_error(
-            'The '.__METHOD__.' method is deprecated since version 3.9 and will be removed in 4.0.',
-            E_USER_DEPRECATED
-        );
+        $args = func_get_args();
+        if (isset($args[1]) && $args[1]) {
```
Comment (core23) [inline Admin/AbstractAdmin.php]: Why? You can't pass null to this method: https://3v4l.org/OWTAH

Comment (wouterj) [inline Admin/AbstractAdmin.php]: It's validating the second argument. See https://github.com/sonata-project/SonataAdminBundle/pull/4235#discussion_r92720511

Comment (core23) [inline Admin/AbstractAdmin.php]: You're right. Just got caught in the simple 0 and 1 adressing problem 😆

**Comment by greg0ire** [comment]
Thanks a lot @wouterj !
