### PR TITLE
Fix help deprecation

### LINKED ISSUE #6319: Render help
**SonataAdminBundle 3.73.0**

Edit form renders as:
image

There has many problems:
1) paragraph inside inline-element (span)
2) empty span if no help
3) deprecation notice throws

TODO:
1) No inside. Use help_attr.class
2) Remove deprecate throws from \Sonata\AdminBundle\Admin\BaseFieldDescription::getHelp (add NEXT_MAJOR: Remove this method.)

### PR DESCRIPTION
**Pull request by kirya-dev**
##  Too many deprecation notices

I am targeting this branch, because receive too many deprecation notices and in upgrades was not actual instructions.

Closes #6319.
Addition for #6215.

## Changelog

```markdown
### Fixed
- Remove unnecessary span wrapper for field help. Merge styles with paragraph.
- Prevent too many deprecation notices.
```

### CODE REVIEW

**Comment by kirya-dev** [comment]
After:
image

File: src/Form/FormMapper.php [hunk 1]
```diff
@@ -137,10 +137,10 @@ public function add($name, $type = null, array $options = [], array $fieldDescri
             }
 
             // NEXT_MAJOR: Remove this block.
-            if (isset($options['help'])) {
+            if (isset($options['help']) && !isset($options['help_html'])) {
                 $containsHtml = $options['help'] !== strip_tags($options['help']);
 
-                if (!isset($options['help_html']) && $containsHtml) {
+                if ($containsHtml) {
```
Comment (greg0ire) [inline src/Form/FormMapper.php:143]: What does this fix?

File: src/Resources/views/Form/form_admin_fields.html.twig [hunk 2]
```diff
@@ -33,11 +33,12 @@ file that was distributed with this source code.
...
 {% endblock %}
 
-{% block form_help %}
-    {% apply spaceless %}
-        <span class="help-block sonata-ba-field-widget-help sonata-ba-field-help">{{ parent() }}</span>
-    {% endapply %}
-{% endblock %}
+{% block form_help -%}
+    {% if help is not empty %}
+        {% set help_attr = help_attr|merge({class: (help_attr.class|default('') ~ ' help-block sonata-ba-field-help')}) %}
```
Comment (greg0ire) [inline src/Resources/views/Form/form_admin_fields.html.twig:38]: Why is `sonata-ba-field-widget-help` removed?

**Review by greg0ire — COMMENTED** [review]
Thanks for this contribution! There are parts I don't understand. If you are fixing many unrelated things, consider making more commits with explanations :pray: 

"Fix help deprecation" does not help understanding what you are doing.

File: src/Form/FormMapper.php (hunk 1 above)
Comment (kirya-dev) [reply src/Form/FormMapper.php:143]: Escape striptag if option label_html is set

File: src/Resources/views/Form/form_admin_fields.html.twig (hunk 2 above)
Comment (kirya-dev) [reply src/Resources/views/Form/form_admin_fields.html.twig:38]: No usages was found by me (:

File: src/Form/FormMapper.php (hunk 1 above)
Comment (kirya-dev) [reply src/Form/FormMapper.php:143]: So is simplest optimization

Comment (greg0ire) [reply src/Form/FormMapper.php:143]: Oh right that makes sense. This should be in a commit saying `Do not strip tags when help_html is set`.

File: src/Resources/views/Form/form_admin_fields.html.twig (hunk 2 above)
Comment (VincentLanglet) [reply src/Resources/views/Form/form_admin_fields.html.twig:38]: It can theorically be used by a developer for specific css or js. We shouldnt remove class IMHO.

Comment (kirya-dev) [reply src/Resources/views/Form/form_admin_fields.html.twig:38]: 4 classes for just help is too many...
You should understand that  in theorically they can relate on this element as:
```CSS
.help-block p {
 margin-top: 3px;
}
```
But after this fix need: 
```CSS
.help-block {
 margin-top: 3px;
}
```

Comment (VincentLanglet) [reply src/Resources/views/Form/form_admin_fields.html.twig:38]: Maybe but it's still a Bc break.
The only thing you can do would be to deprecate some css class on 3.x and remove then in master.

File: src/Form/FormMapper.php (hunk 1 above)
Comment (kirya-dev) [reply src/Form/FormMapper.php:143]: Commited

File: src/Resources/views/Form/form_admin_fields.html.twig (hunk 2 above)
Comment (kirya-dev) [reply src/Resources/views/Form/form_admin_fields.html.twig]: Done

**Review by greg0ire — APPROVED** [review]

File: UPGRADE-3.x.md [hunk 3]
```diff
@@ -40,7 +40,7 @@ You MUST use Symfony's [`help`](https://symfony.com/doc/4.4/reference/forms/type
 Before:
 ```php
 $formMapper
-    ->add('field', null, [
+    ->add('field', null, [], [
```
Comment (franmomu) [inline UPGRADE-3.x.md:43]: Good catch! can we add both examples?

Comment (kirya-dev) [reply UPGRADE-3.x.md:43]: setHelp & setHelps ?

File: src/Admin/BaseFieldDescription.php [hunk 4]
```diff
@@ -475,14 +475,15 @@ public function setHelp($help)
...
+    /**
+     * NEXT_MAJOR: Remove this method.
+     *
+     * @deprecated since sonata-project/admin-bundle 3.x and will be removed in version 4.0. Use Symfony Form "help" option instead.
+     *
+     * @return string
+     */
     public function getHelp()
     {
-        @trigger_error(sprintf(
```
Comment (VincentLanglet) [inline src/Admin/BaseFieldDescription.php:480]: Currently we always add a deprecation before removing a method. Why cant we do this here ?

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Admin/BaseFieldDescription.php (hunk 4 above)
Comment (kirya-dev) [reply src/Admin/BaseFieldDescription.php:480]: Also needs template call `.getHelp('sonata_deprecation_mute')` instead of `.help`

Comment (kirya-dev) [reply src/Admin/BaseFieldDescription.php:480]: Done

File: UPGRADE-3.x.md (hunk 3 above)
Comment (kirya-dev) [reply UPGRADE-3.x.md:43]: Done

**Review by VincentLanglet — APPROVED** [review]

File: UPGRADE-3.x.md [hunk 5]
```diff
@@ -40,8 +40,14 @@ You MUST use Symfony's [`help`](https://symfony.com/doc/4.4/reference/forms/type
...
         'help' => 'Help text <small>Please!</small>',
+    ])
+    ->add('field2')
+    ->addHelp('field2', 'This field is required.')
```
Comment (jordisala1991) [inline UPGRADE-3.x.md:47]: isnt this deprecated? IMo we should not add docs about deprecated things. What is the correct way to add helps now?

Comment (kirya-dev) [reply UPGRADE-3.x.md:47]: It is before - after example

**Comment by jordisala1991** [comment]
Thank you @kirya-dev

File: src/Admin/BaseFieldDescription.php [hunk 6]
```diff
@@ -475,13 +475,22 @@ public function setHelp($help)
         $this->help = $help;
     }
 
+    /**
+     * NEXT_MAJOR: Remove this method.
+     *
+     * @deprecated since sonata-project/admin-bundle 3.x and will be removed in version 4.0. Use Symfony Form "help" option instead.
```
Comment (phansys) [inline src/Admin/BaseFieldDescription.php:481]: The version where this method was deprecated is already released, so "3.74" should be used instead of "3.x".

File: UPGRADE-3.x.md (hunk 3 above)
Comment (franmomu) [reply UPGRADE-3.x.md:43]: Well I meant like:
```php
->add('field_with_help_in_form_options', null, ['help' => '...'])
->add('field_with_help_in_field_description_options', null, [], ['help' => '...'])
```

Comment (kirya-dev) [reply UPGRADE-3.x.md:43]: Maybe.. But in new example we showing two moments how stop throwing deprecating notices
