### PR TITLE
Hotfix Bug #4467

### LINKED ISSUE #4467: [ModelAutocompleteFilter] Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property
#### Sonata packages

```bash
$ composer show sonata-project/*
# Put the result here.
sonata-project/admin-bundle              3.17.0 The missing Symfony Admin...
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.3.0  Symfony SonataClassificat...
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral exte...
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrat...
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtends...
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/media-bundle              3.5.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificatio...
```

#### Symfony packages

```bash
$ composer show symfony/*
# Put the result here.
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.7 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* fun...
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related...
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring exten...
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5...
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7...
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PH...
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Acces...
symfony/swiftmailer-bundle v2.5.4 Symfony SwiftmailerBundle
symfony/symfony            v3.2.7 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
# Put the result here.
PHP 5.6.30 (cli) (built: Apr 24 2017 04:59:14) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.3, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

Auto complete filters stop working, with error: 
>Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.

## Steps to reproduce

1. 
```  
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
    $datagridMapper->add(
        'name',
        ModelAutocompleteFilter::class,
        [],
        ModelAutocompleteType::class,
        [
            'property'=>'property',
            'minimum_input_length' => number
        ]
    );
}
```
2. Access CRUD list
3. Add filter _name_
4. Input _number_ characters in filter input

## Expected results
JSON list of options

## Actual results
```
Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property.
500 Internal Server Error - InvalidArgumentException 

Stack Trace
    in var/cache/dev/classes.php at line 13041  
    at AbstractAdmin ->checkAccess (null)
    in vendor/sonata-project/admin-bundle/Controller/HelperController.php at line 410  
    at HelperController ->retrieveAutocompleteItemsAction (object(Request))
    at call_user_func_array (array(object(HelperController), 'retrieveAutocompleteItemsAction'), array(object(Request)))
    in var/cache/dev/classes.php at line 4229  
    at HttpKernel ->handleRaw (object(Request), 1)
    in var/cache/dev/classes.php at line 4184  
    at HttpKernel ->handle (object(Request), 1, true)
    in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 168  
    at Kernel ->handle (object(Request))
    in web/app_dev.php at line 29  
```

### PR DESCRIPTION
**Pull request by YaoOcelotl**
I am targeting this branch, because bug fix patch.

Closes #4467

## Changelog

```markdown
### Fixed
 - [ModelAutocompleteFilter] Action "" could not be found in access mapping. Please make sure your action is defined into your admin class accessMapping property
```
## Subject

Hotfix for [ModelAutocompleteFilter] Action "" could not be found in
access mapping. Please make sure your action is defined into your admin
class accessMapping property #4467

### CODE REVIEW

File: Controller/HelperController.php [hunk 1]
```diff
@@ -380,7 +380,7 @@ public function retrieveAutocompleteItemsAction(Request $request)
             $itemsPerPage = $filterAutocomplete->getFieldOption('items_per_page', 10);
             $reqParamPageNumber = $filterAutocomplete->getFieldOption('req_param_name_page_number', '_page');
             $toStringCallback = $filterAutocomplete->getFieldOption('to_string_callback');
-            $targetAdminAccessAction = $filterAutocomplete->getFieldOption('target_admin_access_action');
+            $targetAdminAccessAction = $filterAutocomplete->getFieldOption('target_admin_access_action','list');
```
Comment (greg0ire) [inline Controller/HelperController.php]: The build probably fails because you miss a space before `'list'`

**Comment by jordisala1991** [comment]
Thank you @YaoOcelotl
