### PR TITLE
Stop building show/list/form when accessing fieldDescription

### LINKED ISSUE #6142: Infinite Recursion when using fields with 'help' option
### Environment

* Ubuntu 20.04
* Symfony 4.4
* PHP 7.4

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.69.0 3.69.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.19.0 4.2.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.20.0 3.20.0 Symfony SonataCoreBundle (abandoned)
sonata-project/doctrine-extensions       1.6.0  1.6.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.18.0 3.18.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.2.0  2.2.0  Lightweight Exporter library
sonata-project/form-extensions           0.1.2  1.4.0  Symfony form extensions
sonata-project/twig-extensions           0.1.1  1.3.0  Sonata twig extensions
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
Restricting packages listed in "symfony/symfony" to "4.4.*"
symfony/asset                      v4.4.10 v4.4.10 Symfony Asset Component
symfony/browser-kit                v4.4.10 v4.4.10 Symfony BrowserKit Component
symfony/cache                      v4.4.10 v4.4.10 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.1.2  v2.1.2  Generic abstractions related to caching
symfony/config                     v4.4.10 v4.4.10 Symfony Config Component
symfony/console                    v4.4.10 v4.4.10 Symfony Console Component
symfony/css-selector               v4.4.10 v4.4.10 Symfony CssSelector Component
symfony/debug                      v4.4.10 v4.4.10 Symfony Debug Component
symfony/debug-bundle               v4.4.10 v4.4.10 Symfony DebugBundle
symfony/dependency-injection       v4.4.10 v4.4.10 Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.1.2  v2.1.2  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.10 v4.4.10 Symfony Doctrine Bridge
symfony/dom-crawler                v4.4.10 v4.4.10 Symfony DomCrawler Component
symfony/error-handler              v4.4.10 v4.4.10 Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.10 v4.4.10 Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v2.1.2  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.10 v4.4.10 Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.10 v4.4.10 Symfony Filesystem Component
symfony/finder                     v4.4.10 v4.4.10 Symfony Finder Component
symfony/form                       v4.4.10 v4.4.10 Symfony Form Component
symfony/framework-bundle           v4.4.10 v4.4.10 Symfony FrameworkBundle
symfony/http-foundation            v4.4.10 v4.4.10 Symfony HttpFoundation Component
symfony/http-kernel                v4.4.10 v4.4.10 Symfony HttpKernel Component
symfony/inflector                  v4.4.10 v4.4.10 Symfony Inflector Component
symfony/intl                       v4.4.10 v4.4.10 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mime                       v4.4.10 v4.4.10 A library to manipulate MIME messages
symfony/monolog-bridge             v4.4.10 v4.4.10 Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver           v4.4.10 v4.4.10 Symfony OptionsResolver Component
symfony/phpunit-bridge             v5.1.1  v5.1.1  Symfony PHPUnit Bridge
symfony/polyfill-ctype             v1.17.0 v1.17.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.17.0 v1.17.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-idn          v1.17.0 v1.17.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.17.0 v1.17.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-php73             v1.17.0 v1.17.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.17.0 v1.17.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.10 v4.4.10 Symfony Process Component
symfony/property-access            v4.4.10 v4.4.10 Symfony PropertyAccess Component
symfony/property-info              v4.4.10 v4.4.10 Symfony Property Info Component
symfony/proxy-manager-bridge       v4.4.10 v4.4.10 Symfony ProxyManager Bridge
symfony/psr-http-message-bridge    v2.0.0  v2.0.0  PSR HTTP message bridge
symfony/routing                    v4.4.10 v4.4.10 Symfony Routing Component
symfony/security                   v4.4.10 v4.4.10 Symfony Security Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.10 v4.4.10 Symfony SecurityBundle
symfony/serializer                 v4.4.10 v4.4.10 Symfony Serializer Component
symfony/service-contracts          v2.1.2  v2.1.2  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.10 v4.4.10 Symfony Stopwatch Component
symfony/string                     v5.1.1  v5.1.1  Symfony String component
symfony/swiftmailer-bundle         v3.2.4  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.4.10 v4.4.10 Symfony Templating Component
symfony/translation                v4.4.10 v4.4.10 Symfony Translation Component
symfony/translation-contracts      v2.1.2  v2.1.2  Generic abstractions related to translation
symfony/twig-bridge                v4.4.10 v4.4.10 Symfony Twig Bridge
symfony/twig-bundle                v4.4.10 v4.4.10 Symfony TwigBundle
symfony/validator                  v4.4.10 v4.4.10 Symfony Validator Component
symfony/var-dumper                 v4.4.10 v4.4.10 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.4.10 v4.4.10 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle        v4.4.10 v4.4.10 Symfony WebProfilerBundle
symfony/webpack-encore-bundle      v1.7.3  v1.7.3  Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v4.4.10 v4.4.10 Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.4.7 (cli) (built: Jun 12 2020 07:47:45) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.7, Copyright (c), by Zend Technologies
    with Xdebug v2.9.6, Copyright (c) 2002-2020, by Derick Rethans
```

## Subject

After upgrading to v3.69.0, we started to experience
```
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted...
```
while requesting many of our sonata admin pages. Breaking with the debugger before this memory exhaustion occurred showed this stack trace, suggesting infinite recursion when trying to map form fields.
```
... etc ...
(Proprietary Admin)->configureFormFields()
AbstractAdmin.php:1381, (Proprietary Admin)->defineFormBuilder()
AbstractAdmin.php:1354, (Proprietary Admin)->getFormBuilder()
AbstractAdmin.php:3360, (Proprietary Admin)->buildForm()
AbstractAdmin.php:1825, (Proprietary Admin)->getFormFieldDescription()
FormMapper.php:143, Sonata\AdminBundle\Form\FormMapper->add()
(Proprietary Admin)->configureFormFields()
AbstractAdmin.php:1381, (Proprietary Admin)->defineFormBuilder()
AbstractAdmin.php:1354, (Proprietary Admin)->getFormBuilder()
AbstractAdmin.php:3360, (Proprietary Admin)->buildForm()
AbstractAdmin.php:1825, (Proprietary Admin)->getFormFieldDescription()
FormMapper.php:143, Sonata\AdminBundle\Form\FormMapper->add()
(Proprietary Admin)->configureFormFields()
AbstractAdmin.php:1381, (Proprietary Admin)->defineFormBuilder()
AbstractAdmin.php:1354, (Proprietary Admin)->getFormBuilder()
AbstractAdmin.php:3360, (Proprietary Admin)->buildForm()
AbstractAdmin.php:1429, (Proprietary Admin)->getForm()
CRUDController.php:311, Sonata\AdminBundle\Controller\CRUDController->editAction()
HttpKernel.php:158, Symfony\Component\HttpKernel\HttpKernel->handleRaw()
HttpKernel.php:80, Symfony\Component\HttpKernel\HttpKernel->handle()
Kernel.php:201, TestAppKernel->handle()
... PHPUnit Client ...
```

After commenting out the help options on our form fields, then the errors did not occur. Stepping through the code, `getFormFieldDescription` is only called if the 'help' option is included.

Potentially related to #6104?

## Steps to reproduce

Create an admin with a form element that has help text.

## Expected results

Successful page load.

## Actual results

Out of memory exceptions.

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because I think I have found a BC-way to fix the bug (https://github.com/sonata-project/SonataAdminBundle/issues/6142) which can easily occur and create infinite loop.

Currently methods `getFormFieldDescriptions`, `getFormFieldDescription` and `hasFormFieldDescription` are calling `this->buildForm`.
But the `buildForm` method is calling lot of things, as shown in the issue, we may find
```
if (null !== $help) {
    $this->admin->getFormFieldDescription($name)->setHelp($help);
}
```
in the FormMapper->add, or
```
$formMapper->setHelps(['name' => 'help_page_name']);
```
in the SonataPageBundle configureFormField method witch lead to a `hasFormFieldDescriptions` call.

The developper could also possibly use the `getFormFieldDescriptions`, `getFormFieldDescription` and `hasFormFieldDescription` in the configureFormField and create an infinite loop.

Before we didn't try to build the form if the form was already build.
By adding a state, I now do not try to build the form if the build of the form already started.

Closes #6142.

## Changelog

```markdown
### Fixed
- `getFormFieldDescriptions`, `getFormFieldDescription` and `hasFormFieldDescription` doesn't build form anymore if the build already started, avoiding an infinite loop.
- `getShowFieldDescriptions`, `getShowFieldDescription` and `hasShowFieldDescription` doesn't build show anymore if the build already started, avoiding an infinite loop.
- `getListFieldDescriptions`, `getListFieldDescription` and `hasListFieldDescription` doesn't build list anymore if the build already started, avoiding an infinite loop.
- `getFilterFieldDescriptions`, `getFilterFieldDescription` and `hasFilterFieldDescription` doesn't build datagrid anymore if the build already started, avoiding an infinite loop.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@sonata-project/contributors I need your help on this !

**Comment by jordisala1991** [comment]
If the issue is not easily fixable, isnt it better to just revert your pr and then try to find a better way? to avoid breaking peoples apps.

**Comment by VincentLanglet** [comment]
> If the issue is not easily fixable, isnt it better to just revert your pr and then try to find a better way? to avoid breaking peoples apps.

Yes, if I don't find better solution I will remove the `buildXXX` method only in `getFormFieldDescription`.

But the issue will still be present for others methods, it just not currently happen.

Currently SonataPageBundle call `getFormFieldDescription('toto')` during the configureFormField ; luckily it doesn't build the form. But if the call was made this way `getFormFieldDescriptions['toto']` it would have create the same issue.

But I think I have find the right way to fix this definitely by adding a state.
I build the form only if I've not already started to build the form.
The same strategy was used for the menu or the routes.

**Comment by jordisala1991** [comment]
Looks ok to me, @gremo does it fix your issue?

**Comment by VincentLanglet** [comment]
You want a functionnal test to prevent the infinite loop @core23 ?

**Comment by VincentLanglet** [comment]
Done @core23.

It was pretty useful since I caught a mistake. I wrote 
```
$this->loaded['form']
```
instead of
```
$this->loaded['form'] = true
```
so the PR wasn't fixing the bug...

But everything is ok now.

File: tests/Admin/AdminTest.php [hunk 1]
```diff
@@ -2495,6 +2510,37 @@ public function testAdminWithoutControllerName(): void
...
+        $admin->setFormContractor(new FormContractor($formFactory));
+
+        $admin->setShowBuilder(new ShowBuilder());
+
+        $admin->setListBuilder(new ListBuilder());
+
+        $pager = $this->createMock(PagerInterface::class);
+        $admin->setDatagridBuilder(new DatagridBuilder($formFactory, $pager));
+
+        $validator = $this->createMock(ValidatorInterface::class);
```
Comment (phansys) [inline tests/Admin/AdminTest.php:2531]:
```suggestion
        $validator = $this->createStub(ValidatorInterface::class);
```

File: tests/Admin/AdminTest.php [hunk 2]
```diff
@@ -2495,6 +2510,37 @@ public function testAdminWithoutControllerName(): void
...
+        $validator->method('getMetadataFor')->willReturn($this->createMock(MemberMetadata::class));
+        $admin->setValidator($validator);
+
+        $routeGenerator = $this->getMockForAbstractClass(RouteGeneratorInterface::class);
```
Comment (phansys) [inline tests/Admin/AdminTest.php:2535]: You are already using `createMock()` for interfaces. Why is this case different?

File: src/Admin/AdminInterface.php [hunk 3]
```diff
@@ -360,6 +364,8 @@ public function setSubject($subject);
     public function getSubject();
 
     /**
+     * NEXT_MAJOR: Remove this methods, since it's already in FieldDescriptionRegistryInterface.
```
Comment (phansys) [inline src/Admin/AdminInterface.php:367]:
```suggestion
     * NEXT_MAJOR: Remove this method, since it's already in FieldDescriptionRegistryInterface.
```

File: src/Admin/AdminInterface.php [hunk 4]
```diff
@@ -369,6 +375,8 @@ public function getSubject();
     public function getListFieldDescription($name);
 
     /**
+     * NEXT_MAJOR: Remove this methods, since it's already in FieldDescriptionRegistryInterface.
```
Comment (phansys) [inline src/Admin/AdminInterface.php:378]:
```suggestion
     * NEXT_MAJOR: Remove this method, since it's already in FieldDescriptionRegistryInterface.
```

File: src/Admin/AdminInterface.php [hunk 5]
```diff
@@ -378,6 +386,8 @@ public function getListFieldDescription($name);
     public function hasListFieldDescription($name);
 
     /**
+     * NEXT_MAJOR: Remove this methods, since it's already in FieldDescriptionRegistryInterface.
```
Comment (phansys) [inline src/Admin/AdminInterface.php:389]:
```suggestion
     * NEXT_MAJOR: Remove this method, since it's already in FieldDescriptionRegistryInterface.
```

File: src/Admin/AdminInterface.php [hunk 6]
```diff
@@ -542,13 +552,17 @@ public function setShowGroups(array $showGroups);
     public function reorderShowGroup($group, array $keys);
 
     /**
+     * NEXT_MAJOR: Remove this methods, since it's already in FieldDescriptionRegistryInterface.
```
Comment (phansys) [inline src/Admin/AdminInterface.php:555]:
```suggestion
     * NEXT_MAJOR: Remove this method, since it's already in FieldDescriptionRegistryInterface.
```

File: src/Admin/AdminInterface.php [hunk 7]
```diff
@@ -542,13 +552,17 @@ public function setShowGroups(array $showGroups);
...
+     *
      * add a FieldDescription.
      *
      * @param string $name
      */
     public function addFormFieldDescription($name, FieldDescriptionInterface $fieldDescription);
 
     /**
+     * NEXT_MAJOR: Remove this methods, since it's already in FieldDescriptionRegistryInterface.
```
Comment (phansys) [inline src/Admin/AdminInterface.php:564]:
```suggestion
     * NEXT_MAJOR: Remove this method, since it's already in FieldDescriptionRegistryInterface.
```

**Comment by VincentLanglet** [comment]
Done @phansys

**Comment by core23** [comment]
Thanks @VincentLanglet
