### PR TITLE
#5633 fix using Commands for symfony 2.8.x versions

### LINKED ISSUE #5633: Sonata\AdminBundle\Command\CreateClassCacheCommand is used feature from symfony console 3.4
Hello!
I've got an error
```
[Symfony\Component\Console\Exception\LogicException]
  The command defined in "Sonata\AdminBundle\Command\CreateClassCacheCommand" cannot have an empty name.
```

This is because I use symfony 2.8.* version and composer.json of package SonataAdminBundle is minimum requirement version 2.8. But CreateClassCacheCommand using the feature from symfony console 3.4 is called lazy load https://symfony.com/blog/new-in-symfony-3-4-lazy-commands . Should to use method setName or get command name from the constructor. 

#### Sonata packages

```
sonata-project/admin-bundle                  3.51.0 3.51.0 The missing Symfony Admin G...
sonata-project/block-bundle                  3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                         2.0.1  2.0.1  Cache library
sonata-project/core-bundle                   3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.4.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions           1.3.0  1.3.0  Doctrine2 behavioral extens...
sonata-project/doctrine-mongodb-admin-bundle 3.1.1  3.2.1  Symfony Sonata / Integrate ...
sonata-project/exporter                      2.0.1  2.0.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/assetic-bundle        v2.8.2  v2.8.2  Integrates Assetic into Symfony2
Package symfony/assetic-bundle is abandoned, you should avoid using it. Use symfony/webpack-encore-pack instead.
symfony/http-client           v4.3.2  v4.3.2  Symfony HttpClient component
symfony/http-client-contracts v1.1.5  v1.1.5  Generic abstractions related to HTTP cli...
symfony/mime                  v4.3.2  v4.3.2  A library to manipulate MIME messages
symfony/monolog-bundle        v2.12.1 v3.4.0  Symfony MonologBundle
symfony/phpunit-bridge        v2.8.50 v4.3.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu         v1.11.0 v1.11.0 Symfony polyfill backporting apcu_* func...
symfony/polyfill-ctype        v1.11.0 v1.11.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu     v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related ...
symfony/polyfill-intl-idn     v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii...
symfony/polyfill-mbstring     v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php54        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5....
symfony/polyfill-php55        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5....
symfony/polyfill-php56        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5....
symfony/polyfill-php70        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7....
symfony/polyfill-php72        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7....
symfony/polyfill-php73        v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7....
symfony/polyfill-util         v1.11.0 v1.11.0 Symfony utilities for portability of PHP...
symfony/security-acl          v3.0.2  v3.0.2  Symfony Security Component - ACL (Access...
symfony/swiftmailer-bundle    v2.6.7  v3.2.8  Symfony SwiftmailerBundle
symfony/symfony               v2.8.51 v4.3.2  The Symfony PHP framework
```

#### PHP version

```
PHP 7.2.18 (cli) (built: Jun 26 2019 13:40:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
```

## Subject

[Symfony\Component\Console\Exception\LogicException]
  The command defined in "Sonata\AdminBundle\Command\CreateClassCacheCommand" cannot have an empty name.

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:

    [Symfony\Component\Console\Exception\LogicException]

    The command defined in "Sonata\AdminBundle\Command\CreateClassCacheCommand"
   cannot have an empty name.

  .

## Steps to reproduce
use symfony console 2.8.x
add sonata admin bundle

### PR DESCRIPTION
**Pull request by sinkinov-alexander**
## Subject

fix #5633. Add setName for all Commands in the bundle.

I am targeting this branch, because these changes are BC.

Closes #5633

## Changelog

```markdown
### Fixed
- Call setName method in configure part of Command, for backward compatibility wiht sf 2.8.x 
```

### CODE REVIEW

File: src/Command/CreateClassCacheCommand.php [hunk 1]
```diff
@@ -57,7 +57,9 @@ public function __construct(string $cacheDir, bool $debug)
 
     public function configure(): void
     {
-        $this->setDescription('Generate the classes.php files');
+        $this->setDescription('Generate the classes.php files')
+            ->setName(static::$defaultName)
```
Comment (phansys) [inline src/Command/CreateClassCacheCommand.php]: Please, add a comment explaining why is this call required ([ref](https://github.com/sonata-project/SonataBlockBundle/blob/f6bcbedcacb3314cd5b295f06eb34b006075df02/src/Command/DebugBlocksCommand.php#L41)).

Comment (core23) [reply src/Command/CreateClassCacheCommand.php]: Or just a NEXT_MAJOR hint, so we can remove this when dropping support for Symfony 2

Comment (sinkinov-alexander) [reply src/Command/CreateClassCacheCommand.php]: fix it

File: src/Command/CreateClassCacheCommand.php [hunk 2]
```diff
@@ -57,7 +57,10 @@ public function __construct(string $cacheDir, bool $debug)
 
     public function configure(): void
     {
-        $this->setDescription('Generate the classes.php files');
+        $this->setDescription('Generate the classes.php files')
+            ->setName(static::$defaultName)// BC for symfony/console < 3.4.0
+            // NEXT_MAJOR: drop this line after drop support symfony/console < 3.4.0
```
Comment (greg0ire) [inline src/Command/CreateClassCacheCommand.php]: 2 things:
- you're targetting master, BC-breaks are authorized here. Also, you will not see your changes for a long time if you commit here, and sf < 2.8 support will be dropped before that happens.
- sf < 3.4 is no longer maintained, IMO we should drop support for it.

Comment (sinkinov-alexander) [reply src/Command/CreateClassCacheCommand.php]: Which branch I should target? Or maybe need to drop support from composer.json symfony version 3.4 < ?

Comment (phansys) [reply src/Command/CreateClassCacheCommand.php]: Regarding the base branch, please take a look at https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#the-base-branch.

Comment (sinkinov-alexander) [reply src/Command/CreateClassCacheCommand.php]: done

**Comment by greg0ire** [comment]
Thanks @sinkinov-alexander
