### PR TITLE
fix subject assignment in embedded admins

### LINKED ISSUE #4475: getSubject not set of child admin with sonata_type_collection
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.17.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.2.1  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.5.1  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0  Symfony SonataNotificationBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v3.2.8  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.3-2+deb.sury.org~xenial+1 (cli) (built: Mar 15 2017 09:21:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3-2+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.14.3~linux-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.
```

## Subject

getSubject() returns null as of https://github.com/sonata-project/SonataAdminBundle/commit/0761127cfbaf83f2eec3b02e329f2d751a0b6b0f if used in admin of sonata_type_collection
(https://github.com/sonata-project/SonataAdminBundle/pull/4429)

## Steps to reproduce

create an admin with a sonata_type_collection and in the subadmin create fields based on the subject -> cannot do that because it's empty

## Expected results

getSubject() should return entity

## Actual results

getSubject() returns null

### LINKED ISSUE #4517: getSubject() will return null in configureFormFields() for an entity POSTed to and embedded by sonata_type_admin
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.19.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      2.0.0  Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               3.2.4  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.22 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.4.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.4.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.4.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.22 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.1.4-1+deb.sury.org~trusty+1 (cli) (built: Apr 11 2017 22:45:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.4-1+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.4, Copyright (c) 2002-2017, by Derick Rethans
```

## Subject

When data is posted to an Admin that has been included via the sonata_type_admin form type, configureFormFields() appears to be run twice. The first time, $this->getSubject() will return the entity, the second time, it will return a null.

## Steps to reproduce

1. Create a parent entity & admin
2. Create a child entity & admin
3. Add the child to the parent in the form using:
```php
            $formMapper->add(
                'childEntity',
                'sonata_type_admin',
                [
                    'label' => false,
                    'required' => true,
                    'by_reference' => true,
                    'delete' => false,
                ]
            )
```
4. In the child entity admin, add the following conditional code in the configureFormFields() method:
```php
$formMapper->ifTrue($this->getSubject() !== null && $this->getSubject()->getId() !== null)
->add('aProperty')
->ifEnd()
```
5. Use the admin screen to create the new parent entity (The logic in step 4 will ensure that the aProperty field is not displayed)
6. Save the entity
7. Go to edit the parent entity. Now the aProperty field is correctly displayed.
8. Add some text into it and hit update

## Expected results

The aProperty field should now contain the text that you entered in the child entity.

## Actual results

The error message "This form should not contain extra fields." is displayed as the conditional logic in step 4 returned a false because $this->getSubject() returned a null

## Other (hopefully useful) information

This bug was introduced in sonata-project/admin-bundle:3.15.0. Locking composer to sonata-project/admin-bundle:<=3.14.0 fixes the issue.

If you simply add
```php
dump($this->getSubject()); exit();
```
near the logic in step 4, it will return the populated entity correctly, but it seems that configureFormFields() is run again after this and on the second pass, $this->getSubject() will return null
This may be related to or the same as #4475

### PR DESCRIPTION
**Pull request by wodka**
I am targeting this branch, because the issue was introduced in https://github.com/sonata-project/SonataAdminBundle/pull/4429

also noted in commit: https://github.com/sonata-project/SonataAdminBundle/commit/0761127cfbaf83f2eec3b02e329f2d751a0b6b0f

Closes #4517
Closes #4475

## Changelog

```markdown
### Fixed
- subject assignment in embedded admins
```

## Subject

right now embedded admins within a sonata type collect do not populate subject (this was working till version 3.15)

Since the commit that introduced the error was about fixing a path duplication I also added a check for that (this was in issue: #4425)

### CODE REVIEW

**Comment by wodka** [comment]
@mvhirsch can you check if this change will fix the error you were having?

I also think that I can update the test case to include getFieldName()

> 
> 1) Sonata\AdminBundle\Tests\Form\Type\AdminTypeTest::testDotFields
> Prophecy\Exception\Call\UnexpectedCallException: Method call:
>   - getFieldName()
> on Double\FieldDescriptionInterface\P102 was not expected, expected calls were:
>   - getAssociationAdmin()
> /home/travis/build/sonata-project/SonataAdminBundle/Form/Type/AdminType.php:72
> /home/travis/build/sonata-project/SonataAdminBundle/Tests/Form/Type/AdminTypeTest.php:125

File: Form/Type/AdminType.php [hunk 1]
```diff
@@ -67,11 +67,16 @@ public function buildForm(FormBuilderInterface $builder, array $options)
                             $subject = $subjectCollection->get(trim($options['property_path'], '[]'));
                         }
                     } else {
+                        // this check is to work around duplication issue in property path
+                        // https://github.com/sonata-project/SonataAdminBundle/issues/4425
+                        if ($this->getFieldDescription($options)->getFieldName() === $options['property_path']) {
+                            $path = $options['property_path'];
+                        } else {
+                            $path = $this->getFieldDescription($options)->getFieldName().$options['property_path'];
```
Comment (greg0ire) [inline Form/Type/AdminType.php]: When does this happen and what does it typically produce? Is there no need for a separator here? Is the left part the parent name, and the right part the child name?

Comment (greg0ire) [inline Form/Type/AdminType.php]: Also, is this about children admins or about embed fields of type admin?

Comment (wodka) [inline Form/Type/AdminType.php]: you're right - this is actually about embedded admins

-> the other issue was about duplicating the property path, this is why I kept the check for this. But at the same time it broke the subject finding in the embedded admin

**Comment by c0ntax** [comment]
Blocked because of a 0.01% decrease in code coverage. /me cries

**Comment by greg0ire** [comment]
Don't worry, it's not about the coverage, it's about the lack of reviews.

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by greg0ire** [comment]
You can review the PR too @c0ntax

**Comment by c0ntax** [comment]
I'll do what I can @greg0ire ! :-D

File: Form/Type/AdminType.php (hunk 1 above)
Comment (jordisala1991) [reply Form/Type/AdminType.php]: I would like to know if this is related to using some concrete version of other bundle and can be removed on a next major version like 4.0 of SonataAdmin, or this will stay like this forever

**Comment by CrazyMuffin** [comment]
What's the status on this PR? This would certainly help my project upgrade to higher version.

**Comment by mvhirsch** [comment]
@wodka I'm sorry, but I'm unable to test this change on my project (mentioned in the old PR); since we've changed project focus.

But as far as I can see, it looks good to me. 👍

**Comment by greg0ire** [comment]
Thanks @wodka !
