### PR TITLE
Fix GenerateObjectAclCommand error for symfony 3.4

### LINKED ISSUE #6063: Can't generate Acl with version > 3.49.1
I can't generate acl from command anymore with new sonata-admin versions (~3.5)

```
bin/console sonata:admin:generate-object-acl
```

with version 3.50 i get bunch of:
```
The interface "ObjectAclManipulatorInterface" is not implemented for Sonata\AdminBundle\Command\GenerateObjectAclCommand: ignoring
```
with version 3.57:
```
No manipulators are implemented : ignoring
```
Works well with: 
```
sonata-project/admin-bundle              3.49.1
```

#### Sonata packages
Other Sonata packages

```
sonata-project/block-bundle              3.18.4 3.18.4 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/classification-bundle     3.11.1 3.11.1 Symfony SonataClassificationBundle
sonata-project/core-bundle               3.17.2 3.17.2 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  2.5.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.6.0  1.6.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.13.0 3.15.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.11.1 1.11.1 Lightweight Exporter library
sonata-project/intl-bundle               2.7.0  2.7.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.23.1 3.24.0 Symfony SonataMediaBundle
sonata-project/user-bundle               4.5.1  4.5.2  Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/http-client           v4.4.7  v4.4.7  Symfony HttpClient component
symfony/http-client-contracts v1.1.8  v1.1.8  Generic abstractions related to HTTP clients
symfony/maker-bundle          v1.15.1 v1.15.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                  v4.4.7  v4.4.7  A library to manipulate MIME messages
symfony/monolog-bundle        v3.5.0  v3.5.0  Symfony MonologBundle
symfony/phpunit-bridge        v3.4.39 v5.0.7  Symfony PHPUnit Bridge
symfony/polyfill-apcu         v1.15.0 v1.15.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype        v1.15.0 v1.15.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu     v1.15.0 v1.15.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn     v1.15.0 v1.15.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring     v1.15.0 v1.15.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56        v1.15.0 v1.15.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70        v1.15.0 v1.15.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72        v1.15.0 v1.15.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73        v1.15.0 v1.15.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-util         v1.15.0 v1.15.0 Symfony utilities for portability of PHP codes
symfony/security-acl          v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/service-contracts     v1.1.8  v1.1.8  Generic abstractions related to writing services
symfony/swiftmailer-bundle    v2.6.7  v3.4.0  Symfony SwiftmailerBundle
symfony/symfony               v3.4.39 v4.4.7  The Symfony PHP framework
symfony/webpack-encore-bundle v1.7.3  v1.7.3  Integration with your Symfony app & Webpack Encore!
```

#### PHP version

```
$ php -v
PHP 7.1.33-15+0~20200419.36+debian9~1.gbp2384b3 (cli) (built: Apr 19 2020 08:44:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.33-15+0~20200419.36+debian9~1.gbp2384b3, Copyright (c) 1999-2018, by Zend Technologies
chico@seldon:~/sites/SNAM/randoPortail$ 
```

Thanks in advance for your help :)

### PR DESCRIPTION
**Pull request by olivier-rey**
## Subject

When launching `bin/console sonata:admin:generate-object-acl`, the acl generation doesn't start, instead get output: `No manipulators are implemented : ignoring

`

The current `ObjectAclManipulatorCompilerPass` doesn't take into account that the class definition can use the %parameter% syntax, so the $availableManagers array remains empty.

I am targeting this branch, because this is BC.

Closes #6063

## Changelog

```markdown
### Added
Manage class definition which is using "%parameter%" syntax.
```

### CODE REVIEW

File: src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php [hunk 1]
```diff
@@ -30,7 +30,18 @@ public function process(ContainerBuilder $container): void
...
         foreach ($container->getServiceIds() as $id) {
-            if (0 !== strpos($id, 'sonata.admin.manipulator.acl.object.') || !is_subclass_of($container->getDefinition($id)->getClass(), ObjectAclManipulatorInterface::class)) {
+            if (0 !== strpos($id, 'sonata.admin.manipulator.acl.object.') || null === $class = $container->getDefinition($id)->getClass()) {
+                continue;
+            }
+
+            // We trim the possible "%" characters around the class definition since it could be using "%parameter%" syntax.
+            $class = trim($class, '%');
+
+            if (!class_exists($class, false) && $container->hasParameter(str_replace('%', '', $class))) {
```
Comment (phansys) [inline src/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPass.php:40]: Character "%" is already trimmed at line 38.
```suggestion
            if (!class_exists($class, false) && $container->hasParameter($class)) {
```

**Comment by olivier-rey** [comment]
> Do you see how to test this class @olivier-rey ?

Well not really, but will give it a try

**Comment by olivier-rey** [comment]
@VincentLanglet, @phansys 

Does the unit test file seems ok to you ?

File: tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+        $containerBuilder = $this->getContainerWithParameterAsServiceClass();
+
+        $objectAclManipulatorCompilerPass = new ObjectAclManipulatorCompilerPass();
+
+        $objectAclManipulatorCompilerPass->process($containerBuilder);
+
+        $availableManagers = $containerBuilder->getDefinition(GenerateObjectAclCommand::class)->getArgument(1);
+
+        $this->assertArrayHasKey('sonata.admin.manipulator.acl.object.orm', $availableManagers);
+    }
```
Comment (VincentLanglet) [inline tests/DependencyInjection/Compiler/ObjectAclManipulatorCompilerPassTest.php:51]: Are you familiar with dataProvider ?

Since you're making the same assertion in the test you can write
```
    /**
    * @dataProvider containerProvider
    */
    public function testAvailableManager($containerBuilder): void
    {
        $objectAclManipulatorCompilerPass = new ObjectAclManipulatorCompilerPass();

        $objectAclManipulatorCompilerPass->process($containerBuilder);

        $availableManagers = $containerBuilder->getDefinition(GenerateObjectAclCommand::class)->getArgument(1);

        $this->assertArrayHasKey('sonata.admin.manipulator.acl.object.orm', $availableManagers);
    }

    public function containerDataProvider(): array
    {
        return [
            [$this->getContainerWithServiceClass()],
            [$this->getContainerWithParameterAsServiceClass()],
        ]
    }
```

**Comment by olivier-rey** [comment]
> Good job @olivier-rey!

Thanks to you and @VincentLanglet for you support !!
