### PR TITLE
Fix deprecated BlockService::setDefaultSettings usage

### LINKED ISSUE #3052: Fix deprecated settings method on block service
To be done when https://github.com/sonata-project/SonataBlockBundle/pull/204 will be merged.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Fixes #3052.

### CODE REVIEW

File: Block/AdminSearchBlockService.php [hunk 1]
```diff
@@ -91,7 +91,7 @@ public function getName()
     /**
      * {@inheritdoc}
      */
-    public function setDefaultSettings(OptionsResolverInterface $resolver)
+    public function configureSettings(OptionsResolverInterface $resolver)
```
Comment (Koc) [inline Block/AdminSearchBlockService.php]: This method works with contrete implementation, not with interface

Comment (Soullivaneuh) [inline Block/AdminSearchBlockService.php]: What did you mean?

Comment (Koc) [inline Block/AdminSearchBlockService.php]: See method signature
https://github.com/sonata-project/SonataBlockBundle/pull/204/files#diff-0470a0f1cfc16aa469b68ab7066b5a46R37

```php
public function configureSettings(OptionsResolver $resolver)
```
so use `OptionsResolver ` instead of `OptionsResolverInterface`

Comment (Soullivaneuh) [inline Block/AdminSearchBlockService.php]: Oh indeed, I forgot that. Thanks.

**Comment by Soullivaneuh** [comment]
@rande I think this will be BC break if someone override `setDefaultSettings` method for one of those block services.

What do you think? If yes, should we manage it?

**Comment by Soullivaneuh** [comment]
I think not. I created AbstractBlockService for handle that.

Will create tests to be sure.

**Comment by Soullivaneuh** [comment]
Verified by tests. Works like a charm. :+1:
