### PR TITLE
Fixed duplicate translation in filters

### LINKED ISSUE #3283: filter values are not translated
bildschirmfoto 2015-09-24 um 11 04 32

how should we solve this?
shall we introduce keys for this?
shall we bring this to a Sonata* translation domain scope?

### PR DESCRIPTION
**Pull request by core23**
I am targetting this branch, because this is a patch.

Closes #3283

## Changelog

```markdown
### Fixed
- Fixed duplicate translation for list filters
```

## Subject

The filters in the list were translated two times, once in the php classes and a second time in the twig template. 

Before
bildschirmfoto 2016-07-31 um 19 30 33

After
bildschirmfoto 2016-07-31 um 19 31 46

### CODE REVIEW

File: Form/Type/Filter/ChoiceType.php [hunk 1]
```diff
@@ -31,6 +31,8 @@ class ChoiceType extends AbstractType
     const TYPE_EQUAL = 3;
 
     /**
+     * @deprecated since 3.x, to be remove with 4.0
```
Comment (greg0ire) [inline Form/Type/Filter/ChoiceType.php]: Removed

**Comment by greg0ire** [comment]
Good job!

**Comment by greg0ire** [comment]
LGTM despite both failing checks.

**Comment by Soullivaneuh** [comment]
@core23 This is not a patch but a minor as you deprecated some stuff.

LGTM. :+1:
