### PR TITLE
Bug - Removed do-not-use alias for exporter service

### LINKED ISSUE #7134: Export doesn't work anymore
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.98.1 3.98.1 The missing Symfony Admin Generator
sonata-project/block-bundle              4.5.3  4.5.3  Symfony SonataBlockBundle
sonata-project/cache                     2.1.1  2.1.1  Cache library
sonata-project/doctrine-extensions       1.12.0 1.12.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.33.0 3.33.0 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2  2.6.2  Lightweight Exporter library
sonata-project/form-extensions           1.9.0  1.9.0  Symfony form extensions
sonata-project/twig-extensions           1.5.1  1.5.1  Sonata twig extensions
```

## Actual results

```
You have requested a non-existent service "sonata.exporter.exporter.do-not-use". Did you mean this: "sonata.exporter.exporter"
```

```
/vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php in Sonata\AdminBundle\Controller\CRUDController::exportAction at line 962
```

cc @eerison

### PR DESCRIPTION
**Pull request by eerison**
## Remove `do-not-use` alias for exporter service

I am targeting this branch, because it's failing in 3.x version.

Closes #7134.

## Changelog

```markdown
### Fixed
- Remove `do-not-use` alias for exporter service.

```

### CODE REVIEW

File: src/Controller/CRUDController.php [hunk 1]
```diff
@@ -954,9 +954,9 @@ public function exportAction(Request $request)
...
                 $format
             );
-            $exporter = $this->get('sonata.admin.exporter.do-not-use');
+            $exporter = $this->get('sonata.admin.exporter');
         } else {
-            $adminExporter = $this->get('sonata.admin.admin_exporter.do-not-use');
+            $adminExporter = $this->get('sonata.admin.admin_exporter');
             $allowedExportFormats = $adminExporter->getAvailableFormats($this->admin);
             $filename = $adminExporter->getExportFilename($this->admin, $format);
             $exporter = $this->get('sonata.exporter.exporter.do-not-use');
```
Comment (VincentLanglet) [inline src/Controller/CRUDController.php:962]: This is the wrong one. Not 'sonata.admin.admin_exporter.do-not-use'

**Review by VincentLanglet — CHANGES_REQUESTED** [review]

File: src/Controller/CRUDController.php [hunk 2]
```diff
@@ -954,7 +954,7 @@ public function exportAction(Request $request)
                 date('Y_m_d_H_i_s', strtotime('now')),
                 $format
             );
-            $exporter = $this->get('sonata.admin.exporter.do-not-use');
+            $exporter = $this->get('sonata.admin.exporter');
```
Comment (VincentLanglet) [inline src/Controller/CRUDController.php:957]: This one should stay untouched, the error is line 962
```
$exporter = $this->get('sonata.exporter.exporter.do-not-use');
```

**Review by VincentLanglet — APPROVED** [review]

**Comment by jordisala1991** [comment]
Thank you @eerison
