### PR TITLE
Data Transformers in list fields editable

### LINKED ISSUE #5693: Data Transformers in list fields editable
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.52.0 3.53.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.18.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.9.0  3.10.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.4.0  v3.4.0  Symfony MonologBundle
symfony/polyfill-apcu      v1.12.0 v1.12.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.12.0 v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv     v1.12.0 v1.12.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.12.0 v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn  v1.12.0 v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring  v1.12.0 v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.12.0 v1.12.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.8  v3.2.8  Symfony SwiftmailerBundle
symfony/symfony            v3.4.31 v4.3.4  The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.3.9 (cli) (built: Sep  3 2019 06:20:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

I can use `DataTransformer` in `configureFormFields()`, but i can not use it in `configureListFields()`.
Need add ability to use a [DataTransformer](https://symfony.com/doc/current/form/data_transformers.html) in `configureListFields()`.
~~Perhaps a related issue #5691.~~

## Steps to reproduce

Make entity

```php
class ContestantAdminView
{
    // ...

    public function setPermission(Permission $permission): void
    {
        $this->permission = $permission;
    }
}
```

Configure field as editable in admin service

```php
class TestimonialAdmin extends BaseAdmin
{
    // ...

    protected function configureListFields(ListMapper $list_mapper): void
    {
        $list_mapper
            ->add('permission', 'choice', [
                'label' => 'Permission',
                'editable' => true,
                'choices' => Permission::change(),
                'template' => '@Frontend/Testimonial/admin/list_permission.html.twig',
                'catalogue' => 'messages',
            ])
        ;
    }
```
Go to admin. Change the permission and chose some value

image

## Expected results

The `Permission` object is expected.

## Actual results

Click submit and get 500 error because `string` comes

image

### PR DESCRIPTION
**Pull request by peter-gribanov**
## Subject

Allow use [Symfony Data Transformers](https://symfony.com/doc/current/form/data_transformers.html) in `configureListFields()` like:

```php
class TestimonialAdmin extends BaseAdmin
{
    // ...

    protected function configureListFields(ListMapper $list_mapper): void
    {
        $list_mapper
            ->add('permission', 'choice', [
                'label' => 'Permission',
                'editable' => true,
                'choices' => Permission::change(),
                'template' => '@Frontend/Testimonial/admin/list_permission.html.twig',
                'catalogue' => 'messages',
                'data_transformer' => new PermissionDataTransformer(),
            ]);
    }
}
```

Closes #5693

## Changelog

```markdown
### Fixed
- Allow use Symfony Data Transformers in list fields editable
```

### CODE REVIEW

File: src/Action/SetObjectFieldValueAction.php [hunk 1]
```diff
@@ -164,4 +161,32 @@ public function __invoke(Request $request): JsonResponse
...
+        $data_transformer = $fieldDescription->getOption('data_transformer');
+
+        // Handle date type has setter expect a DateTime object
+        if ('date' === $fieldDescription->getType()) {
+            $data_transformer = new DateTimeToStringTransformer();
+        }
+
+        // Handle boolean type transforming the value into a boolean
+        if ('boolean' === $fieldDescription->getType()) {
+            $data_transformer = new BooleanToStringTransformer('1');
```
Comment (peter-gribanov) [inline src/Action/SetObjectFieldValueAction.php]: I'm not sure that we need a date transformer here. Using a [Symfony BooleanToStringTransformer](https://github.com/symfony/symfony/blob/b3467e641c4ccaddb9bbf7c7c56b918a2f3eb635/src/Symfony/Component/Form/Extension/Core/DataTransformer/BooleanToStringTransformer.php) here may interrupt BC. At least the tests use a [non-string](https://github.com/sonata-project/SonataAdminBundle/pull/5937/files#diff-a0b7a5423dfc2dba3b9e37fd138f3d58R97).

We can use `CallbackTransformer` here, so as not to create a extra transformer.

```php
$data_transformer = new CallbackTransformer(static function ($value) {
    return (string) (int) $value;
}, static function ($value) {
    return filter_var($value, FILTER_VALIDATE_BOOLEAN);
});
```

File: src/Form/DataTransformer/BooleanToStringTransformer.php [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+
+use Symfony\Component\Form\DataTransformerInterface;
+
+/**
+ * This is analog of Symfony\Component\Form\Extension\Core\DataTransformer\BooleanToStringTransformer
+ * which allows you to use non-strings in reverseTransform() method.
+ *
+ * @author Peter Gribanov <info@peter-gribanov.ru>
+ */
+class BooleanToStringTransformer implements DataTransformerInterface
```
Comment (core23) [inline src/Form/DataTransformer/BooleanToStringTransformer.php]:
```suggestion
final class BooleanToStringTransformer implements DataTransformerInterface
```

File: tests/Form/DataTransformer/BooleanToStringTransformerTest.php [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+
+namespace Sonata\AdminBundle\Tests\Form\DataTransformer;
+
+use PHPUnit\Framework\TestCase;
+use Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer;
+
+/**
+ * @author Peter Gribanov <info@peter-gribanov.ru>
+ */
+class BooleanToStringTransformerTest extends TestCase
```
Comment (core23) [inline tests/Form/DataTransformer/BooleanToStringTransformerTest.php]:
```suggestion
final class BooleanToStringTransformerTest extends TestCase
```

**Comment by peter-gribanov** [comment]
Try rebuild

**Comment by peter-gribanov** [comment]
@OskarStark this bug fix works more like a feature. It would be nice to document this feature.

**Comment by peter-gribanov** [comment]
@OskarStark i add example [here](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/action_list.rst) a little bit later.

File: docs/reference/action_list.rst [hunk 4]
```diff
@@ -80,6 +80,14 @@ Here is an example::
...
             ])
 
+            // you can use Symfony Data Transformers to transform value into the data form expected by your
+            // application. For example, in a Value Object
+            ->add('permission', 'choice', [
+                'editable' => true,
+                'choices' => Permission::choices(),
+                'data_transformer' => new PermissionDataTransformer(),
+            ])
+
```
Comment (peter-gribanov) [inline docs/reference/action_list.rst]: @OskarStark will this example be enough?

**Comment by peter-gribanov** [comment]
Try rebuild

File: docs/reference/action_list.rst (hunk 4 above)
Comment (OskarStark) [reply docs/reference/action_list.rst]: I would move this to a dedicated section, show this + `Permission` value object + `PermissionDataTransformer`, WDYT?

File: docs/reference/action_list.rst [hunk 5]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+        $listMapper
+            ->add('moderation_status', 'choice', [
+                'editable' => true,
+                'choices' => ModerationStatus::choices(),
+                'data_transformer' => new ModerationStatusDataTransformer(),
+            ])
+        ;
+    }
+
+
```
Comment (peter-gribanov) [inline docs/reference/action_list.rst]: @OskarStark what do you think of this guide?

File: src/Action/SetObjectFieldValueAction.php [hunk 6]
```diff
@@ -164,4 +161,37 @@ public function __invoke(Request $request): JsonResponse
 
         return new JsonResponse($content, Response::HTTP_OK);
     }
+
+    private function getFieldDataTransformer(
```
Comment (core23) [inline src/Action/SetObjectFieldValueAction.php]: I would prefer a more generic way like a `DataTransformerResolver`. This way we can add new transformers more easily.

Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php]: Do you suggest just putting this method in a separate class?

Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php]: Like this?

```php
final class DataTransformerResolver
{
    private $modelManager;

    public function __construct($modelManager)
    {
        $this->modelManager = $modelManager;
    }

    private function resolve(FieldDescriptionInterface $fieldDescription): ?DataTransformerInterface
    {
        $dataTransformer = $fieldDescription->getOption('data_transformer');

        // allow override transformers for 'date', 'boolean' and 'choice' field types
        if ($dataTransformer instanceof DataTransformerInterface) {
            return $dataTransformer;
        }

        // Handle date type has setter expect a DateTime object
        if ('date' === $fieldDescription->getType()) {
            return new DateTimeToStringTransformer();
        }

        // Handle boolean type transforming the value into a boolean
        if ('boolean' === $fieldDescription->getType()) {
            return new BooleanToStringTransformer('1');
        }

        // Handle entity choice association type, transforming the value into entity
        if ('choice' === $fieldDescription->getType()) {
            $className = $fieldDescription->getOption('class');

            if (null !== $className && $className === $fieldDescription->getTargetEntity()) {
                return new ModelToIdTransformer($this->modelManager, $className);
            }
        }

        return null;
    }
}
```

Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php]: Or maybe you are interested in the option with individual services that are binded into a resolver?

File: src/Action/SetObjectFieldValueAction.php [hunk 7]
```diff
@@ -113,34 +119,25 @@ public function __invoke(Request $request): JsonResponse
...
-        // Handle entity choice association type, transforming the value into entity
-        if ('' !== $value
-            && 'choice' === $fieldDescription->getType()
-            && null !== $fieldDescription->getOption('class')
-            && $fieldDescription->getOption('class') === $fieldDescription->getTargetEntity()
-        ) {
-            $value = $admin->getModelManager()->find($fieldDescription->getOption('class'), $value);
-
-            if (!$value) {
+            if (!$value && 'choice' === $fieldDescription->getType()) {
```
Comment (peter-gribanov) [inline src/Action/SetObjectFieldValueAction.php]: @core23 i am very confused by the tight binding to the field type here. I understand why this is done, but it still looks like a dirty hack.

File: src/Action/SetObjectFieldValueAction.php (hunk 6 above)
Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php]: Or like this?
```php
final class ResolverFieldDataTransformer implements FieldDataTransformer
{
    private $dataTransformers;

    public function __construct(array $dataTransformers)
    {
        $this->dataTransformers = $dataTransformers;
    }

    public function transform($value, FieldDescriptionInterface $fieldDescription)
    {
        $dataTransformer = $fieldDescription->getOption('data_transformer');

        // allow override predefined transformers
        if ($dataTransformer instanceof DataTransformerInterface) {
            return $dataTransformer->reverseTransform($value);
        }

        $type = $fieldDescription->getType();

        if (array_key_exists($type, $this->dataTransformers)) {
            return $this->dataTransformers[$type]->transform($value, $fieldDescription);
        }

        return $value;
    }
}

final class ChoiceFieldDataTransformer implements FieldDataTransformer
{
    private $modelManager;

    public function __construct($modelManager)
    {
        $this->modelManager = $modelManager;
    }

    public function transform($value, FieldDescriptionInterface $fieldDescription)
    {
        $className = $fieldDescription->getOption('class');

        if (null !== $className && $className === $fieldDescription->getTargetEntity()) {
            return (new ModelToIdTransformer($this->modelManager, $className))->reverseTransform($value);
        }

        return $value;
    }
}

$resolver = new ResolverFieldDataTransformer([
    'choice' => new ChoiceFieldDataTransformer($modelManager),
]);
```

File: docs/reference/action_list.rst [hunk 8]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
     values so use the ``inverse`` option if you really cannot find a good enough
     antonym for the name you have.
 
+Symfony Data Transformers
+^^^^^^^^^^^^^^^^^^^^^^^^^
+
+If the entity field has a limited list of values (enumeration), it is convenient to use the Value Object to control
```
Comment (OskarStark) [inline docs/reference/action_list.rst]:
```suggestion
If the entity field has a limited list of values (enumeration), it is convenient to use a value object to control
```

File: docs/reference/action_list.rst [hunk 9]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+the available values. For example, consider the Value Object of moderation status with the following values:
```
Comment (OskarStark) [inline docs/reference/action_list.rst]:
```suggestion
the available values. For example, consider the value object of moderation status with the following values:
```

File: docs/reference/action_list.rst (hunk 5 above)
Comment (OskarStark) [reply docs/reference/action_list.rst]: Great 👍 Thanks!

File: docs/reference/action_list.rst [hunk 10]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+                throw new TransformationFailedException($e->getMessage(), $e->getCode(), $e);
+            }
+        }
+    }
+
+For quick moderation of objects, it is convenient to do this on the page for viewing all objects. But if we just
+indicate the field as editable, then when editing we get in the object a string with the value itself (``awaiting``,
+``approved``, ``rejected``), and not the Value Object (``ModerationStatus``). To solve this problem, you must specify
+the Data Transformer in the ``data_transformer`` field so that it correctly converts the input data into the data
+expected by your object.
```
Comment (OskarStark) [inline docs/reference/action_list.rst]:
```suggestion
expected by your object::
```

File: docs/reference/action_list.rst [hunk 11]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+        }
+
+        public function __toString(): string
+        {
+            return self::choices()[$this->value];
+        }
+    }
+
+To use this Value Object in the _`Symfony Form`: https://symfony.com/doc/current/forms.html component, we need a
+_`Data Transformer`: https://symfony.com/doc/current/form/data_transformers.html .
```
Comment (OskarStark) [inline docs/reference/action_list.rst]:
```suggestion
_`Data Transformer`: https://symfony.com/doc/current/form/data_transformers.html ::
```

File: docs/reference/action_list.rst [hunk 12]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
     values so use the ``inverse`` option if you really cannot find a good enough
     antonym for the name you have.
 
+Symfony Data Transformers
+^^^^^^^^^^^^^^^^^^^^^^^^^
+
+If the entity field has a limited list of values (enumeration), it is convenient to use the Value Object to control
+the available values. For example, consider the Value Object of moderation status with the following values:
+``awaiting``, ``approved``, ``rejected``.
```
Comment (OskarStark) [inline docs/reference/action_list.rst]:
```suggestion
``awaiting``, ``approved``, ``rejected``::
```

File: docs/reference/action_list.rst (hunk 8 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: fixed

File: docs/reference/action_list.rst (hunk 10 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: fixed

File: docs/reference/action_list.rst (hunk 12 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: fixed

File: docs/reference/action_list.rst (hunk 11 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: fixed

File: docs/reference/action_list.rst (hunk 9 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: fixed

File: src/Form/DataTransformerResolver.php [hunk 13]
```diff
@@ -0,0 +1,60 @@
...
+        if ('choice' === $fieldDescription->getType()) {
+            $className = $fieldDescription->getOption('class');
+
+            if (null !== $className && $className === $fieldDescription->getTargetEntity()) {
+                return new ModelToIdTransformer($modelManager, $className);
+            }
+        }
+
+        return null;
+    }
```
Comment (peter-gribanov) [inline src/Form/DataTransformerResolver.php]: @core23 please review `DataTransformerResolver` service

**Comment by VincentLanglet** [comment]
@core23 I think your review is needed :)

File: src/Controller/HelperController.php [hunk 14]
```diff
@@ -63,11 +64,21 @@ class HelperController
...
      * @param ValidatorInterface $validator
      */
-    public function __construct(Environment $twig, Pool $pool, AdminHelper $helper, $validator)
-    {
+    public function __construct(
+        Environment $twig,
+        Pool $pool,
+        AdminHelper $helper,
+        $validator,
+        DataTransformerResolver $resolver
```
Comment (core23) [inline src/Controller/HelperController.php]: This is a BC break

File: src/Form/DataTransformer/BooleanToStringTransformer.php [hunk 15]
```diff
@@ -0,0 +1,42 @@
...
+
+/**
+ * This is analog of Symfony\Component\Form\Extension\Core\DataTransformer\BooleanToStringTransformer
+ * which allows you to use non-strings in reverseTransform() method.
+ *
+ * @author Peter Gribanov <info@peter-gribanov.ru>
+ */
+final class BooleanToStringTransformer implements DataTransformerInterface
+{
+    private $trueValue;
```
Comment (core23) [inline src/Form/DataTransformer/BooleanToStringTransformer.php]: Please add type hints

File: src/Form/DataTransformerResolver.php [hunk 16]
```diff
@@ -0,0 +1,60 @@
...
+use Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer;
+use Sonata\AdminBundle\Form\DataTransformer\ModelToIdTransformer;
+use Sonata\AdminBundle\Model\ModelManagerInterface;
+use Symfony\Component\Form\DataTransformerInterface;
+use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToStringTransformer;
+
+/**
+ * @author Peter Gribanov <info@peter-gribanov.ru>
+ */
+final class DataTransformerResolver
```
Comment (core23) [inline src/Form/DataTransformerResolver.php]: Can you please add some extension points or how could I add a custom transformer to the resolver?

File: src/Controller/HelperController.php (hunk 14 above)
Comment (peter-gribanov) [reply src/Controller/HelperController.php]: Is logical. You [asked](https://github.com/sonata-project/SonataAdminBundle/pull/5937#discussion_r390256695) to create a new service. The new service needs to be injected as a dependency into the constructor. Changing the constructor interface break BC.
If we did not add a new service, then there would be no problems with BC. I can now do without a service and make a separate PR to add service for a major release.

File: src/Form/DataTransformerResolver.php (hunk 16 above)
Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php]: Do you want to add the possibility of customization on a global level, and not on a specific one?

Comment (core23) [reply src/Form/DataTransformerResolver.php]: Yes, you could add global list fields via an admin extension, so you should also have the possibility to add a global mapper

Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php]: I added the opportunity to customize global transformers by constructor and `addCustomGlobalTransformer` method in `DataTransformerResolver`.

File: src/Controller/HelperController.php (hunk 14 above)
Comment (VincentLanglet) [reply src/Controller/HelperController.php:80]: Does
```suggestion
       ?DataTransformerResolver $resolver = null
```
avoid the BC break @core23 @peter-gribanov ?

With something like
```
if (!($resolver instanceof DataTransformerResolver)) {
   @trigger_error(....)
   $resolver = new DataTransformerResolver();
} else {
    $this->resolver = $resolver;
}
```

Comment (peter-gribanov) [reply src/Controller/HelperController.php:80]: @VincentLanglet Looks good. Any idea which message to use in `trigger_error()`?

Comment (VincentLanglet) [reply src/Controller/HelperController.php:80]: WDYT about something like:

Calling HelperController::construct without a DataTransformerResolver as fourth argument is deprecated since 3.x and will be throw an error in 4.0.

Comment (peter-gribanov) [reply src/Controller/HelperController.php]: I add this hook

File: docs/reference/action_list.rst [hunk 17]
```diff
@@ -211,6 +211,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
     values so use the ``inverse`` option if you really cannot find a good enough
     antonym for the name you have.
 
+Symfony Data Transformers
+^^^^^^^^^^^^^^^^^^^^^^^^^
+
+If the entity field has a limited list of values (enumeration), it is convenient to use a value object to control
```
Comment (phansys) [inline docs/reference/action_list.rst:217]: If this feature is compatible with other model managers than ORM, we should use the term "model" instead of "entity".

File: src/Action/SetObjectFieldValueAction.php [hunk 18]
```diff
@@ -40,18 +42,35 @@ final class SetObjectFieldValueAction
...
 
-    public function __construct(Environment $twig, Pool $pool, $validator)
+    /**
+     * @var DataTransformerResolver
+     */
+    private $resolver;
+
+    /**
+     * @param ValidatorInterface      $validator
+     * @param DataTransformerResolver $resolver
```
Comment (phansys) [inline src/Action/SetObjectFieldValueAction.php:52]:
```suggestion
     * @param DataTransformerResolver|null $resolver
```

File: src/Action/SetObjectFieldValueAction.php [hunk 19]
```diff
@@ -40,18 +42,35 @@ final class SetObjectFieldValueAction
...
-                'Argument 3 is an instance of '.\get_class($validator).', expecting an instance of'
-                .' \Symfony\Component\Validator\Validator\ValidatorInterface'
+                'Argument 3 is an instance of '.\get_class($validator).', expecting an instance of '
+                .ValidatorInterface::class
             );
         }
+
+        // NEXT_MAJOR: Move DataTransformerResolver check to method signature
+        if (!($resolver instanceof DataTransformerResolver)) {
+            @trigger_error('Calling '.__METHOD__.' without a '.DataTransformerResolver::class.' as fourth argument is deprecated since 3.x and will be throw an error in 4.0.', E_USER_DEPRECATED);
```
Comment (phansys) [inline src/Action/SetObjectFieldValueAction.php:66]:
```suggestion
            @trigger_error(sprintf(
                'Passing other type than %s in argument 4 to %s() is deprecated since since sonta-project/admin-bundle 3.x and will throw %s exception in 4.0.',
                DataTransformerResolver::class,
                __METHOD__,
                \TypeError::class
            ), E_USER_DEPRECATED);
```

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 20]
```diff
@@ -250,14 +269,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+        $request = new Request([
+            'code' => 'sonata.post.admin',
+            'objectId' => 42,
+            'field' => 'enabled',
+            'value' => 'yes',
+            'context' => 'list',
+        ], [], [], [], [], ['REQUEST_METHOD' => Request::METHOD_POST, 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest']);
+
+        $isOverridden = false;
+        $dataTransformer = new CallbackTransformer(static function ($value) {
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:352]:
```suggestion
        $dataTransformer = new CallbackTransformer(static function ($value): string {
```

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 21]
```diff
@@ -250,14 +269,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+            return (string) (int) $value;
+        }, static function ($value) use (&$isOverridden) {
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:354]:
```suggestion
        }, static function ($value) use (&$isOverridden): bool {
```

File: tests/Form/DataTransformer/BooleanToStringTransformerTest.php [hunk 22]
```diff
@@ -0,0 +1,79 @@
...
+            [true, 'true', 'true'],
+            [true, 'yes', 'yes'],
+            [true, 'on', 'on'],
+        ];
+    }
+
+    /**
+     * @dataProvider provideTransform
+     */
+    public function testTransform($value, ?string $expected, string $trueValue)
```
Comment (phansys) [inline tests/Form/DataTransformer/BooleanToStringTransformerTest.php:39]:
```suggestion
    public function testTransform($value, ?string $expected, string $trueValue): void
```

File: tests/Form/DataTransformer/BooleanToStringTransformerTest.php [hunk 23]
```diff
@@ -0,0 +1,79 @@
...
+            ['foo', false],
+            [new \DateTime(), false],
+            [PHP_INT_MAX, false],
+        ];
+    }
+
+    /**
+     * @dataProvider provideReverseTransform
+     */
+    public function testReverseTransform($value, bool $expected)
```
Comment (phansys) [inline tests/Form/DataTransformer/BooleanToStringTransformerTest.php:73]:
```suggestion
    public function testReverseTransform($value, bool $expected): void
```

File: tests/Form/DataTransformerResolverTest.php [hunk 24]
```diff
@@ -0,0 +1,170 @@
...
+        $this->assertInstanceOf(ModelToIdTransformer::class, $dataTransformer);
+        $this->assertSame($object, $dataTransformer->reverseTransform($newId));
+    }
+
+    /**
+     * @dataProvider provideFieldTypes
+     */
+    public function testAddCustomGlobalTransformer(string $fieldType): void
+    {
+        $customDataTransformer = new CallbackTransformer(static function ($value) {
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:152]:
```suggestion
        $customDataTransformer = new CallbackTransformer(static function ($value): string {
```

File: tests/Form/DataTransformerResolverTest.php [hunk 25]
```diff
@@ -0,0 +1,170 @@
...
+            return (string) (int) $value;
+        }, static function ($value) {
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:154]:
```suggestion
        }, static function ($value): bool {
```

File: src/Action/SetObjectFieldValueAction.php (hunk 19 above)
Comment (VincentLanglet) [reply src/Action/SetObjectFieldValueAction.php:66]: I knew it ! I was sure you would have a better error message than mine 😁

Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php:66]: Deja vu. I will change the message, but explain to me about the coding style. As a contributor, i write code in accordance with the coding style adopted in your project ([1](https://github.com/sonata-project/SonataAdminBundle/blob/895fb26c3eac518757ef2151704d901d3b6d550d/src/Action/SetObjectFieldValueAction.php#L47-L50), [2](https://github.com/sonata-project/SonataAdminBundle/blob/51b8c2ed4eee84c5a2bcde76a150277b0d496783/src/Controller/HelperController.php#L73-L76), [3](https://github.com/sonata-project/SonataAdminBundle/blob/067c35119afafde37a44ca1ca99f52bf13f30b89/src/Admin/AbstractAdmin.php#L1427-L1430)). Why do you suggest using `sprintf()` function instead of concatenating strings?

Comment (VincentLanglet) [reply src/Action/SetObjectFieldValueAction.php:66]: I know this: https://symfony.com/doc/current/contributing/code/standards.html
Exception and error message strings must be concatenated using sprintf;

Old code doesn't always respect the coding style.

Comment (peter-gribanov) [reply src/Action/SetObjectFieldValueAction.php]: @VincentLanglet okay. I understood you.

**Comment by VincentLanglet** [comment]
Please kindly squash your commits together. :)

**Comment by peter-gribanov** [comment]
> Please kindly squash your commits together. :)

I have done it. Tests are broken due to another problem #6084

**Comment by VincentLanglet** [comment]
@peter-gribanov Tests are fixed. If you rebase it should be ok.

**Comment by peter-gribanov** [comment]
@VincentLanglet Thank. Now all is fine :+1:

**Comment by VincentLanglet** [comment]
@core23 @phansys You requested changes, do you have time for a review ? :)

File: docs/reference/action_list.rst [hunk 26]
```diff
@@ -226,6 +226,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+        private function __construct(string $value)
+        {
+            if (!array_key_exists($value, self::choices())) {
+                throw new \DomainException(sprintf('The value "%s" is not a valid moderation status.', $value));
+            }
+
+            $this->value = $value;
+        }
+
+        public static function byValue(string $value): Permission
```
Comment (phansys) [inline docs/reference/action_list.rst:255]: I guess the return declaration is wrong in this example.

File: docs/reference/action_list.rst [hunk 27]
```diff
@@ -226,6 +226,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+                return null;
+            }
+
+            if ($value instanceof ModerationStatus) {
+                return $value;
+            }
+
+            try {
+                return ModerationStatus::byValue($value);
+            } catch (\Exception $e) {
```
Comment (phansys) [inline docs/reference/action_list.rst:312]:
```suggestion
            } catch (\Throwable $e) {
```

File: src/Action/SetObjectFieldValueAction.php [hunk 28]
```diff
@@ -40,18 +42,40 @@ final class SetObjectFieldValueAction
...
-                .' \Symfony\Component\Validator\Validator\ValidatorInterface'
+                'Argument 3 is an instance of '.\get_class($validator).', expecting an instance of '
+                .ValidatorInterface::class
             );
         }
+
+        // NEXT_MAJOR: Move DataTransformerResolver check to method signature
+        if (!($resolver instanceof DataTransformerResolver)) {
+            @trigger_error(sprintf(
+                'Passing other type than %s in argument 4 to %s() is deprecated since sonta-project/admin-bundle 3.x and will throw %s exception in 4.0.',
```
Comment (phansys) [inline src/Action/SetObjectFieldValueAction.php:67]:
```suggestion
                'Passing other type than %s in argument 4 to %s() is deprecated since sonata-project/admin-bundle 3.x and will throw %s exception in 4.0.',
```

File: src/Controller/HelperController.php [hunk 29]
```diff
@@ -64,22 +65,40 @@ class HelperController
...
-                .' \Symfony\Component\Validator\Validator\ValidatorInterface'
+                'Argument 4 is an instance of '.\get_class($validator).', expecting an instance of '
+                .ValidatorInterface::class
             );
         }
 
+        // NEXT_MAJOR: Move DataTransformerResolver check to method signature
+        if (!($resolver instanceof DataTransformerResolver)) {
+            @trigger_error(sprintf(
+                'Passing other type than %s in argument 4 to %s() is deprecated since sonta-project/admin-bundle 3.x and will throw %s exception in 4.0.',
```
Comment (phansys) [inline src/Controller/HelperController.php:89]:
```suggestion
                'Passing other type than %s in argument 4 to %s() is deprecated since sonata-project/admin-bundle 3.x and will throw %s exception in 4.0.',
```

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 30]
```diff
@@ -344,14 +367,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
         $fieldDescription->getOption('editable')->willReturn(true);
         $fieldDescription->getOption('multiple')->willReturn(true);
         $fieldDescription->getAdmin()->willReturn($this->admin->reveal());
-        $fieldDescription->getType()->willReturn('boolean');
-        $fieldDescription->getTemplate()->willReturn('field_template');
+        $fieldDescription->getType()->willReturn(null);
+        $fieldDescription->getTemplate()->willReturn(false);
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:371]: Could we return `null` instead?

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 31]
```diff
@@ -344,14 +367,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+        $object = new Foo();
+        $request = new Request([
+            'code' => 'sonata.post.admin',
+            'objectId' => 42,
+            'field' => 'enabled',
+            'value' => 'yes',
+            'context' => 'list',
+        ], [], [], [], [], ['REQUEST_METHOD' => Request::METHOD_POST, 'HTTP_X_REQUESTED_WITH' => 'XMLHttpRequest']);
+
+        $data_transformer = new CallbackTransformer(static function ($value) {
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:394]:
```suggestion
        $dataTransformer = new CallbackTransformer(static function ($value): string {
```

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 32]
```diff
@@ -344,14 +367,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+            return (string) (int) $value;
+        }, static function ($value) {
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:396]:
```suggestion
        }, static function ($value): bool {
```

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 33]
```diff
@@ -344,14 +367,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+        $this->twig->addExtension(new SonataAdminExtension(
+            $pool->reveal(),
+            null,
+            $translator->reveal(),
+            $container->reveal()
+        ));
+        $fieldDescription->getOption('editable')->willReturn(true);
+        $fieldDescription->getAdmin()->willReturn($this->admin->reveal());
+        $fieldDescription->getType()->willReturn(null);
+        $fieldDescription->getTemplate()->willReturn(false);
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:426]: Could we return `null`?

File: tests/Action/SetObjectFieldValueActionTest.php [hunk 34]
```diff
@@ -344,14 +367,130 @@ public function testSetObjectFieldEditableMultipleValue(): void
...
+        $fieldDescription->getValue(Argument::cetera())->willReturn('some value');
+        $fieldDescription->getOption('data_transformer')->willReturn($data_transformer);
```
Comment (phansys) [inline tests/Action/SetObjectFieldValueActionTest.php:428]:
```suggestion
        $fieldDescription->getOption('data_transformer')->willReturn($dataTransformer);
```

File: tests/Form/DataTransformerResolverTest.php [hunk 35]
```diff
@@ -0,0 +1,170 @@
...
+            ['choice'],
+        ];
+    }
+
+    /**
+     * @dataProvider provideFieldTypes
+     */
+    public function testResolveCustomDataTransformer(string $fieldType): void
+    {
+        $customDataTransformer = new CallbackTransformer(static function ($value) {
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:74]:
```suggestion
        $customDataTransformer = new CallbackTransformer(static function ($value): string {
```

File: tests/Form/DataTransformerResolverTest.php [hunk 36]
```diff
@@ -0,0 +1,170 @@
...
+            return (string) (int) $value;
+        }, static function ($value) {
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:76]:
```suggestion
        }, static function ($value): bool {
```

File: docs/reference/action_list.rst (hunk 26 above)
Comment (peter-gribanov) [reply docs/reference/action_list.rst]: Sorry for this. Fixed

File: tests/Action/SetObjectFieldValueActionTest.php (hunk 30 above)
Comment (peter-gribanov) [reply tests/Action/SetObjectFieldValueActionTest.php]: I restore origin value but yes, `null` can be returned in `getTemplate()` method as far as i can tell.

File: tests/Action/SetObjectFieldValueActionTest.php (hunk 33 above)
Comment (peter-gribanov) [reply tests/Action/SetObjectFieldValueActionTest.php]: Using `null` as the return value for the `getTemplate()` method does not break the tests.

File: docs/reference/action_list.rst [hunk 37]
```diff
@@ -226,6 +226,115 @@ to more field types, see `SonataDoctrineORMAdminBundle Documentation`_.
...
+        public function transform($value): ?string
+        {
+            $status = $this->reverseTransform($value);
+
+            return $status instanceof ModerationStatus ? $status->value() : null;
+        }
+
+        public function reverseTransform($value): ?ModerationStatus
+        {
+            if ($value === null || $value === '') {
```
Comment (phansys) [inline docs/reference/action_list.rst:302]: We're currently using `@Symfony` as part of our CS rules, which implies the `yoda_style` rule:
```suggestion
            if (null === $value || '' === $value) {
```

Comment (peter-gribanov) [reply docs/reference/action_list.rst:302]: @greg0ire recently said that the Yoda conditions is not very good and maybe you should give it up. https://github.com/sonata-project/SonataAdminBundle/pull/6062#discussion_r416909700
Do you still want to use Yoda conditions?

Comment (wbloszyk) [reply docs/reference/action_list.rst:302]: At first check 
```php
if ($value instanceof ModerationStatus) {
    return $value;
}
```
Then value must be string.
```suggestion
            if (0 === strlen($value) {
```
You can also move it to try{} to avoid warning about wrong type.

Comment (VincentLanglet) [reply docs/reference/action_list.rst:302]: > @greg0ire recently said that the Yoda conditions is not very good and maybe you should give it up. [#6062 (comment)](https://github.com/sonata-project/SonataAdminBundle/pull/6062#discussion_r416909700)
> Do you still want to use Yoda conditions?

It's still the coding standard ATM. We won't drop it without some discussion and updating all the base code. So for now the doc should be similar to the base code IMHO.

Comment (peter-gribanov) [reply docs/reference/action_list.rst]: Ok. I change it

File: src/Form/DataTransformerResolver.php [hunk 38]
```diff
@@ -0,0 +1,92 @@
...
+        $fieldType = (string) $fieldDescription->getType();
+
+        // allow override predefined transformers on a global level
+        if (\array_key_exists($fieldType, $this->globalCustomTransformers)) {
+            return $this->globalCustomTransformers[$fieldType];
+        }
+
+        // Handle date type has setter expect a DateTime object
+        if ('date' === $fieldDescription->getType()) {
+            return new DateTimeToStringTransformer(null, null, 'Y-m-d');
```
Comment (core23) [inline src/Form/DataTransformerResolver.php:68]: Can you register this transformer as services, so you do not create new instances every time.

Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php]: Symfony has the principle that Data Transformers are initialized each time they are used. Data Transformers are not registered as services.
https://symfony.com/doc/current/form/data_transformers.html

I add lazy-load the predefined data transformers.

**Comment by peter-gribanov** [comment]
rebuild

**Comment by VincentLanglet** [comment]
I think it's RTM @peter-gribanov isn't it ?

Can you take a new look @phansys @core23 ?

File: src/Form/DataTransformerResolver.php [hunk 39]
```diff
@@ -0,0 +1,98 @@
...
+        $fieldType = (string) $fieldDescription->getType();
+
+        // allow override predefined transformers on a global level
+        if (\array_key_exists($fieldType, $this->globalCustomTransformers)) {
+            return $this->globalCustomTransformers[$fieldType];
+        }
+
+        // Handle date type has setter expect a DateTime object
+        if ('date' === $fieldType) {
+            $this->globalCustomTransformers[$fieldType] = new DateTimeToStringTransformer(null, null, 'Y-m-d');
```
Comment (core23) [inline src/Form/DataTransformerResolver.php:68]: Is there a reason why we need a new instance every time a date field is rendered?

File: src/Form/DataTransformerResolver.php [hunk 40]
```diff
@@ -0,0 +1,98 @@
...
+use Sonata\AdminBundle\Form\DataTransformer\BooleanToStringTransformer;
+use Sonata\AdminBundle\Form\DataTransformer\ModelToIdTransformer;
+use Sonata\AdminBundle\Model\ModelManagerInterface;
+use Symfony\Component\Form\DataTransformerInterface;
+use Symfony\Component\Form\Extension\Core\DataTransformer\DateTimeToStringTransformer;
+
+/**
+ * @author Peter Gribanov <info@peter-gribanov.ru>
+ */
+final class DataTransformerResolver
```
Comment (core23) [inline src/Form/DataTransformerResolver.php:26]: This class is final, it would be good if there is at least an interface which you can extend

File: src/Form/DataTransformerResolver.php (hunk 39 above)
Comment (core23) [reply src/Form/DataTransformerResolver.php:68]: (same for the other transformers)

**Review by core23 — DISMISSED** [review]

File: src/Form/DataTransformerResolver.php (hunk 39 above)
Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php:68]: Here we are talking about solving problem #5693. As part of this problem, a translator cannot be created more than once. In addition, we are doing lazy loading ([as i already said](https://github.com/sonata-project/SonataAdminBundle/pull/5937#discussion_r428080908)) and the transformer cannot be initialized more than once.

Or are you talking about [these lines](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Action/SetObjectFieldValueAction.php#L116-L141) that are moved to where they should be, in transformers?

File: src/Form/DataTransformerResolver.php (hunk 40 above)
Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php]: I do not consider this necessary, since the service should not be redefined. The service has everything you need to expand. But i added interface.

File: src/Form/DataTransformerResolver.php (hunk 39 above)
Comment (core23) [reply src/Form/DataTransformerResolver.php:68]: > Here we are talking about solving problem #5693. As part of this problem, a translator cannot be created more than once. In addition, we are doing lazy loading (as i already said) and the transformer cannot be initialized more than once.

Also the transformer is only created once, creating new instances is kind of a anti pattern. Code becomes harder to maintain and unit testing is nearly impossible for this fragments. If you overuse this transformer you will end up with multiple instances of the same class that won't differ in any case.

To solve this issue, you could define each transformer as a symfony service and inject it via `addCustomGlobalTransformer`. You could still use lazy bindings for symfony services. This will also solve the testability of this class.

Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php:68]: > Also the transformer is only created once, creating new instances is kind of a anti pattern. Code becomes harder to maintain and unit testing is nearly impossible for this fragments. If you overuse this transformer you will end up with multiple instances of the same class that won't differ in any case.

@core23 maybe i missed something. How long have Creational design patterns been considered antipatterns?

File: src/Action/SetObjectFieldValueAction.php [hunk 41]
```diff
@@ -40,18 +43,40 @@ final class SetObjectFieldValueAction
...
             throw new \InvalidArgumentException(
-                'Argument 3 is an instance of '.\get_class($validator).', expecting an instance of'
-                .' \Symfony\Component\Validator\Validator\ValidatorInterface'
+                'Argument 3 is an instance of '.\get_class($validator).', expecting an instance of '
+                .ValidatorInterface::class
             );
         }
+
+        // NEXT_MAJOR: Move DataTransformerResolver check to method signature
+        if (!($resolver instanceof DataTransformerResolverInterface)) {
```
Comment (phansys) [inline src/Action/SetObjectFieldValueAction.php:66]:
```suggestion
        if (!$resolver instanceof DataTransformerResolverInterface) {
```

File: src/Controller/HelperController.php [hunk 42]
```diff
@@ -64,22 +66,40 @@ class HelperController
...
             throw new \InvalidArgumentException(
-                'Argument 4 is an instance of '.\get_class($validator).', expecting an instance of'
-                .' \Symfony\Component\Validator\Validator\ValidatorInterface'
+                'Argument 4 is an instance of '.\get_class($validator).', expecting an instance of '
+                .ValidatorInterface::class
             );
         }
 
+        // NEXT_MAJOR: Move DataTransformerResolver check to method signature
+        if (!($resolver instanceof DataTransformerResolverInterface)) {
```
Comment (phansys) [inline src/Controller/HelperController.php:88]:
```suggestion
        if (!$resolver instanceof DataTransformerResolverInterface) {
```

**Comment by peter-gribanov** [comment]
rebuild

File: src/Form/DataTransformerResolver.php (hunk 39 above)
Comment (core23) [reply src/Form/DataTransformerResolver.php:69]: Sorry, I think I misunderstood this class when reviewing it. It is okay to create new instances of a type as long as you use a factory for it. This class can be considered as a factory.

But I would still prefer services over static creation. This will reduce memory footprint and increase testability.

Comment (VincentLanglet) [reply src/Form/DataTransformerResolver.php:69]: Hi, I'm not sure to understand. Do you still request changes or is this PR ok for you @core23 ?

Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php:69]: After merging #6144, #6167 PRs, i will need to modify this PR. As a result, as a service it will be possible to register only `BooleanToStringTransformer`.

**Comment by VincentLanglet** [comment]
Tests are failing.

**Comment by peter-gribanov** [comment]
@VincentLanglet tests fixed

File: src/Form/DataTransformerResolver.php (hunk 39 above)
Comment (peter-gribanov) [reply src/Form/DataTransformerResolver.php]: I register a `BooleanToStringTransformer` as a service.

**Comment by VincentLanglet** [comment]
Please review @sonata-project/contributors.

@greg0ire, we have no news of @core23 on this PR, could you dismiss the review ?

@peter-gribanov There is an issue with the `3.x` in the doc =/

**Comment by peter-gribanov** [comment]
> There is an issue with the 3.x in the doc =/

@VincentLanglet This is not my issue. This part of the documentation is covered in #6200 and #6231 PRs. See the [latest build](https://github.com/sonata-project/SonataAdminBundle/runs/912942612) of 3.x branch.

**Comment by VincentLanglet** [comment]
Indeed ! We need to fix it in dev-kit to avoid this kind of PR
https://github.com/sonata-project/SonataAdminBundle/pull/6231/files

**Comment by peter-gribanov** [comment]
@sonata-project/contributors have any news?

**Comment by VincentLanglet** [comment]
> @sonata-project/contributors have any news?

Can you fix the phpstan check ?

@sonata-project/contributors Please review.

**Comment by peter-gribanov** [comment]
> Can you fix the phpstan check ?

@VincentLanglet problem not on my side.
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Guesser/TypeGuesserChain.php#L63

**Comment by VincentLanglet** [comment]
I fixed it ; you just have to rebase now

https://github.com/sonata-project/SonataAdminBundle/pull/6356

**Review by VincentLanglet — APPROVED** [review]

**Review by wbloszyk — DISMISSED** [review]
Awesome work.

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Please review @core23. :)

(Or can you dismiss the review @greg0ire if we get no response after some days ?)

File: tests/Form/DataTransformerResolverTest.php [hunk 43]
```diff
@@ -0,0 +1,221 @@
...
+
+        $value = '2020-12-12';
+        $defaultTimezone = new \DateTimeZone(date_default_timezone_get());
+        $expectedDate = new \DateTime($value, $expectedTimezone);
+        $expectedDate->setTimezone($defaultTimezone);
+
+        $resultDate = $dataTransformer->reverseTransform($value);
+
+        $this->assertInstanceOf(\DateTime::class, $resultDate);
+        $this->assertSame($expectedDate->format('Y-m-d'), $resultDate->format('Y-m-d'));
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:123]:
```suggestion
        $this->assertSame($expectedDate->format(\DateTimeInterface::ATOM), $resultDate->format(\DateTimeInterface::ATOM));
```

File: tests/Form/DataTransformerResolverTest.php [hunk 44]
```diff
@@ -0,0 +1,221 @@
...
+
+        $this->resolver->addCustomGlobalTransformer($fieldType, $customDataTransformer);
+
+        $dataTransformer = $this->resolve();
+
+        $this->assertInstanceOf(DataTransformerInterface::class, $dataTransformer);
+        $this->assertSame($customDataTransformer, $dataTransformer);
+    }
+
+    protected function resolve(): ?DataTransformerInterface
```
Comment (phansys) [inline tests/Form/DataTransformerResolverTest.php:217]: Can't this method be private?

**Review by phansys — CHANGES_REQUESTED** [review]

File: tests/Form/DataTransformerResolverTest.php (hunk 43 above)
Comment (peter-gribanov) [reply tests/Form/DataTransformerResolverTest.php:123]: This is unnecessary since we are comparing a date without a time.

File: tests/Form/DataTransformerResolverTest.php (hunk 44 above)
Comment (peter-gribanov) [reply tests/Form/DataTransformerResolverTest.php:217]: Yes. Must be private. Now i don't remember why i did this.

File: tests/Form/DataTransformerResolverTest.php [hunk 45]
```diff
@@ -0,0 +1,221 @@
...
+        $this->assertInstanceOf(DateTimeToStringTransformer::class, $dataTransformer);
+
+        $value = '2020-12-12';
+        $defaultTimezone = new \DateTimeZone(date_default_timezone_get());
+        $expectedDate = new \DateTime($value, $expectedTimezone);
+        $expectedDate->setTimezone($defaultTimezone);
+
+        $resultDate = $dataTransformer->reverseTransform($value);
+
+        $this->assertInstanceOf(\DateTime::class, $resultDate);
```
Comment (wbloszyk) [inline tests/Form/DataTransformerResolverTest.php:122]:
```suggestion
        $this->assertInstanceOf(\DateTimeInterface::class, $resultDate);
```

File: tests/Form/DataTransformerResolverTest.php [hunk 46]
```diff
@@ -0,0 +1,221 @@
...
+        $this->assertSame($expectedDate->format(\DateTime::ATOM), $resultDate->format(\DateTime::ATOM));
```
Comment (wbloszyk) [inline tests/Form/DataTransformerResolverTest.php:123]:
```suggestion
        $this->assertSame($expectedDate->format(\DateTimeInterface::ATOM), $resultDate->format(\DateTime::ATOM));
```

**Review by wbloszyk — APPROVED** [review]
You can use `DateTimeInterface`, anyway IMO we can accept this.

File: tests/Form/DataTransformerResolverTest.php (hunk 45 above)
Comment (peter-gribanov) [reply tests/Form/DataTransformerResolverTest.php:122]: Now the transformer always returns the `\DateTime`. If we expect the interface in tests, we may not notice how we break BC by replacing `\DateTime` with `\DateTimeImmutable` in the transformer.

**Review by OskarStark — APPROVED** [review]

**Comment by OskarStark** [comment]
@core23 @phansys @jordisala1991 can you please give us a final review? Thanks

**Review by phansys — APPROVED** [review]

File: tests/Form/DataTransformerResolverTest.php (hunk 43 above)
Comment (phansys) [reply tests/Form/DataTransformerResolverTest.php]: >we are comparing a date without a time.

That's the point. Using `\DateTimeInterface::ATOM` we can be sure there is no time information in this object.

**Comment by VincentLanglet** [comment]
Thanks !
