### PR TITLE
Don't show admin blocks in global search results when no filters are set for global_search

### LINKED ISSUE #4574: Cannot remove Admin from global search
## Subject

I want to remove some admins from the global search (right now I'm doing this by overriding the Core:search.html.twig template)

in my opinion to following should work:

* set all filters to global_search => false
* have an option / tag in admin to disable display in global search

## Steps to reproduce

add 'global_search' => false to all filters of admin

## Expected results

admin should not be included in the search results.

## Actual results

admin is shown but does not have any results

### PR DESCRIPTION
**Pull request by TimoBakx**
I am targeting this branch, because it is BC.

Closes #4574

## Changelog

```markdown
### Fixed
- Admins without global search filters will no longer be shown in the global search.
```

## Subject
It was not possible to remove an Admin from the global search blocks.

The global search would list all the Admins. An Admin was shown with "no results found" if that Admin had no filters specified, no filters of that Admin had `'global_search' => true`, or no results were found within that Admin.

After this change, the Admin block will not be shown in the global search results if there are no filters specified or all specified filters have `'global_search' => false`.
The Admin block is still shown, however, if there are filters for global search, but no results were found.

### CODE REVIEW

File: src/Block/AdminSearchBlockService.php [hunk 1]
```diff
@@ -68,6 +68,10 @@ public function execute(BlockContextInterface $blockContext, Response $response
             $blockContext->getSetting('per_page')
         );
 
+        if (false === $pager) {
+            return null === $response ? new Response() : $response;
```
Comment (greg0ire) [inline src/Block/AdminSearchBlockService.php]: Should the status code be set to 204? Or maybe 205 (should some HTML block be emptied)?

Comment (TimoBakx) [reply src/Block/AdminSearchBlockService.php]: From what I can see, there's an empty response going in. And the status code of the returned response isn't used. Only the caching stuff (TTL, age, date) is used.

Comment (greg0ire) [reply src/Block/AdminSearchBlockService.php]: It's not about being used, it's about expressing the fact that it is normal to get an empty response. People might wonder if this is normal or a bug.

Comment (TimoBakx) [reply src/Block/AdminSearchBlockService.php]: Oh, wait. The status code is checked to see if the block is cacheable against codes 200, 203, 300, 301, 302, 404, 410.
Then using 204 or 205 will make the block uncacheable.

Comment (greg0ire) [reply src/Block/AdminSearchBlockService.php]: Should it really be cached though? 204 and 205 should be considered cacheable by default, see https://httpstatuses.com/204 and https://httpstatuses.com/205

**Comment by TimoBakx** [comment]
@greg0ire I added your suggestions.

File: src/Block/AdminSearchBlockService.php [hunk 2]
```diff
@@ -68,6 +68,14 @@ public function execute(BlockContextInterface $blockContext, Response $response
             $blockContext->getSetting('per_page')
         );
 
+        if (false === $pager) {
+            if (null === $response) {
+                $response = new Response();
+            }
+
+            return $response->setContent('')->setStatusCode(204);
```
Comment (kunicmarko20) [inline src/Block/AdminSearchBlockService.php]: you can just do `new Response('', 204)`

Comment (kunicmarko20) [reply src/Block/AdminSearchBlockService.php]: ah, but this is set for every `$resposne` where the `$pager` is false? So we could have a $response but no $pager?

Comment (TimoBakx) [reply src/Block/AdminSearchBlockService.php]: Yeah, a $response might be given through the parameter of the function. If it isn't (when it's null), one is created afterwards. Hence the extra checks.

Comment (kunicmarko20) [reply src/Block/AdminSearchBlockService.php]: then as you wrote it should be ok.

File: src/Block/AdminSearchBlockService.php [hunk 3]
```diff
@@ -68,6 +68,14 @@ public function execute(BlockContextInterface $blockContext, Response $response
             $blockContext->getSetting('per_page')
         );
 
+        if (false === $pager) {
+            if (null === $response) {
+                $response = new Response();
```
Comment (jordisala1991) [inline src/Block/AdminSearchBlockService.php]: $response = $response ?: new Response(); ?

Comment (kunicmarko20) [reply src/Block/AdminSearchBlockService.php]: Check the line under, he needs to set the status code.

Comment (jordisala1991) [reply src/Block/AdminSearchBlockService.php]: Yes, I am not saying that you return it directly

File: src/Block/AdminSearchBlockService.php (hunk 2 above)
Comment (jordisala1991) [reply src/Block/AdminSearchBlockService.php]: If you are setting content and status code, why are you reusing the request, what could come with the original one?  Cookies? Custom headers?

Comment (TimoBakx) [reply src/Block/AdminSearchBlockService.php]: The TTL is set from a BlockContext in BlockRenderer::render().

**Comment by TimoBakx** [comment]
@jordisala1991, @kunicmarko20 I added your suggestions.

**Comment by jordisala1991** [comment]
Thank you @TimoBakx
