### PR TITLE
Handle field without mappedBy

### LINKED ISSUE #6218: Bug AdminType field: Argument 3 passed to Sonata\AdminBundle\Manipulator\ObjectManipulator::callSetter() must be of the type string, null given
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'

sonata-project/admin-bundle              3.72.0 3.72.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.20.0 3.20.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.20.0 3.20.0 Symfony SonataCoreBundle (abandoned)
Package sonata-project/core-bundle is abandoned, you should avoid using it. No replacement was suggested.
sonata-project/doctrine-extensions       1.7.0  1.8.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.21.0 3.21.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.3.0  2.3.0  Lightweight Exporter library
sonata-project/form-extensions           0.1.2  1.5.0  Symfony form extensions
sonata-project/intl-bundle               2.6.0  2.7.0  Symfony SonataIntlBundle
sonata-project/twig-extensions           0.1.1  1.3.1  Sonata twig extensions
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                      v4.4.10 v4.4.10 Symfony Asset Component
symfony/browser-kit                v4.4.10 v4.4.10 Symfony BrowserKit Component
symfony/cache                      v4.4.10 v4.4.10 Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v2.1.3  v2.1.3  Generic abstractions related to caching
symfony/config                     v4.4.10 v4.4.10 Symfony Config Component
symfony/console                    v4.4.10 v4.4.10 Symfony Console Component
symfony/css-selector               v4.4.10 v4.4.10 Symfony CssSelector Component
symfony/debug                      v4.4.10 v4.4.10 Symfony Debug Component
symfony/debug-bundle               v4.4.10 v4.4.10 Symfony DebugBundle
symfony/dependency-injection       v4.4.10 v4.4.10 Symfony DependencyInjection Component
symfony/deprecation-contracts      v2.1.3  v2.1.3  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v4.4.10 v4.4.10 Symfony Doctrine Bridge
symfony/dom-crawler                v4.4.10 v4.4.10 Symfony DomCrawler Component
symfony/dotenv                     v4.4.10 v4.4.10 Registers environment variables from a .env file
symfony/error-handler              v4.4.10 v4.4.10 Symfony ErrorHandler Component
symfony/event-dispatcher           v4.4.10 v4.4.10 Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.9  v2.1.3  Generic abstractions related to dispatching event
symfony/expression-language        v4.4.10 v4.4.10 Symfony ExpressionLanguage Component
symfony/filesystem                 v4.4.10 v4.4.10 Symfony Filesystem Component
symfony/finder                     v4.4.10 v4.4.10 Symfony Finder Component
symfony/flex                       v1.9.1  v1.9.1  Composer plugin for Symfony
symfony/form                       v4.4.10 v4.4.10 Symfony Form Component
symfony/framework-bundle           v4.4.10 v4.4.10 Symfony FrameworkBundle
symfony/http-client                v4.4.10 v4.4.10 Symfony HttpClient component
symfony/http-client-contracts      v2.1.3  v2.1.3  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.4.10 v4.4.10 Symfony HttpFoundation Component
symfony/http-kernel                v4.4.10 v4.4.10 Symfony HttpKernel Component
symfony/inflector                  v4.4.10 v4.4.10 Symfony Inflector Component
symfony/intl                       v4.4.10 v4.4.10 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mailer                     v4.4.10 v4.4.10 Symfony Mailer Component
symfony/maker-bundle               v1.20.0 v1.20.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v4.4.10 v4.4.10 A library to manipulate MIME messages
symfony/monolog-bridge             v4.4.10 v4.4.10 Symfony Monolog Bridge
symfony/monolog-bundle             v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver           v4.4.10 v4.4.10 Symfony OptionsResolver Component
symfony/phpunit-bridge             v4.4.10 v5.1.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu              v1.18.0 v1.18.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-grapheme     v1.18.0 v1.18.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.18.0 v1.18.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.18.0 v1.18.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.18.0 v1.18.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.18.0 v1.18.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.18.0 v1.18.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.18.0 v1.18.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.18.0 v1.18.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/process                    v4.4.10 v4.4.10 Symfony Process Component
symfony/property-access            v4.4.10 v4.4.10 Symfony PropertyAccess Component
symfony/property-info              v4.4.10 v4.4.10 Symfony Property Info Component
symfony/routing                    v4.4.10 v4.4.10 Symfony Routing Component
symfony/security-acl               v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.4.10 v4.4.10 Symfony SecurityBundle
symfony/security-core              v4.4.10 v4.4.10 Symfony Security Component - Core Library
symfony/security-csrf              v4.4.10 v4.4.10 Symfony Security Component - CSRF Library
symfony/security-guard             v4.4.10 v4.4.10 Symfony Security Component - Guard
symfony/security-http              v4.4.10 v4.4.10 Symfony Security Component - HTTP Integration
symfony/serializer                 v4.4.10 v4.4.10 Symfony Serializer Component
symfony/service-contracts          v2.1.3  v2.1.3  Generic abstractions related to writing services
symfony/stopwatch                  v4.4.10 v4.4.10 Symfony Stopwatch Component
symfony/string                     v5.1.2  v5.1.2  Symfony String component
symfony/swiftmailer-bundle         v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating                 v4.4.10 v4.4.10 Symfony Templating Component
symfony/translation                v4.4.10 v4.4.10 Symfony Translation Component
symfony/translation-contracts      v2.1.3  v2.1.3  Generic abstractions related to translation
symfony/twig-bridge                v4.4.10 v4.4.10 Symfony Twig Bridge
symfony/twig-bundle                v4.4.10 v4.4.10 Symfony TwigBundle
symfony/validator                  v4.4.10 v4.4.10 Symfony Validator Component
symfony/var-dumper                 v4.4.10 v4.4.10 Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.4.10 v4.4.10 A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.4.10 v4.4.10 Symfony WebLink Component
symfony/web-profiler-bundle        v4.4.10 v4.4.10 Symfony WebProfilerBundle
symfony/yaml                       v4.4.10 v4.4.10 Symfony Yaml Component

```

#### PHP version

```
$ php -v
PHP 7.2.31 (cli) (built: May 15 2020 14:32:37) ( NTS ) 
Docker image
```

## Subject
sonata-project/admin-bundle:3.72

Error in edit entity page:

Argument 3 passed to Sonata\AdminBundle\Manipulator\ObjectManipulator::callSetter() must be of the type string, null given, called in /var/www/site/vendor/sonata-project/admin-bundle/src/Manipulator/ObjectManipulator.php on line 63

sonata-project/admin-bundle:3.71 and low - ok, no problem

## Steps to reproduce

Entities:
```
class User{
     /**
     * Many-To-One, Unidirectional . image_id - nullable
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="image_id", referencedColumnName="id")
     */
    protected $image;
} 

class UserAdmin{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('image', AdminType::class);
    }
} 
```
1) Open create User Entity page - ok 
2) Open edit User Entity page (user have image) - ok
3) Open edit User Entity page (user have not image) - Argument 3 passed to Sonata\AdminBundle\Manipulator\ObjectManipulator::callSetter() must be of the type string, null given, called in /var/www/site/vendor/sonata-project/admin-bundle/src/Manipulator/ObjectManipulator.php on line 63

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because BC.

Closes #6218.

## Changelog

```markdown
### Fixed
- Allow to use AdminType with unidirectional field.
```

### CODE REVIEW

File: tests/Manipulator/ObjectManipulatorTest.php [hunk 1]
```diff
@@ -88,6 +88,14 @@ public function testSetObject(): void
         ObjectManipulator::setObject($instance, $object, $fieldDescription);
     }
 
+    public function testSetObjectWithoutMappedBy(): void
+    {
+        $fieldDescription = $this->createMock(FieldDescriptionInterface::class);
+        $fieldDescription->expects($this->once())->method('getAssociationMapping')->willReturn(['mappedBy' => null]);
+
+        ObjectManipulator::setObject(new \stdClass(), new \stdClass(), $fieldDescription);
```
Comment (phansys) [inline tests/Manipulator/ObjectManipulatorTest.php:96]: Tests above perform expectations about the methods present in the object passed as argument 1 to `ObjectManipulator::setObject()`. Shouldn't we do the same here?

Comment (VincentLanglet) [reply tests/Manipulator/ObjectManipulatorTest.php:96]: Here the method is not called. (And doesn't exist)

Comment (phansys) [reply tests/Manipulator/ObjectManipulatorTest.php:96]: Fine. I was thinking about something like
```php
$instance->expects($this->never())->method('theMethod')->with($object);
```
but since I haven't enough context, I trust your decision if you say it is not required.

**Comment by jordisala1991** [comment]
Thank you @VincentLanglet

**Comment by haivala** [comment]
I think because of this there should be release 3.72.1

**Comment by VincentLanglet** [comment]
> I think because of this there should be release 3.72.1

I'll make a release today. But it will be 3.73

**Comment by cjgordon** [comment]
Hi @VincentLanglet 

I believe this breaks admins using doctrine MongoDB and embedded collections as there is no mappedBy attribute for these mappings. 

Example mapping:
`
    /**
     * @MongoDB\EmbedMany(targetDocument="Comment")
     */
    private $comments;
`

Break happens on: ObjectManipulator.php line 56 with error message: 'Notice: Undefined index: mappedBy'

I believe you just need to add a check to ensure that if the mappedBy property is not present that instance is returned. I have test this myself and it has resolved the issue.
`
       $mappedBy = null;
        if (isset($parentFieldDescription->getAssociationMapping()['mappedBy'])) {
            $mappedBy = $parentFieldDescription->getAssociationMapping()['mappedBy'];
        }
        if (null === $mappedBy) {
            return $instance;
        }
`
Cheers
Chris

**Comment by VincentLanglet** [comment]
HI @cjgordon. 

```
if (!isset($parentFieldDescription->getAssociationMapping()['mappedBy'])) {
    return $instance;
}

$mappedBy = $parentFieldDescription->getAssociationMapping()['mappedBy'];
```
Could be a better way to write this, since `isset(null)` is false.

As a quick fix, do you want to make the PR ?

Also could you dump the `$parentFieldDescription->getAssociationMapping()` value ? To know if there is something similar to `mappedBy` in order to provide the same feature to mongoDB than I provided to doctrine orm.

**Comment by cjgordon** [comment]
@VincentLanglet I'll do a PR for this on the weekend.

**Comment by VincentLanglet** [comment]
I done this @cjgordon https://github.com/sonata-project/SonataAdminBundle/pull/6297

**Comment by cjgordon** [comment]
Excellent thank you. Apologies for being slack on this.
