### PR TITLE
Fix filter with default values array

### LINKED ISSUE #7547: Multiple choice field with predefined default values
#### Sonata packages

```
sonata-project/admin-bundle              3.105.3 4.0.1  The missing Symfony Admin Generator
sonata-project/block-bundle              3.21.0  4.7.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1   2.2.0  Cache library
sonata-project/doctrine-extensions       1.13.1  1.14.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.35.0  4.0.0  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.7.0   2.8.0  Lightweight Exporter library
sonata-project/form-extensions           1.12.0  1.12.0 Symfony form extensions
sonata-project/twig-extensions           1.7.0   1.9.0  Sonata twig extensions
```

#### Symfony packages

```
symfony/contracts                v1.1.10 v2.4.0  A set of abstractions extracted out of the Symfony components
symfony/deprecation-contracts    v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/monolog-bundle           v3.6.0  v3.7.0  Symfony MonologBundle
symfony/phpunit-bridge           v5.3.3  v5.3.8  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype           v1.23.0 v1.23.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv           v1.23.0 v1.23.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme   v1.23.1 v1.23.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu        v1.23.0 v1.23.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn        v1.23.0 v1.23.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.23.0 v1.23.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring        v1.23.1 v1.23.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72           v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73           v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80           v1.23.1 v1.23.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81           v1.23.0 v1.23.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/security-acl             v3.1.1  v3.2.0  Symfony Security Component - ACL (Access Control List)
symfony/string                   v5.3.3  v5.3.7  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/swiftmailer-bundle       v3.5.2  v3.5.2  Symfony SwiftmailerBundle
symfony/symfony                  v4.4.26 v5.3.9  The Symfony PHP framework
symfony/test-pack                v1.0.8  v1.0.9  A pack for functional and end-to-end testing within a Symfony app
```

#### PHP version

```
PHP 7.4.22 (cli) (built: Jul 30 2021 13:08:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
    with Zend OPcache v7.4.22, Copyright (c), by Zend Technologies
```

## Subject

I have caught a bug in version 3.90+ 
I have a filter field with multiple choice and default values.
Since 3.90 I can't just clear this field, because after reloading page I get filled field with default values.

## Steps to reproduce

```
protected function configureDatagridFilters(DatagridMapper $filter): void
{
    $filter->add(
                'orderType',
                'doctrine_orm_choice',
                [],
                ChoiceType::class,
                [
                    'multiple' => true,
                    'choices'  => Order::getOrderTypesListForChoices(),
                ]
            );
}

protected function configureDefaultFilterValues(array &$filterValues): void
    {
        $filterValues['orderType'] = ['type' => '', 'value' => [Order::TYPE_ONE, Order::TYPE_TWO]];
    }
```

## Expected results
After submitting the filter with empty orderType field I get all available orders.
## Actual results
After submitting the filter with empty orderType field I get orders filtered by default values. And orderType field is filled.

## Notes 

Maybe this row causes the error:
```
$parameters = ParametersManipulator::merge($parameters, $filters);
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because bugfix.

Closes #7547.

## Changelog

```markdown
### Fixed
- Multiple choice field with predefined default values
```

### CODE REVIEW

**Comment by kirya-dev** [comment]
Possiiblity you are doing not thar Issue reporter wrote in subject. Problem in clear button.

File: assets/js/admin.js [hunk 1]
```diff
@@ -310,6 +310,15 @@ const Admin = {
 
         if (JSON.stringify(defaultElementValue) === JSON.stringify(elementValue)) {
           element.removeAttribute('name');
+        } else if (element.name.endsWith('[]') && '[]' === JSON.stringify(elementValue)) {
```
Comment (kirya-dev) [inline assets/js/admin.js:313]: Same element.multiple

Comment (kirya-dev) [inline assets/js/admin.js]: Same check `element.multiple`

Comment (kirya-dev) [reply assets/js/admin.js]: `defaultValue` have non clear name

**Comment by kirya-dev** [comment]
Issuer reports sonata-admin 3.105

File: assets/js/admin.js (hunk 1 above)
Comment (kirya-dev) [reply assets/js/admin.js]: I think more reable will be 
```JS
if (element.multiple & !elementValue.lengh) {
  elementValue = ''; // Send empty string because empty array not preset at all in HTTP URI
}
```

Comment (VincentLanglet) [reply assets/js/admin.js]: Setting the value doesnt change anything. The form need to be changed instead. I made multiple try in my project.

**Comment by VincentLanglet** [comment]
> Issuer reports sonata-admin 3.105 

3.x branch is not really supported anymore

File: assets/js/admin.js (hunk 1 above)
Comment (kirya-dev) [reply assets/js/admin.js]: Pls show that you are modified

Comment (kirya-dev) [reply assets/js/admin.js]: Letter `t` fogotten in property name in example above.

Comment (VincentLanglet) [reply assets/js/admin.js]: > Pls show that you are modified

I invite you to try by yourself instead.

You're just overriding a variable. Not the field value.

Comment (kirya-dev) [reply assets/js/admin.js]:
```JS
if (element.multiple & !elementValue.length) {
  element.value = ''; // Set empty string because empty array not preset at all in HTTP URI
}
```

Comment (VincentLanglet) [reply assets/js/admin.js]: I tried this yesterday but it didnt change anything for the submitted values.

Comment (kirya-dev) [reply assets/js/admin.js]: Hmm. Could you help what wrote in `configureDatagridFilters`?

Comment (VincentLanglet) [reply assets/js/admin.js]: I'm not sure to understand. If you look for an example, there is one provided in the issue: https://github.com/sonata-project/SonataAdminBundle/issues/7547

**Review by jordisala1991 — DISMISSED** [review]

File: assets/js/admin.js [hunk 2]
```diff
@@ -310,6 +310,16 @@ const Admin = {
 
         if (JSON.stringify(defaultElementValue) === JSON.stringify(elementValue)) {
           element.removeAttribute('name');
+        } else if (element.multiple && JSON.stringify(elementValue) === '[]') {
+          // Empty array values will not be submitted, but we need to override
+          // the default value provided by AdminInterface::getDefaultFilterParameters
```
Comment (phansys) [inline assets/js/admin.js]:
```suggestion
          // the default value provided by `AdminInterface::getDefaultFilterParameters()`.
```

**Review by phansys — DISMISSED** [review]
