### PR TITLE
Fix some issues with select2 v4

### LINKED ISSUE #7087: single choice select2 clearing function and ModelAutoCompleteType not working
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              dev-master 3385cc2 dev-master 3385cc2 The missing Symfony Admin Generator
sonata-project/block-bundle              4.5.3              4.5.3              Symfony SonataBlockBundle
sonata-project/cache                     2.1.1              2.1.1              Cache library
sonata-project/doctrine-extensions       1.12.0             1.12.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master 8b81d53 dev-master 8b81d53 Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2              2.6.2              Lightweight Exporter library
sonata-project/form-extensions           1.9.0              1.9.0              Symfony form extensions
sonata-project/twig-extensions           1.5.1              1.5.1              Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/asset                      v5.2.4  v5.2.4  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.2.6  v5.2.6  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.2.0  v2.2.0  Generic abstractions related to caching
symfony/config                     v5.2.4  v5.2.4  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.2.6  v5.2.6  Eases the creation of beautiful and testable command line interfaces
symfony/dependency-injection       v5.2.6  v5.2.6  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.2.0  v2.2.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.2.6  v5.2.6  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v5.2.4  v5.2.4  Registers environment variables from a .env file
symfony/error-handler              v5.2.6  v5.2.6  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.2.4  v5.2.4  Provides tools that allow your application components to communicate with each other by dispatching events and listeni...
symfony/event-dispatcher-contracts v2.2.0  v2.2.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.4  v5.2.4  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.2.6  v5.2.6  Provides basic utilities for the filesystem
symfony/finder                     v5.2.4  v5.2.4  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.12.2 v1.12.2 Composer plugin for Symfony
symfony/form                       v5.2.6  v5.2.6  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.2.6  v5.2.6  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client-contracts      v2.3.1  v2.3.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.2.4  v5.2.4  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.2.6  v5.2.6  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.2.4  v5.2.4  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/maker-bundle               v1.30.2 v1.30.2 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writi...
symfony/options-resolver           v5.2.4  v5.2.4  Provides an improved replacement for the array_replace PHP function
symfony/polyfill-intl-grapheme     v1.22.1 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.1 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-normalizer   v1.22.1 v1.22.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.1 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/property-access            v5.2.4  v5.2.4  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.2.4  v5.2.4  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                    v5.2.6  v5.2.6  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.1  v3.1.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.2.6  v5.2.6  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.2.6  v5.2.6  Symfony Security Component - Core Library
symfony/security-csrf              v5.2.4  v5.2.4  Symfony Security Component - CSRF Library
symfony/security-guard             v5.2.4  v5.2.4  Symfony Security Component - Guard
symfony/security-http              v5.2.6  v5.2.6  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.2.0  v2.2.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.4  v5.2.4  Provides a way to profile code
symfony/string                     v5.2.6  v5.2.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.2.6  v5.2.6  Provides tools to internationalize your application
symfony/translation-contracts      v2.3.0  v2.3.0  Generic abstractions related to translation
symfony/twig-bridge                v5.2.6  v5.2.6  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.2.4  v5.2.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.2.6  v5.2.6  Provides tools to validate values
symfony/var-dumper                 v5.2.6  v5.2.6  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.2.4  v5.2.4  Allows exporting any serializable PHP data structure to plain PHP code
symfony/yaml                       v5.2.5  v5.2.5  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.0.3 (cli) (built: Mar  5 2021 00:11:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
```

### 1) Clearing selects does not work
The clearing functionality on selects generated by ModelType is broken. When trying to clear the select field the following js error is thrown `Uncaught TypeError: Cannot read property 'id' of undefined`:
image
This only concerns `'multiple' => false` fields. Multiple select fields still clear fine!

### 2) The ModelAutocompleteType is broken
The ModelAutocompleteType does not work anymore, it just renders an unstyled select and throws a js error `select2.min.js:1 Uncaught Error: No select2/compat/dropdownCss`:
image

The second issue went away when I replaced the `public/...../select2.min.js` with the latest version from here [https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js](url). I tried this after reading about a similar issue here [https://github.com/select2/select2/issues/3302](url) but I don't know what is causing it.

Thanks for all the hard work you guys are putting in lately :)

### PR DESCRIPTION
**Pull request by jordisala1991**
We are using the select2 compat dropdownCss, this feature only comes
when using the full version of select2, trying to use it with the normal
version produces an error and disables the ModelAutocompleteType

## Subject

I am targeting this branch, because this is where the bug appears.

Closes #7087

No changelog needed because this didn't land into any alpha releases

### CODE REVIEW

**Comment by jordisala1991** [comment]
The following issues have been solved:

* Rendering of select2 on model autocomplete field
* Rendering of options / searching... for model autocomplete field
* Infinite loop when no results are found on model autocomplete field (This one we have to discuss if this is the place to apply the fix)
* allow a select2 field to be cleared (it needs to have a placeholder)

**Comment by jordisala1991** [comment]
@moostrich can you validate this PR solves your issues?

File: src/Action/RetrieveAutocompleteItemsAction.php [hunk 1]
```diff
@@ -178,7 +178,7 @@ public function __invoke(Request $request): JsonResponse
 
         return new JsonResponse([
             'status' => 'OK',
-            'more' => !$pager->isLastPage(),
+            'more' => \count($items) > 0 && !$pager->isLastPage(),
```
Comment (jordisala1991) [inline src/Action/RetrieveAutocompleteItemsAction.php:181]: If there are no results in the initial query, the page is 1, and the lastPage is 0. We end returning true when there are not more elements. IMO this could be solved on the persistence bundles, but if not, this is a possible fix.

File: src/Resources/public/Admin.js [hunk 2]
```diff
@@ -126,6 +126,7 @@ var Admin = {
                     theme: 'bootstrap',
                     dropdownAutoWidth: true,
                     minimumResultsForSearch: minimumResultsForSearch,
+                    placeholder: allowClearEnabled ? ' ' : '', // allowClear needs placeholder to work properly
```
Comment (jordisala1991) [inline src/Resources/public/Admin.js:129]: The same solution is applied here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig#L72

File: src/Resources/public/Admin.js [hunk 3]
```diff
@@ -567,6 +568,7 @@ var Admin = {
         }
 
         var options = Object.assign({
+            theme: 'bootstrap',
```
Comment (jordisala1991) [inline src/Resources/public/Admin.js:571]: I missed this one while upgrading to v4

File: src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig [hunk 4]
```diff
@@ -62,6 +62,7 @@ file that was distributed with this source code.
                 readonly: {{ attr.read_only|default(false) ? 'true' : 'false' }},
                 minimumInputLength: {{ minimum_input_length }},
                 multiple: {{ multiple ? 'true' : 'false' }},
+                theme: 'bootstrap',
```
Comment (jordisala1991) [inline src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig:65]: Missed this one too

**Review by VincentLanglet — APPROVED** [review]

**Review by phansys — APPROVED** [review]

**Comment by moostrich** [comment]
@jordisala1991 Jup, this PR fixes all the issues I found. Thanks for looking into it :)
