### PR TITLE
#8315 introduce asset package names

### LINKED ISSUE #8315: Assets from extra_stylesheets not found
#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
Direct dependencies required in composer.json:                                                                                                                                                                                        
sonata-project/admin-bundle              4.37.5 4.37.5 The missing Symfony Admin Generator
sonata-project/doctrine-orm-admin-bundle 4.18.0 4.18.0 Integrate Doctrine ORM into the SonataAdminBundle

Transitive dependencies not required in composer.json:                                                                                                                                                                                
sonata-project/block-bundle              5.1.2  5.2.0  Symfony SonataBlockBundle
sonata-project/doctrine-extensions       2.5.0  2.5.0  Doctrine2 behavioral extensions
sonata-project/exporter                  3.3.1  3.3.1  Lightweight Exporter library
sonata-project/form-extensions           2.4.1  2.5.0  Symfony form extensions
sonata-project/twig-extensions           2.5.0  2.5.0  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
Direct dependencies required in composer.json:
symfony/amqp-messenger             7.2.3  7.3.2  Symfony AMQP extension Messenger Bridge
symfony/asset                      7.2.0  7.3.0  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/asset-mapper               7.2.5  7.3.2  Maps directories of assets & makes them available in a public directory with versioned filenames.
symfony/console                    7.2.5  7.3.2  Eases the creation of beautiful and testable command line interfaces
symfony/debug-bundle               7.2.0  7.3.0  Provides a tight integration of the Symfony VarDumper component and the ServerLogCommand from MonologBridge into the Symfony full-stack framework
symfony/dotenv                     7.2.0  7.3.2  Registers environment variables from a .env file
symfony/fake-sms-notifier          7.2.0  7.3.1  Fake SMS (as email or log during development) Notifier Bridge.
symfony/flex                       2.5.0  2.8.1  Composer plugin for Symfony
symfony/framework-bundle           7.2.5  7.3.2  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/lock                       7.2.5  7.3.2  Creates and manages locks, a mechanism to provide exclusive access to a shared resource
symfony/mailer                     7.2.3  7.3.2  Helps sending emails
symfony/maker-bundle               1.62.1 1.64.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mercure-bundle             0.3.9  0.3.9  Symfony MercureBundle
symfony/messenger                  7.2.5  7.3.2  Helps applications send and receive messages to/from other applications or via message queues
symfony/mime                       7.2.4  7.3.2  Allows manipulating MIME messages
symfony/monolog-bundle             3.10.0 3.10.0 Symfony MonologBundle
symfony/notifier                   7.2.0  7.3.0  Sends notifications via one or more channels (email, SMS, ...)
symfony/process                    7.2.5  7.3.0  Executes commands in sub-processes
symfony/rate-limiter               7.2.0  7.3.2  Provides a Token Bucket implementation to rate limit input and output in your application
symfony/runtime                    7.2.3  7.3.1  Enables decoupling PHP applications from global state
symfony/scheduler                  7.2.3  7.3.2  Provides scheduling through Symfony Messenger
symfony/security-bundle            7.2.3  7.3.2  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/stimulus-bundle            2.24.0 2.29.1 Integration with your Symfony app & Stimulus!
symfony/stopwatch                  7.2.4  7.3.0  Provides a way to profile code
symfony/twig-bundle                7.2.0  7.3.2  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/ux-autocomplete            2.24.0 2.29.1 JavaScript Autocomplete functionality for Symfony
symfony/ux-icons                   2.24.0 2.29.0 Renders local and remote SVG icons in your Twig templates.
symfony/ux-live-component          2.24.0 2.29.1 Live components for Symfony
symfony/ux-twig-component          2.24.0 2.29.0 Twig components for Symfony
symfony/var-dumper                 7.2.3  7.3.2  Provides mechanisms for walking through any arbitrary PHP variable
symfony/web-profiler-bundle        7.2.4  7.3.2  Provides a development tool that gives detailed information about the execution of any request
symfony/workflow                   7.2.0  7.3.2  Provides tools for managing a workflow or finite state machine
symfony/yaml                       7.2.5  7.3.2  Loads and dumps YAML files

Transitive dependencies not required in composer.json:
symfony/cache                      7.2.5  7.3.2  Provides extended PSR-6, PSR-16 (and tags) implementations
symfony/cache-contracts            3.5.1  3.6.0  Generic abstractions related to caching
symfony/clock                      7.2.0  7.3.0  Decouples applications from the system clock
symfony/config                     7.2.3  7.3.2  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/dependency-injection       7.2.5  7.3.2  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      3.5.1  3.6.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            7.2.5  7.3.2  Provides integration for Doctrine with various Symfony components
symfony/error-handler              7.2.5  7.3.2  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           7.2.0  7.3.0  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts 3.5.1  3.6.0  Generic abstractions related to dispatching event
symfony/expression-language        7.2.0  7.3.2  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 7.2.0  7.3.2  Provides basic utilities for the filesystem
symfony/finder                     7.2.2  7.3.2  Finds files and directories via an intuitive fluent interface
symfony/form                       7.2.5  7.3.2  Allows to easily create, process and reuse HTML forms
symfony/http-client                7.2.4  7.3.2  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      3.5.2  3.6.0  Generic abstractions related to HTTP clients
symfony/http-foundation            7.2.5  7.3.2  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                7.2.5  7.3.2  Provides a structured process for converting a Request into a Response
symfony/mercure                    0.6.5  0.6.5  Symfony Mercure Component
symfony/monolog-bridge             7.2.0  7.3.0  Provides integration for Monolog with various Symfony components
symfony/options-resolver           7.2.0  7.3.2  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            7.2.0  7.3.0  Provides password hashing utilities
symfony/polyfill-intl-grapheme     1.31.0 1.32.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          1.31.0 1.32.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          1.31.0 1.32.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   1.31.0 1.32.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          1.31.0 1.32.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php83             1.31.0 1.32.0 Symfony polyfill backporting some PHP 8.3+ features to lower PHP versions
symfony/polyfill-php84             1.31.0 1.32.0 Symfony polyfill backporting some PHP 8.4+ features to lower PHP versions
symfony/property-access            7.2.3  7.3.2  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              7.2.5  7.3.1  Extracts information about PHP class' properties using metadata of popular sources
symfony/routing                    7.2.3  7.3.2  Maps an HTTP request to a set of configuration variables
symfony/security-acl               3.3.4  3.3.4  Symfony Security Component - ACL (Access Control List)
symfony/security-core              7.2.3  7.3.2  Symfony Security Component - Core Library
symfony/security-csrf              7.2.3  7.3.0  Symfony Security Component - CSRF Library
symfony/security-http              7.2.4  7.3.2  Symfony Security Component - HTTP Integration
symfony/serializer                 7.2.5  7.3.2  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          3.5.1  3.6.0  Generic abstractions related to writing services
symfony/string                     7.2.0  7.3.2  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                7.2.4  7.3.2  Provides tools to internationalize your application
symfony/translation-contracts      3.5.1  3.6.0  Generic abstractions related to translation
symfony/twig-bridge                7.2.5  7.3.2  Provides integration for Twig with various Symfony components
symfony/type-info                  7.2.5  7.3.2  Extracts PHP types information.
symfony/validator                  7.2.5  7.3.2  Provides tools to validate values
symfony/var-exporter               7.2.5  7.3.2  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   7.2.0  7.3.0  Manages links between resources
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 8.3.21 (cli) (built: May 21 2025 23:17:25) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.21, Copyright (c) Zend Technologies
    with Xdebug v3.4.0, Copyright (c) 2002-2024, by Derick Rethans
```

## Subject

There is a bug in #8300. LastModifiedVersionStrategy doesnt work properly with extra stylesheets defined in sonata_admin.yaml in sonata_admin.assets.extra_stylesheets. It looks for asset in public directory but in DEV env assets are not publushed here. In PROD env after running `asset-map:compile` all assets will have unique suffix in its name, but not a version parameter. So in both cases asset will be not found.

extra_stylesheets work in 4.36.2 and I think it was broken in 4.37.0 and still doesn't work in 4.37.5

## Steps to reproduce
Add extra stylesheets in sonata_admin.yaml:
```
sonata_admin:
    assets:
        extra_stylesheets:
            - styles/admin/sonata_admin.css
```

## Expected results
Assets are loaded

## Actual results
404 (Not Found) when loading styles/admin/sonata_admin.css

### PR DESCRIPTION
**Pull request by andreybotanic**
## Subject

New `package_name` option added to `stylesheets`, `extra_stylesheets`, `javascripts` and `extra_javascripts` assets. `package_name` may be missed and by default it is `sonata_admin`. Theese lines are equivalent:
```
sonata_admin
    assets:
        extra_stylesheets:
            - foo/bar.css
            - { path: foo/bar.css, package_name: sonata_admin }
```

`package_name` can also be null:
```
sonata_admin
    assets:
        extra_stylesheets:
            - { path: bar/bazz.css, package_name: ~ }
```
null `package_name` is useful when you are using e.g. `AssetMapper` component (it can handle all assets from all bundles).

I am targeting this branch, because there are no BC-breaks.

Closes #8315.

## Changelog

```markdown
### Added
- Optional package_name for assets
```

### CODE REVIEW

File: src/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -712,4 +750,91 @@ public function getConfigTreeBuilder(): TreeBuilder
...
+        // 2) Array forms
+        if (\is_array($item)) {
+            // Positional form: [asset, package_name]
+            if (array_is_list($item)) {
+                return match (\count($item)) {
+                    2 => [
+                        'asset' => (string) $item[0],
+                        'package_name' => null === $item[1] ? null : (string) $item[1],
+                    ],
+                    default => throw new \InvalidArgumentException(
```
Comment (VincentLanglet) [inline src/DependencyInjection/Configuration.php]: You say you support [asset] but you only handle count = 2 in your match

File: src/DependencyInjection/SonataAdminExtension.php [hunk 2]
```diff
@@ -258,21 +263,23 @@ private function buildJavascripts(array $config): array
     }
 
     /**
-     * @param array<int, string> $array
-     * @param array<int, string> $addArray
-     * @param array<int, string> $removeArray
+     * @param array<int, SonataAdminAsset> $array
+     * @param array<int, SonataAdminAsset> $addArray
+     * @param array<int, string>           $removeArray
```
Comment (VincentLanglet) [inline src/DependencyInjection/SonataAdminExtension.php:268]: Should the removeArray have the same format ?

File: src/DependencyInjection/Configuration.php (hunk 1 above)
Comment (andreybotanic) [reply src/DependencyInjection/Configuration.php]: No, [asset] form is not suppurted (there was wrong comment at the first). I don't think it's needed. If you don't want to add custom package_name you should use simple string.

File: src/DependencyInjection/SonataAdminExtension.php (hunk 2 above)
Comment (andreybotanic) [reply src/DependencyInjection/SonataAdminExtension.php:268]: I don't think so. Anyway you will remove asset by its path and I don't think it's possible to have assets with the same path but in diffarent packages.

**Comment by onEXHovia** [comment]
I think the `[foo/bar.css, sonata_admin]` option is redundant. It's enough to either use a simple string with the asset path or key-based format: `{ asset: foo/bar.css, package_name: sonata_admin }`, since a third key might appear later, this approach allows for easier extension.

Maybe the key `path` would be more logical: `{ path: foo/bar.css, package_name: sonata_admin }`.

```
 @phpstan-type SonataAdminAsset = array{
      path: string,
      package_name: string|null,
 }
```

File: src/DependencyInjection/Configuration.php (hunk 1 above)
Comment (VincentLanglet) [reply src/DependencyInjection/Configuration.php]: In the error message you say [asset] is supported

**Comment by andreybotanic** [comment]
I did some changes:
- renamed `asset` key to `path`
- removed form `[foo/bar.css, sonata_admin]`
- addd more tests to check wrong configuration

File: src/DependencyInjection/Configuration.php [hunk 3]
```diff
@@ -172,6 +176,8 @@
  */
 final class Configuration implements ConfigurationInterface
 {
+    private const DEFAULT_PACKAGE = 'sonata_admin';
```
Comment (andreybotanic) [inline src/DependencyInjection/Configuration.php:179]: I didn't find a good place for this constant so I placed it here. May be it's better to move it somewere.

**Review by VincentLanglet — APPROVED** [review]
