### PR TITLE
Handle Abstract class of mapped entities in autocompletion

### LINKED ISSUE #7822: Cannot use `ModelAutocompleteType` with mapped entities
#### Sonata packages

<details><summary>show</summary>
<p>

```
sonata-project/admin-bundle              4.11.1 4.11.1 The missing Symfony Admin Generator
sonata-project/block-bundle              4.11.0 4.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.2.0  2.2.0  Cache library
sonata-project/doctrine-extensions       1.16.0 1.17.0 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.2.8  4.2.8  Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.11.0 2.11.0 Lightweight Exporter library
sonata-project/form-extensions           1.13.1 1.16.0 Symfony form extensions
sonata-project/intl-bundle               2.11.2 2.12.1 Symfony SonataIntlBundle
sonata-project/twig-extensions           1.9.1  1.9.1  Sonata twig extensions
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
symfony/amazon-sqs-messenger       v5.4.3  v6.0.3  Symfony Amazon SQS extension Messenger Bridge
symfony/amqp-messenger             v5.4.5  v6.0.7  Symfony AMQP extension Messenger Bridge
symfony/asset                      v5.4.7  v6.0.7  Manages URL generation and versioning of web assets such as CSS stylesheets, Ja...
symfony/browser-kit                v5.4.3  v6.0.3  Simulates the behavior of a web browser, allowing you to make requests, click o...
symfony/cache                      v5.4.7  v6.0.8  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.5.0  v3.0.1  Generic abstractions related to caching
symfony/config                     v5.4.7  v6.0.8  Helps you find, load, combine, autofill and validate configuration values of an...
symfony/console                    v5.4.7  v6.0.8  Eases the creation of beautiful and testable command line interfaces
symfony/css-selector               v5.4.3  v6.0.3  Converts CSS selectors to XPath expressions
symfony/debug-bundle               v5.4.3  v6.0.3  Provides a tight integration of the Symfony VarDumper component and the ServerL...
symfony/dependency-injection       v5.4.7  v6.0.8  Allows you to standardize and centralize the way objects are constructed in you...
symfony/deprecation-contracts      v3.0.0  v3.0.1  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.4.7  v6.0.8  Provides integration for Doctrine with various Symfony components
symfony/doctrine-messenger         v5.4.7  v6.0.8  Symfony Doctrine Messenger Bridge
symfony/dom-crawler                v5.4.6  v6.0.6  Eases DOM navigation for HTML and XML documents
symfony/dotenv                     v5.4.5  v6.0.5  Registers environment variables from a .env file
symfony/error-handler              v5.4.7  v6.0.8  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.4.3  v6.0.3  Provides tools that allow your application components to communicate with each ...
symfony/event-dispatcher-contracts v2.5.0  v3.0.1  Generic abstractions related to dispatching event
symfony/expression-language        v5.4.7  v6.0.8  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.4.7  v6.0.7  Provides basic utilities for the filesystem
symfony/finder                     v5.4.3  v6.0.8  Finds files and directories via an intuitive fluent interface
symfony/flex                       v2.1.6  v2.1.8  Composer plugin for Symfony
symfony/form                       v5.4.7  v6.0.8  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.4.7  v6.0.8  Provides a tight integration between Symfony components and the Symfony full-st...
symfony/http-client                v5.4.7  v6.0.8  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.5.0  v3.0.1  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.4.6  v6.0.8  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.4.7  v6.0.8  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.4.5  v6.0.8  Provides a PHP replacement layer for the C intl extension that includes additio...
symfony/lock                       v5.4.7  v6.0.7  Creates and manages locks, a mechanism to provide exclusive access to a shared ...
symfony/loco-translation-provider  v5.4.7  v6.0.8  Symfony Loco Translation Provider Bridge
symfony/mailer                     v5.4.7  v6.0.8  Helps sending emails
symfony/messenger                  v5.4.3  v6.0.8  Helps applications send and receive messages to/from other applications or via ...
symfony/mime                       v5.4.7  v6.0.8  Allows manipulating MIME messages
symfony/monolog-bridge             v5.4.3  v6.0.3  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.1  v3.8.0  Symfony MonologBundle
symfony/options-resolver           v5.4.3  v6.0.3  Provides an improved replacement for the array_replace PHP function
symfony/password-hasher            v5.4.3  v6.0.8  Provides password hashing utilities
symfony/phpunit-bridge             v6.0.7  v6.0.8  Provides utilities for PHPUnit, especially user deprecation notices management
symfony/polyfill-ctype             v1.25.0 v1.25.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme     v1.25.0 v1.25.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.25.0 v1.25.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.25.0 v1.25.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.25.0 v1.25.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.25.0 v1.25.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56             v1.20.0 v1.20.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php72             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/polyfill-php81             v1.25.0 v1.25.0 Symfony polyfill backporting some PHP 8.1+ features to lower PHP versions
symfony/polyfill-uuid              v1.25.0 v1.25.0 Symfony polyfill for uuid functions
symfony/process                    v5.4.7  v6.0.8  Executes commands in sub-processes
symfony/property-access            v5.4.7  v6.0.8  Provides functions to read and write from/to an object or array using a simple ...
symfony/property-info              v5.4.7  v6.0.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.4.6  v6.0.6  Provides integration for ProxyManager with various Symfony components
symfony/psr-http-message-bridge    v2.1.2  v2.1.2  PSR HTTP message bridge
symfony/psr7-meta                  v1.0.0  v1.0.0  A meta package providing recipes for PSR-7
symfony/rate-limiter               v5.4.7  v6.0.8  Provides a Token Bucket implementation to rate limit input and output in your a...
symfony/redis-messenger            v5.4.6  v6.0.7  Symfony Redis extension Messenger Bridge
symfony/routing                    v5.4.3  v6.0.8  Maps an HTTP request to a set of configuration variables
symfony/runtime                    v5.4.7  v6.0.8  Enables decoupling PHP applications from global state
symfony/security-acl               v3.3.1  v3.3.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.4.5  v6.0.8  Provides a tight integration of the Security component into the Symfony full-st...
symfony/security-core              v5.4.7  v6.0.8  Symfony Security Component - Core Library
symfony/security-csrf              v5.4.3  v6.0.3  Symfony Security Component - CSRF Library
symfony/security-guard             v5.4.3  v5.4.3  Symfony Security Component - Guard
symfony/security-http              v5.4.5  v6.0.8  Symfony Security Component - HTTP Integration
symfony/service-contracts          v2.4.1  v3.0.1  Generic abstractions related to writing services
symfony/stopwatch                  v5.4.5  v6.0.5  Provides a way to profile code
symfony/string                     v5.4.3  v6.0.8  Provides an object-oriented API to strings and deals with bytes, UTF-8 code poi...
symfony/templating                 v5.4.3  v6.0.3  Provides all the tools needed to build any kind of template system
symfony/translation                v5.4.7  v6.0.8  Provides tools to internationalize your application
symfony/translation-contracts      v2.5.0  v3.0.1  Generic abstractions related to translation
symfony/twig-bridge                v5.4.7  v6.0.8  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.4.3  v6.0.8  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.4.7  v6.0.8  Provides tools to validate values
symfony/var-dumper                 v5.4.6  v6.0.8  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.4.7  v6.0.8  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-profiler-bundle        v5.4.6  v6.0.8  Provides a development tool that gives detailed information about the execution...
symfony/webpack-encore-bundle      v1.14.0 v1.14.1 Integration with your Symfony app & Webpack Encore!
symfony/workflow                   v5.4.3  v6.0.8  Provides tools for managing a workflow or finite state machine
symfony/yaml                       v5.4.3  v6.0.3  Loads and dumps YAML files
```

</p>
</details>

#### PHP version

```
PHP 8.0.17 (cli) (built: Mar 18 2022 09:32:28) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.17, Copyright (c), by Zend Technologies
    with blackfire v1.73.0~mac-x64-non_zts80, https://blackfire.io, by Blackfire
```

## Subject

I tried to use `Sonata\AdminBundle\Form\Type\ModelAutocompleteType` in a definition which relates to a mapped entity.
But `Sonata\AdminBundle\Action\RetrieveAutocompleteItemsAction` tries to instanciate the abstract class to give an empty subject to "avoid" performance issue.

## Steps to reproduce
Use `Sonata\AdminBundle\Form\Type\ModelAutocompleteType` in the datagrid filters of a definition related to a mapped entity.

## Expected results
Having autocomplete.

## Actual results

The ajax request is going HTTP 500.
Url: `/contrib/core/get-autocomplete-items?q=test&_per_page=10&_sonata_admin=app.admin.adoption.pet.pet&field=shelter&_context=filter&_=1652713926257`
image

### PR DESCRIPTION
**Pull request by Geekimo**
## Handle Abstract class of mapped entities in autocompletion

This PR aims to add mapped entities handling for `ModelAutocompleteType` when definition's subject is an abstract entity.

I am targeting this branch, because this is the current stable release.

Closes #7822 .

## Changelog

```markdown
### Added
- Support for abstract class subject in `RetrieveAutocompleteItemsAction`.
```

### CODE REVIEW

File: src/Action/RetrieveAutocompleteItemsAction.php [hunk 1]
```diff
@@ -57,8 +58,13 @@ public function __invoke(Request $request): JsonResponse
             throw new AccessDeniedException();
         }
 
-        // subject will be empty to avoid unnecessary database requests and keep autocomplete function fast
-        $admin->setSubject($admin->getNewInstance());
+        try {
+            // subject will be empty to avoid unnecessary database requests and keep autocomplete function fast
+            $admin->setSubject($admin->getNewInstance());
+        } catch (AbstractEntityException) {
```
Comment (VincentLanglet) [inline src/Action/RetrieveAutocompleteItemsAction.php]: Catching RuntimeException was an issue ?

Comment (Geekimo) [reply src/Action/RetrieveAutocompleteItemsAction.php]: I cannot be sure that the `RuntimeException` is the one thrown from the `Instantiator`.

File: src/Action/RetrieveAutocompleteItemsAction.php [hunk 2]
```diff
@@ -57,8 +58,13 @@ public function __invoke(Request $request): JsonResponse
...
         }
 
-        // subject will be empty to avoid unnecessary database requests and keep autocomplete function fast
-        $admin->setSubject($admin->getNewInstance());
+        try {
+            // subject will be empty to avoid unnecessary database requests and keep autocomplete function fast
+            $admin->setSubject($admin->getNewInstance());
+        } catch (AbstractClassException) {
+            // in case the subject is an abstract entity, we continue
+            // no-op
```
Comment (Kocal) [inline src/Action/RetrieveAutocompleteItemsAction.php]:
```suggestion
            // in case if the subject is an abstract entity, we continue
```

File: src/Util/Instantiator.php [hunk 3]
```diff
@@ -27,7 +29,7 @@ public static function instantiate(string $class): object
     {
         $r = new \ReflectionClass($class);
         if ($r->isAbstract()) {
-            throw new \RuntimeException(sprintf('Cannot initialize abstract class: %s', $class));
+            throw new AbstractClassException(sprintf('Cannot initialize abstract class: %s', $class));
```
Comment (Kocal) [inline src/Util/Instantiator.php]:
```suggestion
            throw new AbstractClassException($class);
```

Then you can update `AbstractClassException`'s constructor which will create the error message.

File: tests/Util/InstantiatorTest.php [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+
+/**
+ * @author Morgan Abraham <morgan@geekimo.me>
+ */
+final class InstantiatorTest extends TestCase
+{
+    public function testAbstractClassThrowsException(): void
+    {
+        $this->expectException(AbstractClassException::class);
+        Instantiator::instantiate(AbstractEntity::class);
```
Comment (Kocal) [inline tests/Util/InstantiatorTest.php]:
```suggestion
        $this->expectException(AbstractClassException::class);

        Instantiator::instantiate(AbstractEntity::class);
```

File: tests/Util/InstantiatorTest.php [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+
+use PHPUnit\Framework\TestCase;
+use Sonata\AdminBundle\Exception\AbstractClassException;
+use Sonata\AdminBundle\Tests\Fixtures\Entity\AbstractEntity;
+use Sonata\AdminBundle\Util\Instantiator;
+
+/**
+ * @author Morgan Abraham <morgan@geekimo.me>
+ */
+final class InstantiatorTest extends TestCase
```
Comment (Kocal) [inline tests/Util/InstantiatorTest.php:25]: It would be great to have another test that checks if a non-abstract class can be instanciated.

File: src/Exception/AbstractClassException.php [hunk 6]
```diff
@@ -0,0 +1,21 @@
...
+ * For the full copyright and license information, please view the LICENSE
+ * file that was distributed with this source code.
+ */
+
+namespace Sonata\AdminBundle\Exception;
+
+/**
+ * @author Morgan Abraham <morgan@geekimo.me>
+ */
+final class AbstractClassException extends \RuntimeException
```
Comment (franmomu) [inline src/Exception/AbstractClassException.php:21]:
```suggestion
final class AbstractClassException extends \InvalidArgumentException
```
Since the argument passed is invalid, what about extending `InvalidArgumentException`?

Comment (VincentLanglet) [reply src/Exception/AbstractClassException.php:21]: Previously we were throwing a RuntimeException, so extending an InvalidArgumentException would be a BC-break (in case someone was catching RuntimeException), isn't it ?

I think the best we can do is
```
/**
 * NEXT_MAJOR: extends \InvalidArgumentException
 */
final class AbstractClassException extends \RuntimeException
```

File: src/Action/RetrieveAutocompleteItemsAction.php (hunk 2 above)
Comment (VincentLanglet) [reply src/Action/RetrieveAutocompleteItemsAction.php]: I agree that the `no-op` can be removed.

If a comment need to be added, it would be about "why it's still working without a subject set"

File: src/Util/Instantiator.php (hunk 3 above)
Comment (VincentLanglet) [reply src/Util/Instantiator.php]: This could be great indeed

**Comment by VincentLanglet** [comment]
@Geekimo This PR is ok to me, after the small request changes made by Kocal.

File: src/Exception/AbstractClassException.php (hunk 6 above)
Comment (Geekimo) [reply src/Exception/AbstractClassException.php:21]: Done (NEXT_MAJOR comment)

File: tests/Util/InstantiatorTest.php (hunk 5 above)
Comment (Geekimo) [reply tests/Util/InstantiatorTest.php:25]: Done, I've added another case.

File: tests/Util/InstantiatorTest.php (hunk 4 above)
Comment (Geekimo) [reply tests/Util/InstantiatorTest.php]: Done

File: src/Util/Instantiator.php (hunk 3 above)
Comment (Geekimo) [reply src/Util/Instantiator.php]: Done, sounds more logical.

File: src/Action/RetrieveAutocompleteItemsAction.php (hunk 2 above)
Comment (Geekimo) [reply src/Action/RetrieveAutocompleteItemsAction.php]: Done

**Comment by Geekimo** [comment]
@Kocal @VincentLanglet All comments have been adressed.

**Review by VincentLanglet — DISMISSED** [review]

**Comment by VincentLanglet** [comment]
Test are failing @Geekimo ; can u take a look ?

**Comment by Geekimo** [comment]
@VincentLanglet Php 7.4 does not like catch blocks without variables... That's fixed.

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks !

File: src/Exception/AbstractClassException.php (hunk 6 above)
Comment (franmomu) [reply src/Exception/AbstractClassException.php:21]: It shouldn't be a BC break since`Instantiator` was created as `@internal` IIRC

Comment (jordisala1991) [reply src/Exception/AbstractClassException.php:21]: Maybe we can change it before release, then?

Comment (VincentLanglet) [reply src/Exception/AbstractClassException.php:21]: https://github.com/sonata-project/SonataAdminBundle/pull/7825
