### PR TITLE
Increase consistency on default page sizes

### LINKED ISSUE #4391: Default page sizes are confusing
### Environment
Not relevant.

#### Sonata packages

```bash
# not relevant
```

#### Symfony packages

```bash
# not relevant
```

#### PHP version

```bash
# not relevant
```

## Subject
**Disclamer**: yes, I do know that this property is easily configurable and I can override it. My point is that the default distribution must be as user-friendly as possible.

[Default page sizes](https://github.com/sonata-project/SonataAdminBundle/blob/f880155d92450a874bbdcad952c486cef882270e/Admin/AbstractAdmin.php#L169) are confusing. Admin panels are meant to be designed for non-technical staff. Non-technical staff is used to counting things in multiples of tens not twos. E.g. 10, 20, 50, 100, 500.

If you decide to stick to binary-based page sizes then what is the rationale behind having the last item equal to `192`? Why not `256` which would be consistent to the previous sequence elements?

## Steps to reproduce
Open any admin panel.

## Expected results
Expect to see decimal-based page sizes.

## Actual results
Page sizes are binary-based.

### PR DESCRIPTION
**Pull request by jordisala1991**
I am targeting this branch, because this is BC.

Closes #4391 

## Changelog

```markdown
### Fixed
- Increase consistency on default page sizes (replaced 192 by 256)
```

## Subject

192 didn't make sense, 256 is more consistent.

### CODE REVIEW

File: tests/Admin/AdminTest.php [hunk 1]
```diff
@@ -802,7 +802,7 @@ public function testGetPerPageOptions()
     {
         $admin = new PostAdmin('sonata.post.admin.post', 'NewsBundle\Entity\Post', 'SonataNewsBundle:PostAdmin');
 
-        $this->assertSame([16, 32, 64, 128, 192], $admin->getPerPageOptions());
+        $this->assertSame([16, 32, 64, 128, 256], $admin->getPerPageOptions());
```
Comment (greg0ire) [inline tests/Admin/AdminTest.php]: Please change the test so that you don't have to change them when checking the values. You could check that all the values are divisible by 4, for instance.

**Comment by jordisala1991** [comment]
Fixed, I simplified a bit those assertions, too much checking is redundant.

**Comment by greg0ire** [comment]
Thanks @jordisala1991!
