### PR TITLE
Fix compatibility with Symfony 3.2 form renderer

### LINKED ISSUE #4152: CRUD Controller tries to access private property Symfony\Bridge\Twig\Extension\FormExtension::$renderer
Environment
Symfony 3.2.0-dev
SonataAdminBundle 3.x-dev
StackTrace
[1] Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access private property Symfony\Bridge\Twig\Extension\FormExtension::$renderer
    at n/a
        in .../vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 108

### PR DESCRIPTION
**Pull request by Koc**
I am targetting this branch, because this is bugfix.

Closes #4152, #4154

## Changelog

```markdown
### Added
- Added helper method `CRUDController::setFormTheme`.
### Fixed
- Fix compatibility with Symfony 3.2 form renderer.
```

## Subject

Proposed sollution in #4154 breaks compatibility with older Symfony versions because `twig.form.renderer` service is private https://github.com/symfony/symfony/blob/2.8/src/Symfony/Bundle/TwigBundle/Resources/config/twig.xml#L156 . Also I've updated code in other places.

### CODE REVIEW

**Comment by Koc** [comment]
Also another approach is maybe calling `$this->get('twig')->getRuntime('Symfony\Bridge\Twig\Form\TwigRenderer')->setTheme(...)`.

@fabpot, @stof can you please suggest how to deal in this case?

File: Controller/CRUDController.php [hunk 1]
```diff
@@ -105,7 +105,12 @@ public function listAction()
         $formView = $datagrid->getForm()->createView();
 
         // set the theme for the current Admin Form
-        $this->get('twig')->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')->renderer->setTheme($formView, $this->admin->getFilterTheme());
+        if ($this->has('twig.form.renderer')) {
```
Comment (greg0ire) [inline Controller/CRUDController.php]: `has` does not seem to exist (see Travis)

File: Controller/CRUDController.php [hunk 2]
```diff
@@ -105,7 +105,12 @@ public function listAction()
...
+            $this->get('twig.form.renderer')->setTheme($formView, $this->admin->getFilterTheme());
+        } else {
+            // BC for Symfony < 3.2
+            $this->get('twig')->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')->renderer->setTheme($formView, $this->admin->getFilterTheme());
```
Comment (greg0ire) [inline Controller/CRUDController.php]: Please linebreak this

File: Controller/HelperController.php [hunk 3]
```diff
@@ -112,7 +112,13 @@ public function appendFormFieldElementAction(Request $request)
 
         $extension = $this->twig->getExtension('Symfony\Bridge\Twig\Extension\FormExtension');
         $extension->initRuntime($this->twig);
-        $extension->renderer->setTheme($view, $admin->getFormTheme());
+
+        if ($this->has('twig.form.renderer')) {
```
Comment (greg0ire) [inline Controller/HelperController.php]: `HelperController` does not extend the standard sf controller, hence the error you get in Travis

Comment (greg0ire) [inline Controller/HelperController.php]: You can get the container from the pool if you wish (it's a very ugly, but should do the trick).

Comment (greg0ire) [inline Controller/HelperController.php]: The alternative would be to simply extend the standard controller.

Comment (Koc) [inline Controller/HelperController.php]: No, I will inject `twig.form.renderer` service here inside constructor. Controller as a service helps a lot here.

Comment (greg0ire) [inline Controller/HelperController.php]: Ok, but you will have do inject it conditionally, since it does not necessarily exist, right?

File: Tests/Controller/HelperControllerTest.php [hunk 4]
```diff
@@ -717,4 +717,14 @@ public function getValidatorInterfaces()
 
         return $data;
     }
+
+    protected function getTwigRenderer()
```
Comment (greg0ire) [inline Tests/Controller/HelperControllerTest.php]: private?

File: Controller/CRUDController.php [hunk 5]
```diff
@@ -1364,4 +1363,18 @@ protected function preList(Request $request)
 
         return $this->get('translator')->trans($id, $parameters, $domain, $locale);
     }
+
+    protected function setFormTheme(FormView $formView)
```
Comment (core23) [inline Controller/CRUDController.php]: final?

Comment (core23) [inline Controller/CRUDController.php]: PHPdoc missing

File: Controller/HelperController.php [hunk 6]
```diff
@@ -53,12 +54,18 @@ class HelperController
...
+
+    /**
      * @param \Twig_Environment  $twig
      * @param Pool               $pool
      * @param AdminHelper        $helper
      * @param ValidatorInterface $validator
+     * @param TwigRenderer       $twigRenderer
      */
-    public function __construct(\Twig_Environment $twig, Pool $pool, AdminHelper $helper, $validator)
+    public function __construct(\Twig_Environment $twig, Pool $pool, AdminHelper $helper, $validator, TwigRenderer $twigRenderer)
```
Comment (core23) [inline Controller/HelperController.php]: This is a BC break. Please make the last parameter optional

File: Controller/CRUDController.php (hunk 5 above)
Comment (core23) [inline Controller/CRUDController.php]: Would prefer a private method, because we will move the twig stuff to the template completly.

File: Controller/HelperController.php (hunk 6 above)
Comment (greg0ire) [inline Controller/HelperController.php]: And use `TwigRendererInterface` as type hinting, it will be easier to make the build pass

Comment (Koc) [inline Controller/HelperController.php]: @greg0ire it is deprecated since 3.2 https://github.com/symfony/twig-bridge/blob/master/Form/TwigRendererInterface.php

Comment (greg0ire) [inline Controller/HelperController.php]: Oh… too bad.

File: Controller/CRUDController.php [hunk 7]
```diff
@@ -1348,6 +1347,23 @@ protected function preList(Request $request)
     {
     }
 
+    protected function setFormTheme(FormView $formView)
```
Comment (core23) [inline Controller/CRUDController.php]: - private please
- add phpdoc

File: Controller/HelperController.php [hunk 8]
```diff
@@ -497,4 +493,18 @@ private function retrieveFilterFieldDescription(AdminInterface $admin, $field)
 
         return $fieldDescription;
     }
+
+    protected function setFormTheme(FormView $formView, $theme)
```
Comment (core23) [inline Controller/HelperController.php]: - private please
- add phpdoc

**Comment by fbourigault** [comment]
This is a Symfony BC break. I opened a pull request: https://github.com/symfony/symfony/pull/20710.

**Comment by cedricziel** [comment]
Just saw this PR. FYI: I have a similar approach, but use the container to retrieve the renderer, which should save some hassle. https://github.com/cedricziel/SonataAdminBundle/commit/23707f91d0679cbf8b1d362796280a80529a36dd

**Comment by Koc** [comment]
@cedricziel I've tryed this before. The problem that we need pass another dependency to `HelperController`. In my updated sollution we using only Twig.

**Comment by cedricziel** [comment]
@Koc the `HelperController` in my commit uses twig itself or falls back on the old way. https://github.com/cedricziel/SonataAdminBundle/commit/23707f91d0679cbf8b1d362796280a80529a36dd#diff-bca3ecd7f88753148a6fec5ea1b4623aR446

**Comment by greg0ire** [comment]
@Koc are you stuck? If yes how can we help? Should we ask @cedricziel to make a PR?

**Comment by Koc** [comment]
@greg0ire just need more time to fix tests

File: Controller/CRUDController.php [hunk 9]
```diff
@@ -1349,6 +1348,28 @@ protected function preList(Request $request)
     }
 
     /**
+     * Sets the admin form theme to form view. Used for compatibility between Symfony versions.
+     *
+     * @param FormView $formView
+     */
+    protected function setFormTheme(FormView $formView)
```
Comment (core23) [inline Controller/CRUDController.php]: We still need a `private` method

File: Tests/Controller/HelperControllerTest.php [hunk 10]
```diff
@@ -328,6 +329,20 @@ public function testappendFormFieldElementAction($validatorInterface)
 
         $twig = new \Twig_Environment($this->getMock('\Twig_LoaderInterface'));
         $twig->addExtension(new FormExtension($mockRenderer));
+
+        if (Kernel::MAJOR_VERSION >= 3 && Kernel::MINOR_VERSION >= 2) {
```
Comment (core23) [inline Tests/Controller/HelperControllerTest.php]: Not sure, if we could rely on the kernel version.

cc @greg0ire

Comment (greg0ire) [inline Tests/Controller/HelperControllerTest.php]: We shouldn't. I'm currently waiting for the tests to pass, and then I think we should do a complete review, but yeah this is not the way to go. Detecting the presence of the public property might be a solution.

File: Controller/CRUDController.php (hunk 9 above)
Comment (Koc) [inline Controller/CRUDController.php]: This method can be useful for custom actions that extends from crud controller and used forms. We have a lot `setFormTheme` calls in our actions and for now they also not works anymore.

File: Tests/Controller/HelperControllerTest.php (hunk 10 above)
Comment (cedricziel) [inline Tests/Controller/HelperControllerTest.php]: Question: Why do you think it might be a bad idea to rely on `Kernel` to bring the version information? Maybe I'm mistaken, but those fields provide exactl the info we need. I'd rather switch to `Kernel::VERSION_ID >= 30200` though.

Comment (greg0ire) [inline Tests/Controller/HelperControllerTest.php]: Here is your answer right from the sf docs : https://symfony.com/doc/current/setup/bundles.html#updating-your-code-to-support-symfony-2-x-and-3-x-at-the-same-time

Comment (cedricziel) [inline Tests/Controller/HelperControllerTest.php]: Interesting-thank you for the link.

Comment (greg0ire) [inline Tests/Controller/HelperControllerTest.php]: You're very welcome :)

File: Controller/CRUDController.php (hunk 9 above)
Comment (core23) [inline Controller/CRUDController.php]: That's true, but we will remove the feature to set the form rendering in the controller. This will be done in the template files with the next major.

Comment (core23) [inline Controller/CRUDController.php]: See https://github.com/sonata-project/SonataAdminBundle/issues/4088

File: Tests/Controller/HelperControllerTest.php (hunk 10 above)
Comment (stof) [inline Tests/Controller/HelperControllerTest.php]: @cedricziel the bundle depends on individual packages, not on the fullstack repo (to give flexibility to users), but this allows to have different versions of each package. Kernel constants give you the version of HttpKernel, not of the Twig bridge

**Comment by wouterj** [comment]
Why not simply doing `$this->get('twig.form.renderer')->setTheme(...)` ? Anywhy, please fix Symfony 3.2 support soon :)

**Comment by nicolas-grekas** [comment]
Please test https://github.com/symfony/symfony/pull/20769

**Comment by greg0ire** [comment]
@nicolas-grekas [seems to work](https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/181472730), at least for our use case

**Comment by greg0ire** [comment]
@Koc : created a quick and dirty PR on your fork : https://github.com/Koc/SonataAdminBundle/pull/1 It should fix the build (it does locally for me). @nicolas-grekas : might be necessary to fix the proof PR for symfony/symfony#20769

**Comment by greg0ire** [comment]
People who want to help : please provide a clean way to detect `symfony/twig-bridge < 3.2`. I thought about `property_exists`, but then if the property is removed later, in 4.0,this will break. Maybe have a look at the twig bridge changelog to find something that can be detected.

**Comment by greg0ire** [comment]
I made [a PR on SonataCoreBundle](https://github.com/sonata-project/SonataCoreBundle/pull/364) with the required changes. Please review.

**Comment by Koc** [comment]
@greg0ire we can check for existence of https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/ContainerAwareRuntimeLoader.php class. This class not in twig bridge, but if it exists - `$twig->getRuntime()` most likely will return runtime instead of throwing exception.

File: Tests/Controller/HelperControllerTest.php (hunk 10 above)
Comment (greg0ire) [inline Tests/Controller/HelperControllerTest.php]: Based on [this changelog](https://github.com/symfony/twig-bridge/blob/master/CHANGELOG.md#320), [here is the detection trick I'd use](https://github.com/sonata-project/SonataCoreBundle/pull/364/files#diff-ab34013c1c5e23c243a5c45874748062R61)

**Comment by greg0ire** [comment]
@Koc : I found something in the changelog just now, see https://github.com/sonata-project/SonataAdminBundle/pull/4216#discussion_r91060974

**Comment by greg0ire** [comment]
TODO to get a green build : 

- [ ] merge https://github.com/Koc/SonataAdminBundle/pull/1
- [ ] merge https://github.com/sonata-project/SonataCoreBundle/pull/364
- [ ] make a new release for the core bundle

**Comment by Koc** [comment]
@greg0ire thank you for help with tests fix. I've merged your PR

**Comment by greg0ire** [comment]
Thank you for your work, hopefully we can fix this soon :)

**Comment by greg0ire** [comment]
@Koc : while waiting for the core bundle PR to get merged, here is another one for you : https://github.com/Koc/SonataAdminBundle/pull/2

**Comment by greg0ire** [comment]
Hmm… not sure why StyleCI wasn't fixed by applying the patch it suggested itself…

**Comment by greg0ire** [comment]
Triggering a new build. Let's pray :church:

**Comment by greg0ire** [comment]
Let's not celebrate prematurely, but it looks good :)

**Comment by greg0ire** [comment]
@Koc please fix the StyleCI build

**Comment by greg0ire** [comment]
Aaaand it's green! Congrats!

**Comment by Koc** [comment]
@greg0ire done

**Comment by Koc** [comment]
Have somewho tested it in real life application (not only unit tests)? does it really works?

**Comment by greg0ire** [comment]
@wouterj maybe you can? I don't have such an app lying around.

File: Tests/Controller/CRUDControllerTest.php [hunk 11]
```diff
@@ -187,6 +187,19 @@ protected function setUp()
                 }
             }));
 
+        $twig->expects($this->any())
+            ->method('getRuntime')
+            ->will($this->returnCallback(function ($name) use ($twigRenderer) {
+                switch ($name) {
+                    case 'Symfony\Bridge\Twig\Form\TwigRenderer':
```
Comment (greg0ire) [inline Tests/Controller/CRUDControllerTest.php]: A switch with one case… :confused:

**Comment by cedricziel** [comment]
Just test-drove it in a (rather minimal) sf 3.2 app. All nice and dandy so far.

**Comment by greg0ire** [comment]
@core23 @OskarStark please give this a final review and merge

**Comment by greg0ire** [comment]
@core23 @OskarStark this needs to be squash-merged (or at least, some of the commits should be squashed together)

**Comment by greg0ire** [comment]
@sonata-project/contributors : this is kind of a blocker. I'll merge this afternoon if you don't have anything to say.

**Comment by greg0ire** [comment]
[Squashed with a new commit message](https://github.com/sonata-project/SonataAdminBundle/commit/d8fc2edae14bc22d32e7d99990bcea54b626d01a)

**Comment by greg0ire** [comment]
Thanks @Koc ! And thanks everyone for testing / reviews !

**Comment by axzx** [comment]
Do you know, that this code
```
// set the theme for the current Admin Form
$this->get('twig')->getExtension('Symfony\Bridge\Twig\Extension\FormExtension')
          ->renderer->setTheme($view, $this->admin->getFormTheme());
```
works fine in Symfony 3.2.1?

**Comment by stof** [comment]
@axzx but it triggers deprecation warnings
