### PR TITLE
Deprecate ModelChoiceList

### LINKED ISSUE #4484: ModelChoiceList : SimpleChoiceList class has been removed in favor of ArrayChoiceList.
### Environment
Symfony >= 3.0.0
Sonata Admin 3.*

#### Sonata packages
Sonata Admin 3.*

## Subject

The Symfony\Component\Form\Extension\Core\ChoiceList\SimpleChoiceList class has been removed in favor of Symfony\Component\Form\ChoiceList\ArrayChoiceList. [[source upgrade to v3 symfony](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md)]

But the ModelChoiceList still has a[ reference on it](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/ChoiceList/ModelChoiceList.php#L18). 

(sorry, I don't have all the info about my config or how to reproduce but all the main info are here I think  )

### PR DESCRIPTION
**Pull request by jlamur**
I am targeting this branch, because this is a deprecation PR.

Closes #4484

## Changelog

```markdown
### Deprecated
- `ModelChoiceList` in favor of `ModelChoiceLoader`
```

### CODE REVIEW

File: Form/ChoiceList/ModelChoiceList.php [hunk 1]
```diff
@@ -20,7 +20,18 @@
 use Symfony\Component\PropertyAccess\PropertyAccessorInterface;
 use Symfony\Component\PropertyAccess\PropertyPath;
 
+@trigger_error(
+    'The '.__NAMESPACE__.'\ModelChoiceList class is deprecated since SF 2.7,'.
```
Comment (OskarStark) [inline Form/ChoiceList/ModelChoiceList.php]: no `,`

The Message looks good to me

**Comment by jlamur** [comment]
@OskarStark Why did you add a *Upgrade note* label? Do you want me to add a subject to the PR?

**Comment by OskarStark** [comment]
You need to add something to our `UPGRADE.md` file, how the user can avoid getting this deprecation warning

File: Form/ChoiceList/ModelChoiceList.php [hunk 2]
```diff
@@ -20,7 +20,18 @@
 use Symfony\Component\PropertyAccess\PropertyAccessorInterface;
 use Symfony\Component\PropertyAccess\PropertyPath;
 
+@trigger_error(
+    'The '.__NAMESPACE__.'\ModelChoiceList class is deprecated since SF 2.7'.
```
Comment (greg0ire) [inline Form/ChoiceList/ModelChoiceList.php]: You can use `__CLASS__` here

Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: > since SF 2.7

The deprecation is wrong. You are deprecated a Sonata code, note a Symfony code.

Please review guidelines about deprecations: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#the-base-branch

**Comment by Soullivaneuh** [comment]
@OskarStark wrong label. Deprecation are on minor releases, not patches. Please be careful with that.

File: Form/ChoiceList/ModelChoiceList.php (hunk 2 above)
Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: Should not this deprecation be on the class constructor? We might have a lot of useless deprecation notice in this place. Am I right?

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: Are you sure that this will trigger useless deprecation notices? AFAIK, the file is included by the autoloader only when you use the class defined in it.

Deprecations are also triggered this way in Symfony repository (c.f. https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Form/Extension/Core/ChoiceList/SimpleChoiceList.php#L14).

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: Is this message ok `The XXX class is deprecated since 3.21 and will be removed when bumping requirement to SF 2.7+`? If it's not could you please help me writing this deprecation message?

Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: Indeed, and this one does not seem to be added to compilation: https://github.com/sonata-project/SonataAdminBundle/blob/7cfd7470ee2f532844e3376e6bbed5d1ef614979/DependencyInjection/SonataAdminExtension.php#L285

Should be OK I guess.

Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: @jlamur not really, please see examples from the documentation.

Should be something like "deprecated since 3.x and will be removed in 4.0".

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: @Soullivaneuh So if I understand right, Sonata will drop SF < 2.7 support in 4.0? It did not found anything that mention it.

Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: Certainly, but this is not the issue. As far you deprecate any class on the sonata code, this means it would be removed on next major.

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: @Soullivaneuh That's the issue. If you remove the `ModelChoiceList` class in 4.0 but still support SF < 2.7 in 4.0, then the `ModelChoiceLoader` class will not be usable by SF < 2.7 setups. Because the class `ArrayChoiceList` (which is used in the `ModelChoiceLoader` [here](https://github.com/sonata-project/SonataAdminBundle/blob/1d9ef6e/Form/ChoiceList/ModelChoiceLoader.php#L133)) exists only since SF >= 2.7.

In case Sonata 4.0 does not drop SF 2.7 support, that means I need to override the call to `ArrayChoiceList` class, to check if it exists, and fallback to `SimpleChoiceList` class if it does not.

Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: Right. But in any case, I confirm: next major will support SF 2.8+ only: https://github.com/sonata-project/dev-kit/issues/51

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: done

Comment (jlamur) [inline Form/ChoiceList/ModelChoiceList.php]: done

**Comment by jlamur** [comment]
@Soullivaneuh @greg0ire ready for review!

File: Form/ChoiceList/ModelChoiceList.php [hunk 3]
```diff
@@ -20,7 +20,18 @@
 use Symfony\Component\PropertyAccess\PropertyAccessorInterface;
 use Symfony\Component\PropertyAccess\PropertyPath;
 
+@trigger_error(
+    'The '.__CLASS__.' class is deprecated since 3.x'.
+    ' and will be removed in 4.0.'
```
Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: This part could be merged with the first line.

And normally, error message should be one-lined, but I guess I'm the only one of @sonata-project/contributors taking care of that. Meh.

File: Form/ChoiceList/ModelChoiceList.php [hunk 4]
```diff
@@ -20,7 +20,18 @@
...
+    .' Use '.__NAMESPACE__.'\ModelChoiceLoader instead.',
+    E_USER_DEPRECATED
+);
+
 /**
+ * NEXT_MAJOR: Remove this class.
+ *
+ * @deprecated Use Sonata\AdminBundle\ModelChoiceLoader instead
```
Comment (Soullivaneuh) [inline Form/ChoiceList/ModelChoiceList.php]: `@deprected Since 3.x, to be removed in 4.0. Use ...`

File: UPGRADE-3.x.md [hunk 5]
```diff
@@ -1,6 +1,15 @@
 UPGRADE 3.x
 ===========
 
+## Deprecated ModelChoiceList class in favor of ModelChoiceLoader
+
+The `ModelChoiceList` class is no longer supported. Please use the
+`ModelChoiceLoader` class instead.
```
Comment (Soullivaneuh) [inline UPGRADE-3.x.md]: One line this part please.

**Comment by jlamur** [comment]
@Soullivaneuh please review again!

**Comment by OskarStark** [comment]
Thanks @jlamur 👍
