### PR TITLE
Calls to AbstractAdmin::getTemplate put back

### LINKED ISSUE #5065: BC Break 3.33 to 3.34 ?
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.34.1 3.34.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.5.0  3.5.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.0.8             v4.0.8             Symfony Asset Component
symfony/browser-kit          v4.0.8             v4.0.8             Symfony BrowserKit Component
symfony/cache                v4.0.8             v4.0.8             Symfony Cache component with PSR-6, PSR-16, and tags
symfony/class-loader         v3.4.8             v3.4.8             Symfony ClassLoader Component
symfony/config               v4.0.8             v4.0.8             Symfony Config Component
symfony/console              v4.0.8             v4.0.8             Symfony Console Component
symfony/css-selector         v4.0.8             v4.0.8             Symfony CssSelector Component
symfony/debug                v4.0.8             v4.0.8             Symfony Debug Component
symfony/debug-bundle         v4.0.8             v4.0.8             Symfony DebugBundle
symfony/debug-pack           v1.0.5             v1.0.5             A debug pack for Symfony projects
symfony/dependency-injection v4.0.8             v4.0.8             Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.0.8             v4.0.8             Symfony Doctrine Bridge
symfony/dom-crawler          v4.0.8             v4.0.8             Symfony DomCrawler Component
symfony/dotenv               v4.0.8             v4.0.8             Registers environment variables from a .env file
symfony/event-dispatcher     v4.0.8             v4.0.8             Symfony EventDispatcher Component
symfony/expression-language  v4.0.8             v4.0.8             Symfony ExpressionLanguage Component
symfony/filesystem           v4.0.8             v4.0.8             Symfony Filesystem Component
symfony/finder               v4.0.8             v4.0.8             Symfony Finder Component
symfony/flex                 v1.0.78            v1.0.78
symfony/form                 v4.0.8             v4.0.8             Symfony Form Component
symfony/framework-bundle     v4.0.8             v4.0.8             Symfony FrameworkBundle
symfony/http-foundation      v4.0.8             v4.0.8             Symfony HttpFoundation Component
symfony/http-kernel          v4.0.8             v4.0.8             Symfony HttpKernel Component
symfony/inflector            v4.0.8             v4.0.8             Symfony Inflector Component
symfony/intl                 v4.0.8             v4.0.8             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/lts                  dev-master 6de50b2 dev-master 6de50b2 Enforces Long Term Supported versions of Symfony components
symfony/maker-bundle         v1.3.1             v1.3.1             Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bridge       v4.0.8             v4.0.8             Symfony Monolog Bridge
symfony/monolog-bundle       v3.2.0             v3.2.0             Symfony MonologBundle
symfony/options-resolver     v4.0.8             v4.0.8             Symfony OptionsResolver Component
symfony/orm-pack             v1.0.5             v1.0.5             A pack for the Doctrine ORM
symfony/phpunit-bridge       v4.0.8             v4.0.8             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu    v1.7.0             v1.7.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.7.0             v1.7.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.7.0             v1.7.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/process              v4.0.8             v4.0.8             Symfony Process Component
symfony/profiler-pack        v1.0.3             v1.0.3             A pack for the Symfony web profiler
symfony/property-access      v4.0.8             v4.0.8             Symfony PropertyAccess Component
symfony/property-info        v4.0.8             v4.0.8             Symfony Property Info Component
symfony/routing              v4.0.8             v4.0.8             Symfony Routing Component
symfony/security             v4.0.8             v4.0.8             Symfony Security Component
symfony/security-acl         v3.0.1             v3.0.1             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.0.8             v4.0.8             Symfony SecurityBundle
symfony/serializer           v4.0.8             v4.0.8             Symfony Serializer Component
symfony/serializer-pack      v1.0.1             v1.0.1             A pack for the Symfony serializer
symfony/stopwatch            v4.0.8             v4.0.8             Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.2             v3.2.2             Symfony SwiftmailerBundle
symfony/templating           v4.0.8             v4.0.8             Symfony Templating Component
symfony/translation          v4.0.8             v4.0.8             Symfony Translation Component
symfony/twig-bridge          v4.0.8             v4.0.8             Symfony Twig Bridge
symfony/twig-bundle          v4.0.8             v4.0.8             Symfony TwigBundle
symfony/validator            v4.0.8             v4.0.8             Symfony Validator Component
symfony/var-dumper           v4.0.8             v4.0.8             Symfony mechanism for exploring and dumping PHP variables
symfony/web-link             v4.0.8             v4.0.8             Symfony WebLink Component
symfony/web-profiler-bundle  v4.0.8             v4.0.8             Symfony WebProfilerBundle
symfony/web-server-bundle    v4.0.8             v4.0.8             Symfony WebServerBundle
symfony/webpack-encore-pack  v1.0.2             v1.0.2             A pack for Symfony Encore
symfony/yaml                 v4.0.8             v4.0.8             Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

## Actual results

This code works in Sonata 3.33 and does not work on 3.34 anymore. I don't get any error message, but the new template  is not loaded and the old one continues to be displayed. The main reason is that this function is not used in the new version, but it was in the previous ones. So this might be a BC break

```php
<?php

namespace App\Admin;
/* ... */
class PageAdmin extends AbstractAdmin
{

/* ... */

    /**
     * @param string $name
     * @return mixed|null|string
     */
    public function getTemplate($name)
    {
        dump("this will never be called");
        switch ($name) {
            case 'edit':
                return 'admin/cms/cms_edit.html.twig';
                break;

            default:
                return parent::getTemplate($name);
                break;
        }
    }
}
```

### PR DESCRIPTION
**Pull request by TimoBakx**
I am targeting this branch, because this is a fix to a BC breaking change.

Closes #5065

## Changelog

```markdown
### Fixed
- Fixed a BC break where an overwritten `getTemplate()` method in an `Admin`
was no longer called by Sonata.
```

## Subject

Changes in PR #4980 introduced a BC break: the `AbstractAdmin` method `getTemplate()` was no longer called (all calls to that method were replaced with calls to the `TemplateRegistry::getTemplate()` method).

As @FabienPapet pointed out, people may override the `AbstractAdmin::getTemplate()` method to use different templates than the defaults.
Because that method is no longer called, the system reverts back to using the default templates. This is a BC break.

I replaced all admin-specific calls to `TemplateRegistry::getTemplate()` with calls to `AbstractAdmin::getTemplate()`. The original calls are commented out, so they may be re-used at the next major update.

### CODE REVIEW

File: src/Admin/AbstractAdmin.php [hunk 1]
```diff
@@ -2556,7 +2556,9 @@ public function configureActionButtons($action, $object = null)
             && $this->hasRoute('create')
         ) {
             $list['create'] = [
-                'template' => $this->getTemplateRegistry()->getTemplate('button_create'),
+                // NEXT_MAJOR: Remove this line and use commented line below it instead
+                'template' => $this->getTemplate('button_create'),
```
Comment (greg0ire) [inline src/Admin/AbstractAdmin.php]: Can we detect the override, trigger a deprecation if it exists and call the registry otherwise?

Comment (greg0ire) [reply src/Admin/AbstractAdmin.php]: A dedicated final method may be added in the admin just to do that check

Comment (FabienPapet) [reply src/Admin/AbstractAdmin.php]: Detecting overrides in AbstractAdmin::getTemplate` may not be that easy without the use of the ReflectionClass which slows down the application.

Comment (greg0ire) [reply src/Admin/AbstractAdmin.php]: You're right and besides, all `getTemplate` does now is calling the registry, so nevermind my comment.

**Comment by greg0ire** [comment]
Thanks @TimoBakx !
