### PR TITLE
Better handling of ChoiceFieldMaskType option 'map'

### LINKED ISSUE #4127: sonata_type_choice_field_mask doesn't work in expanded mode
When you use a sonata_type_choice_field_mask form field with the option `'expanded' => true` (causing it to generate radio buttons instead of a select list), the rendered jQuery code to handle this behaviour doesn't work anymore. It appears to be completely written to work for a select element only.

I guess expanded should be supported as well here.

Not sure if multiple should be supported here, since the field mapping would maybe required a single selection mode.

### LINKED ISSUE #4717: Warning: array_merge() expects at least 1 parameter, 0 given
https://github.com/sonata-project/SonataAdminBundle/blob/caab4a84a2146c0109de7f22550a41af0be72706/Form/Type/ChoiceFieldMaskType.php#L38

If the second is null something like this: call_user_func_array('array_merge', array())
Next action is : array_merge()
Error: So this throws error

### PR DESCRIPTION
**Pull request by TimoBakx**
I am targeting this branch, because this is a minor, BC fix.

Closes #4717
Closes #4127

## Changelog

```markdown

### Fixed
- Fixed PHP warnings when `ChoiceFieldMaskType` option `map` is invalid or empty
- Fixed javascript handling of `ChoiceFieldMaskType` when option `expanded` is `true`

```

## Subject

The `ChoiceFieldMaskType` option `map` was not handled safely enough:
- It gave a `Warning: array_merge() expects at least 1 parameter, 0 given` if the option was not set or was set to an empty array.
- It gave a `Warning: Invalid argument supplied for foreach()` if the option was anything but an array.

Also, the javascript function to show/hide fields did not work if the `ChoiceFieldMaskType` field was expanded (radio buttons instead of a select).

I changed the following:
- Set the allowed types for the `map` option to array only.
- Added a check before the `array_merge` call, so empty arrays will no longer cause problems.
- Fixed the javascript handling, so the code also works with expanded choice fields.

### CODE REVIEW

File: src/Form/Type/ChoiceFieldMaskType.php [hunk 1]
```diff
@@ -33,8 +33,11 @@ public function buildView(FormView $view, FormInterface $form, array $options)
             }
         }
 
-        $allFieldNames = call_user_func_array('array_merge', $sanitizedMap);
-        $allFieldNames = array_unique($allFieldNames);
+        $allFieldNames = [];
+        if ([] !== $sanitizedMap) {
```
Comment (jordisala1991) [inline src/Form/Type/ChoiceFieldMaskType.php]: why is this if needed?

Comment (TimoBakx) [reply src/Form/Type/ChoiceFieldMaskType.php]: If `$santizedMap` is an empty array, `call_user_func_array('array_merge', $sanitizedMap)` will throw a `Warning: array_merge() expects at least 1 parameter, 0 given`.

File: tests/Form/Type/ChoiceFieldMaskTypeTest.php [hunk 2]
```diff
@@ -13,30 +13,57 @@
...
+            'boolean' => [false],
+            'string' => ['string'],
+            'class' => [new \stdClass()],
+        ];
+    }
+
+    /**
+     * @dataProvider setAllowedTypesProvider
+     *
+     * @param $map
```
Comment (greg0ire) [inline tests/Form/Type/ChoiceFieldMaskTypeTest.php]: Please remove this

File: tests/Form/Type/ChoiceFieldMaskTypeTest.php [hunk 3]
```diff
@@ -48,4 +75,66 @@ public function testGetParent()
...
+                'field5',
+            ],
+        ];
+
+        $this->assertSame(array_values($expectedAllFields), array_values($view->reveal()->vars['all_fields']));
+        $this->assertSame($expectedMap, $view->reveal()->vars['map']);
+    }
+
+    /**
+     * @param array $options
```
Comment (greg0ire) [inline tests/Form/Type/ChoiceFieldMaskTypeTest.php]: Please remove this and add a type hint

File: src/Form/Type/ChoiceFieldMaskType.php (hunk 1 above)
Comment (jordisala1991) [reply src/Form/Type/ChoiceFieldMaskType.php]: The only problem here is even if the array is not empty, if the value of each item is not an array it will still fail.

Comment (jordisala1991) [reply src/Form/Type/ChoiceFieldMaskType.php]: Question, what code is easier to understand (I don't have an opinion yet):

```
        $allFieldNames = [];
        if ([] !== $sanitizedMap) {
            $allFieldNames = call_user_func_array('array_merge', $sanitizedMap);
            $allFieldNames = array_unique($allFieldNames);
        }
```

or:

```
$allFieldNames = array_unique(array_reduce($sanitizedMap, function($carry, $value) {
    return array_merge($carry, is_array($value) ? $value : []);
}, []));
```

or:

```
$allFieldNames = [];
foreach ($sanitizedMap as $value) {
    if (is_array($value)) {
        $allFieldNames = array_merge($allFieldNames, $value);
    }
}
$allFieldNames = array_unique($allFieldNames);
```

Comment (greg0ire) [reply src/Form/Type/ChoiceFieldMaskType.php]: How about `$allFieldNames = array_merge(...$sanitizedMap);`?

Comment (TimoBakx) [reply src/Form/Type/ChoiceFieldMaskType.php]: I think the last one is easiest to understand. I do like the version @greg0ire suggested. I'll run some tests to see if it'll work in all cases.

Comment (jordisala1991) [reply src/Form/Type/ChoiceFieldMaskType.php]: it fails on my test: https://3v4l.org/sDsvL

Comment (greg0ire) [reply src/Form/Type/ChoiceFieldMaskType.php]: Ah right, needs array values https://3v4l.org/b6sdI

Comment (TimoBakx) [reply src/Form/Type/ChoiceFieldMaskType.php]: I'll also set up a unit test to test weird values in the second layer of the `$map` array.

Comment (TimoBakx) [reply src/Form/Type/ChoiceFieldMaskType.php]: Thank you both for your feedback and insights. I changed the code and added a unit test to test for unexpected values.

File: src/Form/Type/ChoiceFieldMaskType.php [hunk 4]
```diff
@@ -27,14 +27,14 @@ public function buildView(FormView $view, FormInterface $form, array $options)
     {
         $sanitizedMap = [];
         foreach ($options['map'] as $value => $fieldNames) {
-            foreach ($fieldNames as $fieldName) {
-                $sanitizedMap[$value][] =
-                    str_replace(['__', '.'], ['____', '__'], $fieldName);
+            if (is_array($fieldNames)) {
+                foreach ($fieldNames as $fieldName) {
+                    $sanitizedMap[$value][] = str_replace(['__', '.'], ['____', '__'], $fieldName);
```
Comment (jordisala1991) [inline src/Form/Type/ChoiceFieldMaskType.php]: wouldn't it be better to just add the value on the `allFieldNames` here directly, and then only do a `array_unique` after?

File: src/Form/Type/ChoiceFieldMaskType.php [hunk 5]
```diff
@@ -26,14 +26,17 @@ class ChoiceFieldMaskType extends AbstractType
...
+                    $sanitizedMap[$value][] = $sanitizedFieldName;
+                    $allFieldNames[] = $sanitizedFieldName;
+                }
             }
         }
 
-        $allFieldNames = call_user_func_array('array_merge', $sanitizedMap);
         $allFieldNames = array_unique($allFieldNames);
 
         $view->vars['all_fields'] = $allFieldNames;
```
Comment (jordisala1991) [inline src/Form/Type/ChoiceFieldMaskType.php]: you can do the array_unique here to simplify even more

File: src/Form/Type/ChoiceFieldMaskType.php [hunk 6]
```diff
@@ -26,14 +26,17 @@ class ChoiceFieldMaskType extends AbstractType
     public function buildView(FormView $view, FormInterface $form, array $options)
     {
         $sanitizedMap = [];
+        $allFieldNames = [];
         foreach ($options['map'] as $value => $fieldNames) {
-            foreach ($fieldNames as $fieldName) {
-                $sanitizedMap[$value][] =
-                    str_replace(['__', '.'], ['____', '__'], $fieldName);
+            if (is_array($fieldNames)) {
```
Comment (jordisala1991) [inline src/Form/Type/ChoiceFieldMaskType.php]: I am not sure about this if, the ideal would be to use is_iterable but that function is only php 7.1. The foreach also works with objects.

Comment (jordisala1991) [reply src/Form/Type/ChoiceFieldMaskType.php]: https://github.com/symfony/polyfill-php71/blob/master/Php71.php#L23

What about adding this second condition?

**Comment by jordisala1991** [comment]
Thank you @TimoBakx !

**Comment by TimoBakx** [comment]
Thank you for the reviews and patience.

**Comment by johnpancoast** [comment]
Do you guys know when this fix will end up in a tagged 3.x release? I'm trying to use a choice mask with an expanded radio and can't and it looks likes this fixes that.

Unfortunately, I cannot temporarily use dev-master either since this app is not (yet) on PHP 7 which dev-master depend on.

**Comment by kunicmarko20** [comment]
You can use `3.x-dev` until release
