### PR TITLE
fix issue with integer indexed form children

### LINKED ISSUE #7984: Type error caused by `FormBuilderIterator`
### Environment

- PHP 8.1
- latest Symfony 6.1
- latest Sonata packages

## Subject

Type error caused by `FormBuilderIterator`

## Minimal repository with the bug

?

## Steps to reproduce

I have an inline admin where I can add new items in a table view. If I press the "add" button then I get a type error since I moved to Symfony 6. It worked fine with Symfony 5.4 as there was no `string` typehint on Symfony's `FormBuilder::get`.

## Actual results

Screenshot from 2022-12-08 13-09-45

A dump of

```php
    public function current(): FormBuilderInterface
    {
        if ($this->iterator->current() === 0) {
            dd($this);
        }

        return $this->formBuilder->get($this->iterator->current());
    }
``` 

Screenshot from 2022-12-08 13-10-26

From what I can tell we cannot guarantee that `$this->iterator->current()` within `FormBuilderIterator` will actually be a string. In my case its an integer and this seems legit. The problematic form field is an expanded choice field with checkboxes and the children of this form are indexed with integers.

I checked it and casting to string there solves the issue for me. Shall I create a PR for this?

```php
    public function current(): FormBuilderInterface
    {
        return $this->formBuilder->get((string) $this->iterator->current());
    }
```

### PR DESCRIPTION
**Pull request by dmaicher**
## Subject

I am targeting this branch, because its BC and a bug fix.

Closes https://github.com/sonata-project/SonataAdminBundle/issues/7984

## Changelog

```markdown
### Fixed
- fixed an issue with integer indexed form children within `FormBuilderIterator`
```

### CODE REVIEW

File: tests/Util/FormBuilderIteratorTest.php [hunk 1]
```diff
@@ -53,4 +54,11 @@ public function testHasChildren(): void
         $iterator = new FormBuilderIterator($this->builder);
         static::assertTrue($iterator->hasChildren());
     }
+
+    public function testCurrentWithIntegerIndexedChildren(): void
```
Comment (dmaicher) [inline tests/Util/FormBuilderIteratorTest.php:58]: this fails without the fix

```
There was 1 error:

1) Sonata\AdminBundle\Tests\Util\FormBuilderIteratorTest::testCurrentWithIntegerIndexedChildren
TypeError: Symfony\Component\Form\FormBuilder::get(): Argument #1 ($name) must be of type string, int given, called in /var/www/SonataAdminBundle/src/Util/FormBuilderIterator.php on line 67

/var/www/SonataAdminBundle/vendor/symfony/form/FormBuilder.php:91
/var/www/SonataAdminBundle/src/Util/FormBuilderIterator.php:67
/var/www/SonataAdminBundle/tests/Util/FormBuilderIteratorTest.php:62
/var/www/SonataAdminBundle/vendor/phpunit/phpunit/src/Framework/TestResult.php:728
/var/www/SonataAdminBundle/vendor/phpunit/phpunit/src/Framework/TestSuite.php:673
/var/www/SonataAdminBundle/vendor/phpunit/phpunit/src/Framework/TestSuite.php:673
/var/www/SonataAdminBundle/vendor/phpunit/phpunit/src/Framework/TestSuite.php:673

**Comment by dmaicher** [comment]
Weird failures seem unrelated

**Comment by VincentLanglet** [comment]
> Weird failures seem unrelated

Might be related to https://github.com/symfony/symfony/issues/48422

Should be skip the test for now ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by VincentLanglet** [comment]
I'll take care of psalm
