### PR TITLE
Fixed error 500 when requesting short object description as json

### LINKED ISSUE #5202: GetShortObjectDescriptionAction fails returning JsonResponse
#### Sonata packages

```
sonata-project/admin-bundle              3.38.2 3.38.2 The missing Symfony Admin Generator      
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.11.2 3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.1  3.6.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
sonata-project/formatter-bundle          3.5.0  3.5.0  Symfony SonataFormatterBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle

```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.2  v3.3.0 Symfony MonologBundle
symfony/phpunit-bridge     v4.1.3  v4.1.3 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.9.0  v1.9.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.9.0  v1.9.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.9.0  v1.9.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.9.0  v1.9.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.9.0  v1.9.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.9.0  v1.9.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.9.0  v1.9.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.9.0  v1.9.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.2  v3.2.2 Symfony SwiftmailerBundle
symfony/symfony            v3.4.14 v4.1.3 The Symfony PHP framework
symfony/var-dumper         v4.1.3  v4.1.3 Symfony mechanism for exploring and dumping PHP variables

```

#### PHP version

```
$ php -v
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

```

## GetShortObjectDescriptionAction fails returning JsonResponse

When trying to get object description as json error 500 is thrown. 

https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Action/GetShortObjectDescriptionAction.php#L76

```php
return new JsonResponse(['result' => [
    'id' => $admin->id($object),
    'label' => $admin->toString($object),
]);
```

You forgot to use JsonResponse in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Action/GetShortObjectDescriptionAction.php#L14

```diff
use Sonata\AdminBundle\Admin\Pool;
+ use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Twig\Environment;
```

### PR DESCRIPTION
**Pull request by jdeveloper**
Closes #5202 

## Changelog
```markdown
### Fixed
- issue Error 500 when requesting short object description as JSON
```

### CODE REVIEW

File: src/Action/GetShortObjectDescriptionAction.php [hunk 1]
```diff
@@ -68,7 +69,7 @@ public function __invoke(Request $request)
 
         $object = $admin->getObject($objectId);
 
-        if (!$object && 'html' == $request->get('_format')) {
+        if (!$object && in_array($request->get('_format'), ['html', 'json'])) {
```
Comment (kunicmarko20) [inline src/Action/GetShortObjectDescriptionAction.php]: It will never get to:

```
if ('json' == $request->get('_format')) {
             return new JsonResponse(['result' => [
                 'id' => $admin->id($object),
                 'label' => $admin->toString($object),
             ]]);
         }
```

Why did you add json here?

Comment (kunicmarko20) [inline src/Action/GetShortObjectDescriptionAction.php]: Why did you add `json` here?

Comment (kunicmarko20) [reply src/Action/GetShortObjectDescriptionAction.php]: Got it now that I expanded whole code.

Comment (jdeveloper) [reply src/Action/GetShortObjectDescriptionAction.php]: I did not knew if always return empty response when object is not found or just in html or json format.

Comment (jdeveloper) [reply src/Action/GetShortObjectDescriptionAction.php]: I you want I'll change it to return always an empty response. Or perhaps an 404.

Comment (kunicmarko20) [reply src/Action/GetShortObjectDescriptionAction.php]: Does it throw an exception if `$object` is null and the format is `json` before your change?

**Comment by jdeveloper** [comment]
I don't know why I get this error https://flintci.io/repositories/61/analyses/9959

I tried to put the use sentences in alphabetical order.

**Comment by kunicmarko20** [comment]
Because you added it to test class but you don't use it

File: src/Action/GetShortObjectDescriptionAction.php (hunk 1 above)
Comment (kunicmarko20) [reply src/Action/GetShortObjectDescriptionAction.php]: I just checked and it shouldn't throw an exception, but it will return empty results as JSON, please revert this line.

Comment (jdeveloper) [reply src/Action/GetShortObjectDescriptionAction.php]: I thought  it would make no sens to return
{
   "id": "",
   "label": ""
}

**Comment by jdeveloper** [comment]
Oh, thanks.

My fault, since I added and used it in the Action class I copied it over to the test.

File: src/Action/GetShortObjectDescriptionAction.php (hunk 1 above)
Comment (kunicmarko20) [reply src/Action/GetShortObjectDescriptionAction.php]: Change it now is a BC Break, but I agree that it makes no sense, cc @sonata-project/contributors

Comment (jdeveloper) [reply src/Action/GetShortObjectDescriptionAction.php]: ok, I'll change it to return it this way

**Comment by greg0ire** [comment]
That's because of a new version of php-cs-fixer

**Comment by greg0ire** [comment]
Blocked by #5205

**Comment by jdeveloper** [comment]
I'll wait until it's merged in master than I'll rebase.

Thanks

**Comment by greg0ire** [comment]
I think you actually don't need to rebase, I will restart the failing job and only that one.

**Comment by greg0ire** [comment]
I restarted the relevant job.

**Comment by greg0ire** [comment]
Thanks @jdeveloper

**Comment by jdeveloper** [comment]
@greg0ire it was a pleasure.

Thanks for tagging it so fast in 3.x so we don't have to downgrade the version

**Comment by OskarStark** [comment]
Thank you for your contribution 👍
