### PR TITLE
Fix error on getNewInstance() when parent object property in uninitialised.

### LINKED ISSUE #7703: Setting the parent object when creating a new instance gives error with uninitialised property (PHP >=7.4)
### Environment

PHP 7.4
Symfony 4.4
Sonata Admin 3

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle 3.107.1 3.107.1
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
symfony/property-info   v4.4.31 v4.4.31 
```

</p>
</details>

#### PHP version

```
$ php -v
PHP 7.4.13 (cli) (built: Dec  1 2020 04:25:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

## Subject

When Sonata Admin is setting a parent object on a child object when creating a new instance of the child object, Symfony Property Access gives an `\Symfony\Component\PropertyAccess\Exception\AccessException` because of an uninitialised property when having a typed non-nullable uninitialised property.

## Steps to reproduce

I have a parent-child 1:n relation between two entities and also a parent and child admin configured. I recently updated my code to call `addChild()` on the parent admin with the second parameter set (to remove deprecations).

The child entity needs to have a parent entity set, so I have written my PHP code as such:

```php
class Child {
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ParentEntity", inversedBy="child")
     * @ORM\JoinColumn(onDelete="CASCADE", nullable=false)
     */
    private ParentEntity $parent;

    public function getParent(): ParentEntity { return $this->parent; }

    public function setParent(ParentEntity $parent): void { $this->parent = $parent; }
}
```

Parent could be something like:
```php
class ParentEntity {
    /**
     * @var Collection<int, Child>
     * @ORM\OneToMany(targetEntity="App\Entity\Child", mappedBy="parent", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    public Collection $children;

    /* public functions getChildren, setChildren, addChild, removeChild etc. */
}
```

In admin services definition for the parent entity admin:
```yaml
        calls:
            - [addChild, ['@app.admin.child_admin', 'parent']]
```

## Actual results

Now when Sonata Admin is setting the parent object when creating a new instance, Symfony Property Access gives an error because of an uninitialised property:

> **\Symfony\Component\PropertyAccess\Exception\AccessException**
> The property "App\Entity\Child::$parent" is not readable because it is typed "App\Entity\ParentEntity". You should initialize it or declare a default value instead.

## Expected results

I do not want to make my properties nullable and initialise them with a `null` value. Neither do I want to initialise the property in the constructor with `$this->parent = new ParentEntity();`.

Sonata Admin should not need to get the property to set it or a least should not error out on this.

## Possible solution

`\Symfony\Component\PropertyAccess\Exception\AccessException` is only being thrown when the property cannot be read because it has not been initialised. We could wrap the specific line that is responsible for this error with a `try { } catch(AccessException $e)`:

```diff
-                $value = $propertyAccessor->getValue($object, $propertyPath);
+                try {
+                    $value = $propertyAccessor->getValue($object, $propertyPath);
+                } catch(\Symfony\Component\PropertyAccess\Exception\AccessException $e) {
+                    // Symfony PropertyAccess failed to get the value because the property is uninitialised. Set value to null.
+                    $value = null;
+                }
```

### PR DESCRIPTION
**Pull request by 7ochem**
## Subject

When creating a new object instance, the admin will check if there is a parent object that needs to be appended. The appendParentObject() method will check the current value of the property that holds the parent object. But if this property is typed and not yet initialised, Symfony's PropertyAccess will throw an AccessException. This fix catches that exception and continues as if the current value is `null`.

Note:
I'm catching `\Symfony\Component\PropertyAccess\Exception\AccessException`. The `\Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException` (child of `AccessException`) was introduced in Symfony 5.1 and thus not yet available in Symfony 4.4.

I am targeting the 3.x branch, because this is a bug.

Closes #7703.

## Changelog

```markdown
### Fixed
- Catch AccessException in AbstractAdmin::appendParentObject() to prevent an error when the property for the parent object is uninitialised.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
> Note: I'm catching `\Symfony\Component\PropertyAccess\Exception\AccessException`. The `\Symfony\Component\PropertyAccess\Exception\UninitializedPropertyException` (child of `AccessException`) was introduced in Symfony 5.1 and thus not yet available in Symfony 4.4.

Can you add a TODO comment to change to `UninitializedPropertyException` when dropping support for Symfony < 5.1 ?

**Review by VincentLanglet — DISMISSED** [review]

File: src/Admin/AbstractAdmin.php [hunk 1]
```diff
@@ -3953,7 +3954,13 @@ final protected function appendParentObject(object $object): void
                 $propertyAccessor = PropertyAccess::createPropertyAccessor();
                 $propertyPath = new PropertyPath($this->getParentAssociationMapping());
 
-                $value = $propertyAccessor->getValue($object, $propertyPath);
+                try {
+                    $value = $propertyAccessor->getValue($object, $propertyPath);
+                } catch (AccessException $e) {
```
Comment (jordisala1991) [inline src/Admin/AbstractAdmin.php:3960]: what happens if the entity does not have the getParent method? Would this try catch hide some potential problems?

Comment (VincentLanglet) [reply src/Admin/AbstractAdmin.php:3960]: I would say yes because "noSuchPropertyException" extends AccessException...

Dunno if we can filter the right case we want until support for Sf4.4 is dropped.

Should we check the message of the exception until the use of the new exception ?

Comment (7ochem) [reply src/Admin/AbstractAdmin.php:3960]: PropertyAccessor throws this exception in 3 cases:

1. The getter is used but a native PHP `\Error` was catched by PropertyAccessor, the PHP version is >= 7.4 and the message of the error is "Typed property .... must not be accessed before initialization"
1. The property is public and PropertyAccessor detects that is was not set (not initialised)
1. The getter is used but a native PHP `\TypeError` was catched by PropertyAccessor and the message of the error is "Return value ... must be of type ..., null returned" (in which case the property is untyped and uninitialised and the getter return type is not nullable)

> what happens if the entity does not have the getParent method? Would this try catch hide some potential problems?

In case the property exists and is private/protected but the `getParent` method does not exist (or is private/protected) a `\Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException` is thrown.

Comment (VincentLanglet) [reply src/Admin/AbstractAdmin.php:3960]: > NoSuchPropertyException

`NoSuchPropertyException extends AccessException` so it's caught too by your try/catch.
Same for `NoSuchIndexException`.

Maybe we should add a check `if ($e instanceof NoSuchPropertyException || $e instanceof NoSuchIndexException) throw $e`.

Comment (7ochem) [reply src/Admin/AbstractAdmin.php:3960]: > I would say yes because "noSuchPropertyException" extends AccessException...
> 
> Dunno if we can filter the right case we want until support for Sf4.4 is dropped.
> 
> Should we check the message of the exception until the use of the new exception ?

Ok... sharp, I've overlooked that "detail" 😄 

I could add:

```php
if (!$e instanceof UninitializedPropertyException && get_class($e) !== AccessException::class) {
    throw $e; // Re-throw. We only want to "ignore" AccessException (Sf < 5.1) and UninitializedPropertyException (Sf >= 5.1)
}
```

Comment (VincentLanglet) [reply src/Admin/AbstractAdmin.php:3960]: Yes, I think it would be better with this re-throw

Comment (7ochem) [reply src/Admin/AbstractAdmin.php:3960]: Ok done. I also updated the todo message for this slightly.

Comment (VincentLanglet) [reply src/Admin/AbstractAdmin.php:3960]: Linter are failing

Comment (7ochem) [reply src/Admin/AbstractAdmin.php:3960]: I fixed this one thing in my code, but now PHP CS Fixer is failing on other things. It is using PHP CS Fixer 3.5.0 which has been released 9 hours ago, so maybe this is a bug in that new release

I see FriendsOfPHP/PHP-CS-Fixer#6238. That's probably the one causing this.

**Comment by VincentLanglet** [comment]
@7ochem Can you rebase ? The linter build should be fixed.

**Review by VincentLanglet — APPROVED** [review]

**Review by jordisala1991 — APPROVED** [review]
