### PR TITLE
Use AdminCode as key instead of id in the AdminSearchCompilerPass

### LINKED ISSUE #7510: Disable global search by admin options does not work
The disable global search by admin option introduced in [#6609](https://github.com/sonata-project/SonataAdminBundle/pull/6609) does not seems to have any effects.

`AdminSearchCompilerPass` set the index of the `adminSearch` table with the `id` of the tagged admin (https://github.com/sonata-project/SonataAdminBundle/blob/f26feb598e32d194aa3ad82609bb1a27ebcd67e5/src/DependencyInjection/Compiler/AdminSearchCompilerPass.php#L51).

However, the `SearchHandler` look for `$admin->getCode()` as index: https://github.com/sonata-project/SonataAdminBundle/blob/f26feb598e32d194aa3ad82609bb1a27ebcd67e5/src/Search/SearchHandler.php#L44

services.yaml :
```yaml

  App\Admin\Entity1:
    tags:
      - name: sonata.admin
        global_search: false
  App\Admin\Entity2:
    tags:
      - name: sonata.admin
        global_search: false
```

adminSearch dump:
```php
array:2 [▼
  "App\Admin\Entity1" => false
  "App\Admin\Entity2" => false
]
```

$admin->getCode() dump
```admin.entity1```

### Environment
```
sonata-project/admin-bundle              3.105.0           
sonata-project/block-bundle              3.23.0            
sonata-project/cache                     2.1.1             
sonata-project/core-bundle               3.20.0            
sonata-project/doctrine-extensions       1.12.0            
sonata-project/doctrine-orm-admin-bundle 3.35.0            
sonata-project/exporter                  2.6.2             
sonata-project/form-extensions           0.1.2             
sonata-project/intl-bundle               2.7.0             
sonata-project/twig-extensions           0.1.1 
```
```
symfony 4.4
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

I am targeting this branch, because bugfix.

Closes #7510.

## Changelog

```markdown
### Fixed
- Disabling `global_search` for admin with non-default code.
```

### CODE REVIEW

File: src/SonataAdminBundle.php [hunk 1]
```diff
@@ -34,7 +34,7 @@ public function build(ContainerBuilder $container): void
     {
         $container->addCompilerPass(new AddDependencyCallsCompilerPass());
         $container->addCompilerPass(new AddFilterTypeCompilerPass());
-        $container->addCompilerPass(new AdminSearchCompilerPass());
+        $container->addCompilerPass(new AdminSearchCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION, -1);
```
Comment (VincentLanglet) [inline src/SonataAdminBundle.php:37]: Need to be after AddDependencyCallsCompilerPass

File: src/DependencyInjection/Compiler/AdminSearchCompilerPass.php [hunk 2]
```diff
@@ -41,14 +41,15 @@ public function process(ContainerBuilder $container): void
         foreach ($container->findTaggedServiceIds(TaggedAdminInterface::ADMIN_TAG) as $id => $tags) {
             $this->validateAdminClass($container, $id);
 
+            $adminCode = $container->getDefinition($id)->getArgument(0);
```
Comment (VincentLanglet) [inline src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: I don't see a better way to get the admin code...

Comment (jordisala1991) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: This will be a problem for auto configuration right?

Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: This will need to be done in another way the day we'll have full-auto configuration. Maybe later this could be replace by some static `$class::getCode` method call. But we currently don't. Even https://github.com/sonata-project/SonataAdminBundle/pull/7660 since to not touch the constructor definition.

Since the code is used to access the value in the SearchHandler, I need to access to the code in the compiler pass.
In the ExtensionCompilerPass, the call `$admin->getArgument(1)` is made, so this won't be the first time we rely on the argument.

Comment (core23) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: When relying on the first argument, we should check if this is a valid `string` or use the `id` as a fallback

**Review by core23 — CHANGES_REQUESTED** [review]

File: tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php [hunk 3]
```diff
@@ -26,15 +28,24 @@ final class AdminSearchCompilerPassTest extends AbstractCompilerPassTestCase
...
+            PostAdmin::class,
+            ['admin_bar_code', Post::class, CRUDController::class]
+        );
         $adminBarDefinition->addTag('sonata.admin', ['global_search' => false]);
         $this->setDefinition('admin.bar', $adminBarDefinition);
 
-        $adminBazDefinition = new Definition(PostAdmin::class);
+        $adminBazDefinition = new Definition(
+            PostAdmin::class,
+            ['admin_bar_code', Post::class, CRUDController::class]
```
Comment (franmomu) [inline tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php]: what would be the use case for someone to use the same code for two admins?

Comment (VincentLanglet) [reply tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php]: My mistake, it need to be 'admin_baz_code'

Comment (VincentLanglet) [reply tests/DependencyInjection/Compiler/AdminSearchCompilerPassTest.php]: Fixed

File: src/DependencyInjection/Compiler/AdminSearchCompilerPass.php (hunk 2 above)
Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: I added a string check.

File: src/DependencyInjection/Compiler/AdminSearchCompilerPass.php [hunk 4]
```diff
@@ -39,7 +39,18 @@ public function process(ContainerBuilder $container): void
         $adminSearch = [];
 
         foreach ($container->findTaggedServiceIds(TaggedAdminInterface::ADMIN_TAG) as $id => $tags) {
-            $this->validateAdminClass($container, $id);
+            $adminClass = $this->validateAdminClass($container, $id);
+
+            $argument = $container->getDefinition($id)->getArgument(0);
+            $adminCode = $container->getParameterBag()->resolveValue($argument);
+            if (!\is_string($adminCode)) {
+                throw new \TypeError(sprintf(
```
Comment (core23) [inline src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: Not sure if this is BC

Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: According to the `TaggedAdminInterface` comment the constructor signature MUST be:
```
public function __construct(string $code, string $class, string $controller, ...);
```

And indeed the AddDependencyCallsCompiler (which is called before the AdminSerchCompilerPass) is doing 
```
$this->replaceDefaultArguments([
     0 => $id,
     2 => $defaultController,
], $definition, $parentDefinition);
```

So this is already not supposed to work correctly if the first argument is not a string.

Comment (core23) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: We do not enforce this signature:
https://github.com/sonata-project/SonataAdminBundle/blob/e5c9405d937726cdd76a237669443096f4c6dfd0/src/DependencyInjection/Admin/TaggedAdminInterface.php#L40

IMHO enforcing a specific constructor is against good coding practice.

When looking at the mentioned compiler pass, it looks like this the argument are only replaced if there is no existing argument:
https://github.com/sonata-project/SonataAdminBundle/blob/e5c9405d937726cdd76a237669443096f4c6dfd0/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L461-L463

Maybe it's just a theoretical case...

Comment (jordisala1991) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: What if you only pass the admins without trying to get the code from the dependency injection, and then on the search class you modify that array to add the code as key at runtime (only executed once)

Or do a not smart array search where you have to iterate over the whole array.

Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: > IMHO enforcing a specific constructor is against good coding practice.

I agree, but currently `ExtensionCompilerPass` we does, with the `$admin->getArgument(1);` call.
Also, if someone change the signature like `__construct(?Foo $foo, ...)`, the AddDependencyCalls could replace null value by something wrong.

Lastly if you changed the signature, it means that the admin code won't be the id service too and this won't work anymore...

But clearly I would prefer to get rid of the Admin constructor for the next sonata version. And this shouldn't be too hard:
- The admin code could use a method setCode
- The class could use a method setClass
- There is already a `setBaseControllerName` method

And the code/class/controllerName could be a tag property instead of being in the constructor.

@jordisala1991 It could be better indeed, but how would you do that ?
I think I can have the admin instance with `new Reference($id)`, but I cannot pass an array with keys Admin and value bool.

Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: I reopened https://github.com/sonata-project/SonataAdminBundle/issues/6723 ; this would solve all the constructor issues.

Comment (VincentLanglet) [reply src/DependencyInjection/Compiler/AdminSearchCompilerPass.php]: I started the POC https://github.com/sonata-project/SonataAdminBundle/pull/7684 which should solve the issue

**Comment by VincentLanglet** [comment]
This is now ready @sonata-project/contributors @core23

**Review by jordisala1991 — APPROVED** [review]

**Review by core23 — APPROVED** [review]
