### PR TITLE
Use an event listener to configure CRUDController

### LINKED ISSUE #6773: Cannot use a custom controller on master branch
Some informations can be found https://github.com/sonata-project/SonataAdminBundle/pull/6770

Both
```
    Sonata\AdminBundle\Tests\App\Admin\FooAdmin:
        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, Sonata\AdminBundle\Controller\CRUDController]
        tags:
            - {name: sonata.admin, manager_type: test, label: Foo}
```
and
```
    Sonata\AdminBundle\Tests\App\Admin\FooAdmin:
        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, Sonata\AdminBundle\Tests\App\Controller\CustomCRUDController]
        tags:
            - {name: sonata.admin, manager_type: test, label: Foo}
```
configuration doesn't work.

Only 
```
Sonata\AdminBundle\Tests\App\Admin\FooAdmin:
        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, ~]
        tags:
            - {name: sonata.admin, manager_type: test, label: Foo}
```
does.

The error are
```
[critical] Uncaught PHP Exception LogicException: ""Sonata\AdminBundle\Controller\CRUDController" has no container set, did you forget to define it as a service subscriber?" at /home/runner/work/SonataAdminBundle/SonataAdminBundle/vendor/symfony/framework-bundle/Controller/ControllerResolver.php line 39
```

It seems related to the fact that we changed how we register the default controller on dependency injection. Before that change it was a Symfony controller that it was not explicitly declared on DI (the old way of registering controllers). After the change it was explicitly declared on DI: https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Resources/config/core.php#L164-L167

### PR DESCRIPTION
**Pull request by franmomu**
## Subject

To configure the admin associated in a CRUDController, it was used `CRUDController::setContainer` which called `AbstractController::setContainer`, the previous call is internal, so it may change.

This commit adds an event listener on `KernelEvents::CONTROLLER` which configures the CRUDController and removes `CRUDController::setContainer` method.

I was going to do it in `3.x`, but since someone may have overriden `CRUDController::configure()` method, I wasn't sure if there was a way to make it BC, so we can deprecate this method in `3.x` and remove it here.

I am targeting this branch, because these changes break BC.

Closes #6773.

## Changelog

```markdown
### Removed
- Removed `CRUDController::configure()` method.
```

## To do

- [x] Add tests for `ConfigureCRUDControllerListener`.
- [x] [Deprecate `CRUDController::configure()` in 3.x.](https://github.com/sonata-project/SonataAdminBundle/pull/6751)

### CODE REVIEW

File: src/Controller/CRUDController.php [hunk 1]
```diff
@@ -916,17 +903,15 @@ public function getRequest(): Request
...
+     * @throws \InvalidArgumentException
      */
     final public function configureAdmin(Request $request): void
     {
         $adminCode = $request->get('_sonata_admin');
 
         if (null === $adminCode) {
-            // NEXT_MAJOR: Change \RuntimeException by \InvalidArgumentException in the next line.
-            throw new \RuntimeException(sprintf(
+            throw new \InvalidArgumentException(sprintf(
```
Comment (greg0ire) [inline src/Controller/CRUDController.php:914]: Should this change be moved to a separate commit? It does not seem to fit the description.

Comment (OskarStark) [reply src/Controller/CRUDController.php:914]: Makes sense

File: src/EventListener/ConfigureCRUDControllerListener.php [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+
+namespace Sonata\AdminBundle\EventListener;
+
+use Sonata\AdminBundle\Controller\CRUDController;
+use Symfony\Component\EventDispatcher\EventSubscriberInterface;
+use Symfony\Component\HttpKernel\Event\ControllerEvent;
+use Symfony\Component\HttpKernel\KernelEvents;
+
+/**
+ * @internal
```
Comment (VincentLanglet) [inline src/EventListener/ConfigureCRUDControllerListener.php:22]: Why internal ?

File: src/Controller/CRUDController.php (hunk 1 above)
Comment (franmomu) [reply src/Controller/CRUDController.php:914]: 👍 I will continue with this once `3.x` is merged in this branch and I'll split the PR.

File: src/EventListener/ConfigureCRUDControllerListener.php (hunk 2 above)
Comment (franmomu) [reply src/EventListener/ConfigureCRUDControllerListener.php:22]: It's internal to this package for configuring `CRUDController`, I don't think people should use it.

**Comment by VincentLanglet** [comment]
@OskarStark https://github.com/sonata-project/SonataAdminBundle/pull/6780 is needed first

File: tests/App/config/services.yml [hunk 3]
```diff
@@ -42,10 +42,14 @@ services:
         class: Sonata\AdminBundle\Tests\App\Datagrid\ProxyQuery
 
     Sonata\AdminBundle\Tests\App\Admin\FooAdmin:
-        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, Sonata\AdminBundle\Controller\CRUDController]
+        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, 'sonata.admin.controller.crud']
         tags:
             - {name: sonata.admin, manager_type: test, label: Foo}
 
+    Sonata\AdminBundle\Tests\App\Controller\CustomCRUDController:
+        public: true
```
Comment (VincentLanglet) [inline tests/App/config/services.yml:50]: The recommended symfony config is 
```
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: ../src/*
        exclude: ../src/{Entity,Migrations,Kernel.php}

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: ../src/Controller
        tags: [controller.service_arguments]
```
(See https://github.com/symfony/demo/blob/main/config/services.yaml)

So CRUDController will be autowire by default, but will be private too.
Do we have another way than asking them to put all the CRUDController public ?

File: tests/App/config/services.yml [hunk 4]
```diff
@@ -42,10 +42,14 @@ services:
         class: Sonata\AdminBundle\Tests\App\Datagrid\ProxyQuery
 
     Sonata\AdminBundle\Tests\App\Admin\FooAdmin:
-        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, Sonata\AdminBundle\Controller\CRUDController]
+        arguments: [~, Sonata\AdminBundle\Tests\App\Model\Foo, 'sonata.admin.controller.crud']
```
Comment (VincentLanglet) [inline tests/App/config/services.yml:45]: Do we have a way to make this working with `Sonata\AdminBundle\Controller\CRUDController` to avoid the BC-break ?

Does an alias could work ?

File: tests/App/config/services.yml (hunk 3 above)
Comment (franmomu) [reply tests/App/config/services.yml:50]: Yes, I'll change it, I was just trying. BTW controllers are not private with this configuration, adding the `controller.service_arguments` makes them public.

File: tests/App/config/services.yml (hunk 4 above)
Comment (franmomu) [reply tests/App/config/services.yml:45]: I guess so, what we can do is to create `sonata.admin.controller.crud` in `3.x` and deprecate `Sonata\AdminBundle\Controller\CRUDController`, but I don't know why someone would use `Sonata\AdminBundle\Controller\CRUDController`.

Comment (VincentLanglet) [reply tests/App/config/services.yml:52]: > but I don't know why someone would use `Sonata\AdminBundle\Controller\CRUDController`.

I find more natural to pass a class rather a name.
And some people can prefer to pass the default values.

Comment (VincentLanglet) [reply tests/App/config/services.yml:52]: And why https://github.com/sonata-project/SonataAdminBundle/pull/6793/commits/11217d12bfabb651dfec8863a94a46442d93ccd2 is not working ?

Comment (VincentLanglet) [reply tests/App/config/services.yml:52]: If we don't support the old way, we need to update
https://github.com/sonata-project/SonataAdminBundle/blob/master/docs/cookbook/recipe_knp_menu.rst#hiding-menu-items
https://github.com/sonata-project/SonataAdminBundle/blob/master/docs/cookbook/recipe_knp_menu.rst#show-menu-item-without-treeview

And I don't know if we need to change the explanation somewhere else.

File: tests/App/config/services.yml [hunk 5]
```diff
@@ -1,9 +1,16 @@
 services:
-    # Under real conditions, this service is registered by "doctrine/doctrine-bundle"
-    database_connection:
-        class: Sonata\AdminBundle\Tests\Fixtures\DoctrineBundle\Connection
+    _defaults:
+        autowire: true
+        autoconfigure: true
+        public: false
```
Comment (dmaicher) [inline tests/App/config/services.yml:5]: this can be removed since we require at least Symfony 4, right? Its the default then.

File: tests/App/config/services.yml (hunk 4 above)
Comment (dmaicher) [reply tests/App/config/services.yml:52]: > And why [11217d1](https://github.com/sonata-project/SonataAdminBundle/commit/11217d12bfabb651dfec8863a94a46442d93ccd2) is not working ?

maybe the alias needs to be public then?

**Comment by VincentLanglet** [comment]
@franmomu WDYT about adding this commit https://github.com/sonata-project/SonataAdminBundle/pull/6793/commits/1cfc0991ff44f7a132050b7fc38f2638822238ed ?

**Review by VincentLanglet — APPROVED** [review]

**Comment by franmomu** [comment]
So looks like this `configureAdmin` code is used also in actions, like:

https://github.com/sonata-project/SonataAdminBundle/blob/1dea724086d681bb2d668b2228f33c69cc71cd35/src/Action/AppendFormFieldElementAction.php#L54-L64

I haven't given much thought, but maybe this should be changed and create an `AdminAwareInterface` which would implement the actions that need an admin and the `CRUDController`. The event listener would check if the controller implements that interface and fetch the corresponding admin from request, configure it and set it to those instances.

**Comment by VincentLanglet** [comment]
I think we should try to stop changing too much admin/controller way of working before 4.0 or at least decide a quick milestone. This PR can fix #6773, this seems enough for now. And after this nothing more is really needed to start 4.0 (except removing all the NEXT_MAJOR or closing some api).

There are multiple issue about splitting/changing admin and crudController with the 5.0 milestone. This could be one more.

WDYT ? Do you think it's good enough to merge this PR like this ?

**Comment by VincentLanglet** [comment]
@franmomu Can you take a look at the conflict ? :)

**Review by phansys — APPROVED** [review]

File: tests/App/config/services.yml (hunk 4 above)
Comment (dmaicher) [reply tests/App/config/services.yml:51]: Shall we include the "fix" to make the alias public here?

Comment (franmomu) [reply tests/App/config/services.yml:51]: We changed in `4.0` the services to not use FQCN (at least some of them I think), IMHO we shouldn't promote using it, maybe triggering a deprecation in `3.x` if the user has specified `CRUDController::class` explicitly as a third parameter.

But I'll add it if you think it would be useful.

Comment (dmaicher) [reply tests/App/config/services.yml:51]: Yeah either triggering a deprecation or making the alias public. Both seem fine to me :blush:

Comment (wbloszyk) [reply tests/App/config/services.yml:51]: My sugestion is remove controller from `__constructor()`. This functionality can be replace by improving `RouteCollecton` to allow do something like this:
```php
final class MediaAdmin extends AbstractAdmin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->add('myCustom'); // Action gets added automatically
        $collection->add('view', $this->getRouterIdParameter().'/view');

        // new options
        $collection->add('App/Controller/CustomCRUDController::myCustom'); // Action gets added automatically
        $collection->add('App/Controller/CustomCRUDController::view', $this->getRouterIdParameter().'/view');
    }
}
```

In this case we can also split `CRUDController` to `*Action` which extends `BaseCRUDAction`.

**Comment by VincentLanglet** [comment]
You can now rebase @franmomu to fix the psalm error

File: tests/App/config/services.yml (hunk 4 above)
Comment (franmomu) [reply tests/App/config/services.yml:51]: I'd rather remove it from the `__construct` too, but not sure how. 

Let's use https://github.com/sonata-project/SonataAdminBundle/pull/6796 for this.

**Comment by franmomu** [comment]
any idea about those random errors https://github.com/sonata-project/SonataAdminBundle/pull/6615/checks?check_run_id=1779444700?

**Review by VincentLanglet — APPROVED** [review]

File: tests/App/config/services.yml (hunk 4 above)
Comment (wbloszyk) [reply tests/App/config/services.yml:51]: Can we move it to the `sonata_admin.admin` tag? It will be more obvious. After study this:
https://github.com/sonata-project/SonataAdminBundle/blob/a17000609e5b1d64c0102606a06267f75b10f6b5/src/Route/RouteCollection.php#L70-L105
We can do it and remove `RouteCollection::baseController` property:
```php
final class MediaAdmin extends AbstractAdmin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->add('myCustom'); // Action gets added automatically
        $collection->add('view', $this->getRouterIdParameter().'/view');

        // new options
        $collection->add('myCustom', null, ['_controller' => 'App/Controller/CustomCRUDController']);
        $collection->add('myCustom', null, ['_controller' => 'app.controller.custom_contoller']);
    }
}
```

Comment (VincentLanglet) [reply tests/App/config/services.yml:51]: All of the 3 parameters of an admin: code, class and controller could (and should IMHO) at least be moved to the `sonata_admin.admin` instead.
I have already created this issue: https://github.com/sonata-project/SonataAdminBundle/issues/6723
