### PR TITLE
Handle ParentAssociationMapping when looking for new instance

### LINKED ISSUE #5738: CollectionType for OneToOneToMany relation seems broken
#### Sonata packages

```
sonata-project/admin-bundle              3.54.1 3.54.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.1 3.18.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.1  1.3.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.10.0 3.11.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
```

#### Symfony packages

```
symfony/asset                v4.3.5  v4.3.6  Symfony Asset Component
symfony/browser-kit          v4.3.5  v4.3.6  Symfony BrowserKit Component
symfony/cache                v4.3.5  v4.3.6  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.3.5  v4.3.6  Symfony Config Component
symfony/console              v4.3.5  v4.3.6  Symfony Console Component
symfony/contracts            v1.1.7  v1.1.7  A set of abstractions extracted out of the Symfony components
symfony/css-selector         v4.3.5  v4.3.6  Symfony CssSelector Component
symfony/debug                v4.3.5  v4.3.6  Symfony Debug Component
symfony/debug-bundle         v4.3.5  v4.3.6  Symfony DebugBundle
symfony/dependency-injection v4.3.5  v4.3.6  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.3.5  v4.3.6  Symfony Doctrine Bridge
symfony/dom-crawler          v4.3.5  v4.3.6  Symfony DomCrawler Component
symfony/dotenv               v4.3.5  v4.3.6  Registers environment variables from a .env file
symfony/event-dispatcher     v4.3.5  v4.3.6  Symfony EventDispatcher Component
symfony/expression-language  v4.3.5  v4.3.6  Symfony ExpressionLanguage Component
symfony/filesystem           v4.3.5  v4.3.6  Symfony Filesystem Component
symfony/finder               v4.3.5  v4.3.6  Symfony Finder Component
symfony/flex                 v1.4.6  v1.4.6  Composer plugin for Symfony
symfony/form                 v4.3.5  v4.3.6  Symfony Form Component
symfony/framework-bundle     v4.3.5  v4.3.6  Symfony FrameworkBundle
symfony/http-foundation      v4.3.5  v4.3.6  Symfony HttpFoundation Component
symfony/http-kernel          v4.3.5  v4.3.6  Symfony HttpKernel Component
symfony/inflector            v4.3.5  v4.3.6  Symfony Inflector Component
symfony/intl                 v4.3.5  v4.3.6  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mime                 v4.3.5  v4.3.6  A library to manipulate MIME messages
symfony/monolog-bridge       v4.3.5  v4.3.6  Symfony Monolog Bridge
symfony/monolog-bundle       v3.4.0  v3.4.0  Symfony MonologBundle
symfony/options-resolver     v4.3.5  v4.3.6  Symfony OptionsResolver Component
symfony/phpunit-bridge       v4.3.5  v4.3.6  Symfony PHPUnit Bridge
symfony/polyfill-apcu        v1.12.0 v1.12.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype       v1.12.0 v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv       v1.12.0 v1.12.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu    v1.12.0 v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn    v1.12.0 v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring    v1.12.0 v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72       v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73       v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process              v4.3.5  v4.3.6  Symfony Process Component
symfony/property-access      v4.3.5  v4.3.6  Symfony PropertyAccess Component
symfony/routing              v4.3.5  v4.3.6  Symfony Routing Component
symfony/security-acl         v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.3.5  v4.3.6  Symfony SecurityBundle
symfony/security-core        v4.3.5  v4.3.6  Symfony Security Component - Core Library
symfony/security-csrf        v4.3.5  v4.3.6  Symfony Security Component - CSRF Library
symfony/security-guard       v4.3.5  v4.3.6  Symfony Security Component - Guard
symfony/security-http        v4.3.5  v4.3.6  Symfony Security Component - HTTP Integration
symfony/serializer           v4.3.5  v4.3.6  Symfony Serializer Component
symfony/stopwatch            v4.3.5  v4.3.6  Symfony Stopwatch Component
symfony/swiftmailer-bundle   v3.2.8  v3.3.0  Symfony SwiftmailerBundle
symfony/templating           v4.3.5  v4.3.6  Symfony Templating Component
symfony/translation          v4.3.5  v4.3.6  Symfony Translation Component
symfony/twig-bridge          v4.3.5  v4.3.6  Symfony Twig Bridge
symfony/twig-bundle          v4.3.5  v4.3.6  Symfony TwigBundle
symfony/validator            v4.3.5  v4.3.6  Symfony Validator Component
symfony/var-dumper           v4.3.5  v4.3.6  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter         v4.3.5  v4.3.6  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle  v4.3.5  v4.3.6  Symfony WebProfilerBundle
symfony/yaml                 v4.3.5  v4.3.6  Symfony Yaml Component
```

#### PHP version

```
PHP 7.3.8-1+0~20190807.43+debian9~1.gbp7731bf (cli) (built: Aug  7 2019 19:46:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8-1+0~20190807.43+debian9~1.gbp7731bf, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

I have a Contract entity, with a field `subscription` (OneToOne).
This is a Subscription entity, with a field `appendixes` (OneToMany).
Which is a Document entity.

In Contract.php, I have a getter
```
    /**
     * @return Subscription|null
     */
    public function getSubscription()
    {
        return $this->subscription;
    }
```

In Subscription, I have a getter
```
    /**
     * @return Document[]|Collection
     */
    public function getAppendixes()
    {
        return $this->appendixes;
    }
```

In the configureFormField of ContractAdmin, I have
```
$formMapper->add(
    'subscription.appendixes',
    CollectionType::class,
    ['by_reference' => false],
    ['edit'   => 'inline', 'inline' => 'table']
)
```

## Expected results

No error

## Actual results

```
Neither the property "appendixes" nor one of the methods "getAppendixes()", "appendixes()", "isAppendixes()", "hasAppendixes()", "__get()" exist and have public access in class "AssuranceVie\Entity\Contract".
```

### PR DESCRIPTION
**Pull request by VincentLanglet**
## Subject

When using `->add('foo.bar', CollectionType::class)` in PostAdmin, the adminHelper try to call the function `addBar` on Post entity instead of Foo entity.

After the PR, it will do `$post->getFoo()->addBar()`;

I am targeting this branch, because BC.

Closes #5738

## Changelog
```markdown
### Fixed
Class Helper addNewInstance take care about parentAssociation mapping.
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
@core23 Test added

**Comment by VincentLanglet** [comment]
@OskarStark I'm looking for a second approval in order to merge :)

File: src/Admin/AdminHelper.php [hunk 1]
```diff
@@ -231,6 +229,19 @@ public function addNewInstance($object, FieldDescriptionInterface $fieldDescript
...
         $instance = $fieldDescription->getAssociationAdmin()->getNewInstance();
         $mapping = $fieldDescription->getAssociationMapping();
+        $parentMappings = $fieldDescription->getParentAssociationMappings();
+
+        foreach ($parentMappings as $parentMapping) {
+            $method = sprintf('get%s', Inflector::classify($parentMapping['fieldName']));
+
+            if (!method_exists($object, $method)) {
+                throw new \RuntimeException(
+                    sprintf('Please add a method %s in the %s class!', $method, ClassUtils::getClass($object))
```
Comment (phansys) [inline src/Admin/AdminHelper.php]: I know there is a previous exception like this using a different type and different wording, but IMO this way is more accurate:
```suggestion
            if (!is_callable([$object, $method])) {
                throw new \BadMethodCallException(
                    sprintf('Method %s::%s() does not exist.', ClassUtils::getClass($object), $method)
```

File: tests/Admin/AdminHelperTest.php [hunk 2]
```diff
@@ -89,6 +90,29 @@ public function testAddNewInstance(): void
...
+    {
+        $admin = $this->createMock(AdminInterface::class);
+        $admin->expects($this->once())->method('getNewInstance')->willReturn(new \stdClass());
+
+        $fieldDescription = $this->createMock(FieldDescriptionInterface::class);
+        $fieldDescription->expects($this->once())->method('getAssociationAdmin')->willReturn($admin);
+        $fieldDescription->expects($this->once())->method('getAssociationMapping')->willReturn(['fieldName' => 'fooBar']);
+        $fieldDescription->expects($this->once())->method('getParentAssociationMappings')->willReturn([['fieldName' => 'parent']]);
+
+        $object2 = $this->getMockBuilder('stdClass')
```
Comment (phansys) [inline tests/Admin/AdminHelperTest.php]:
```suggestion
        $object2 = $this->getMockBuilder(\stdClass::class)
```

File: tests/Admin/AdminHelperTest.php [hunk 3]
```diff
@@ -89,6 +90,29 @@ public function testAddNewInstance(): void
...
+            ->setMethods(['addFooBar'])
+            ->getMock();
+        $object2->expects($this->once())->method('addFooBar');
+
+        $object1 = $this->getMockBuilder('stdClass')
```
Comment (phansys) [inline tests/Admin/AdminHelperTest.php]:
```suggestion
        $object1 = $this->getMockBuilder(\stdClass::class)
```

File: src/Admin/AdminHelper.php (hunk 1 above)
Comment (VincentLanglet) [reply src/Admin/AdminHelper.php]: Should I make the changes for the other exception too @phansys ?

Comment (phansys) [reply src/Admin/AdminHelper.php]: I think yes, regardless technically it will be a BC break (`\BadMethodCallException` does not extend `\RuntimeException`).
Let's wait for more opinions.

**Comment by VincentLanglet** [comment]
@phansys I made some changes. WDYT about them ?
